/***************************************************************************
 *   controldatadlg.cpp                                                    *
 *   Copyright (C) 2014 by Daniel Suson                                    *
 *   suson@calumet.purdue.edu                                              *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU General Public License     *
 *   along with this program; if not, write to the                         *
 *   Free Software Foundation, Inc.,                                       *
 *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
 *                                                                         *
 *   In addition, as a special exception, the copyright holders give       *
 *   permission to link the code of this program with any edition of       *
 *   the Qt library by Trolltech AS, Norway (or with modified versions     *
 *   of Qt that use the same license as Qt), and distribute linked         *
 *   combinations including the two.  You must obey the GNU General        *
 *   Public License in all respects for all of the code used other than    *
 *   Qt.  If you modify this file, you may extend this exception to        *
 *   your version of the file, but you are not obligated to do so.  If     *
 *   you do not wish to do so, delete this exception statement from        *
 *   your version.                                                         *
 ***************************************************************************
 * Description:                                                            *
 *                                                                         *
 * This class defines the control data dialog structure associated with    *
 * the Qt4 user interface.                                                 *
 * ----------------------- Change Log ------------------------------------ *
 * Date    Name         Description                                        *
 *                                                                         *
 ***************************************************************************
 * This software evolved from work that was done by Eric Hivon at the      *
 * California Institute of Technology on the MASTER algorithm (Hivon, E.,  *
 * et al., ApJ, vol 567, p 2).  It adapts or interfaces with these         *
 * packages:                                                               *
 *                                                                         *
 * HealPix         (http://www.eso.org/science/healpix/)                   *
 * FTOOLS & FITSIO (http://heasarc.gsfc.nasa.gov/docs/corp/software.html)  *
 *                                                                         *
 * Any publications or presentations that use results generated by this    *
 * program must reference the fact that it was developed by Daniel Suson   *
 ***************************************************************************/
#include "controldatadlg.h"
#include <limits>

controlDataDialog::controlDataDialog(association *assoc, std::istream* i, std::ostream* o, successFunc s, cancelFunc c)
                   : controlDataDialogParent(assoc)
{
	input = i;
	output = o;
	successF = s;
	cancelF = c;
}

controlDataDialog::~controlDataDialog()
{
}

void controlDataDialog::clearInput()
{
	input->clear();
	input->ignore(std::numeric_limits<std::streamsize>::max(), '\n');
}

void controlDataDialog::execute()
{
	setDataType();
	setResolution();
	setStrength();
	setControlType();
	setOperation();

	if(confirm())
		buildControlData(dataType, true);
	else
		dataCreationCancelled();
}

void controlDataDialog::setDataType()
{
	int dType = 0;
	do
	{
		clearInput();

		(*output) << "Enter the data type to be created.\n"
			  << "\t1. Data\n"
			  << "\t2. Weights\n"
			  << "\t3. Noise\n"
			  << "\t4. Filter\n"
			  << "\t5. Beam\n";
	}while(		!((*input)>>dType)
				|| dType > 5
				|| dType < 1);

	if(dType == 1)
		dataType = FILETYPE::InputData;
	else if(dType == 2)
		dataType = FILETYPE::InputWeights;
	else if(dType == 3)
		dataType = FILETYPE::InputNoise;
	else if(dType == 4)
		dataType = FILETYPE::InputFilter;
	else
		dataType = FILETYPE::InputBeam;
}

void controlDataDialog::setResolution()
{
	double res1, res2;
	do
	{
		clearInput();
		(*output) << "Enter the RA Resolution.\t";
	}while(		!((*input)>>res1)
				|| res1 <= 0);

	resRA = res1;

	do
	{
		clearInput();
		(*output) << "Enter the Dec Resolution.\t";
	}while(		!((*input)>>res2)
				|| res2 <= 0);

	resDec = res2;
}

void controlDataDialog::setStrength()
{
	double str;
	do
	{
		clearInput();
		(*output) << "Enter the Signal Strength.\t";
	}while(		!((*input)>>str)
				|| str <= 0);

	signalStrength = str;
}

void controlDataDialog::setControlType()
{
	int cType = 0;
	do
	{
		clearInput();

		(*output) << "Enter the control type to be created.\n"
			  << "\t1. Full Sky\n"
			  << "\t2. Partial Sky\n"
			  << "\t3. Checkerboard\n"
			  << "\t4. Delta\n"
			  << "\t5. Gaussian\n"
			  << "\t6. Spherical Harmonic\n";
	}while(		!((*input)>>cType)
				|| cType > 6
				|| cType < 1);

	if(cType == 1)
	{
		dataSet = CONTROLTYPE::Uniform;
	}
	else if(cType == 2)
	{
		dataSet = CONTROLTYPE::Regional;

		double t, b;
		do
		{
			do
			{
				clearInput();
				(*output) << "Enter the top bounds.\t";
			}while(		!((*input)>>t));

			do
			{
				clearInput();
				(*output) << "Enter the bottom bounds.\t";
			}while(		!((*input)>>b));

			if(t < b)
				(*output) << "ERROR. Top must be greater than Bottom.\n";
		}while(t < b);


		top = t;
		bottom = b;

		double l, r;
		do
		{
			do
			{
				clearInput();
				(*output) << "Enter the left bounds.\t";
			}while(		!((*input)>>l));

			do
			{
				clearInput();
				(*output) << "Enter the right bounds.\t";
			}while(		!((*input)>>r));

			if(r < l)
				(*output) << "ERROR. Right must be greater than Left.\n";
		}while(r < l);

		to = r;
		from = l;
	}
	else if(cType == 3)
	{
		dataSet = CONTROLTYPE::Checker;

		double res1, res2;
		do
		{
			clearInput();
			(*output) << "Enter the RA checker width.\t";
		}while(		!((*input)>>res1)
					|| res1 <= 0);

		checkRA = res1;

		do
		{
			clearInput();
			(*output) << "Enter the Dec checker height.\t";
		}while(		!((*input)>>res2)
					|| res2 <= 0);

		checkDec = res2;
	}
	else if(cType == 4)
	{
		dataSet = CONTROLTYPE::Delta;

		double ra, dec;
		do
		{
			clearInput();
			(*output) << "Enter the RA point.\t";
		}while(		!((*input)>>ra)
					|| ra < -180
					|| ra > 180);

		peakRA = ra;

		do
		{
			clearInput();
			(*output) << "Enter the Dec point.\t";
		}while(		!((*input)>>dec)
					|| dec < -90
					|| dec > 90);

		peakDec = dec;
	}
	else if(cType == 5)
	{
		dataSet = CONTROLTYPE::Gaussian;

		double ra, dec, width;
		do
		{
			clearInput();
			(*output) << "Enter the RA point.\t";
		}while(		!((*input)>>ra)
					|| ra < -180
					|| ra > 180);

		peakRA = ra;

		do
		{
			clearInput();
			(*output) << "Enter the Dec point.\t";
		}while(		!((*input)>>dec)
					|| dec < -90
					|| dec > 90);

		peakDec = dec;

		do
		{
			clearInput();
			(*output) << "Enter the std. dev.\t";
		}while(		!((*input)>>width)
					|| width < -180
					|| width > 180);

		fwhm = width;
	}
	else
	{
		dataSet = CONTROLTYPE::Harmonic;

		long lVal, mVal;
		do
		{
			clearInput();
			(*output) << "Enter l parameter.\t";
		}while(		!((*input)>>lVal)
					|| lVal < 0);

		l = lVal;

		do
		{
			clearInput();
			(*output) << "Enter m parameter.\t";
		}while(		!((*input)>>mVal)
					|| mVal < -lVal
					|| mVal >  lVal);
		m = mVal;
	}
}

void controlDataDialog::setOperation()
{
	int opType = 0;
	do
	{
		clearInput();

		(*output) << "Enter the operation to be performed.\n"
			  << "\t1. Addition\n"
			  << "\t2. Subtraction\n"
			  << "\t3. Scale\n"
			  << "\t4. Replace\n"
			  << "\t5. Invert\n"
			  << "\t6. Mirror\n";
	}while(		!((*input)>>opType)
				|| opType > 6
				|| opType < 1);

	if(opType == 1)
		operation = M_OP::Add;
	else if(opType == 2)
		operation = M_OP::Subtract;
	else if(opType == 3)
		operation = M_OP::Scale;
	else if(opType == 4)
		operation = M_OP::Replace;
	else if(opType == 5)
		operation = M_OP::Invert;
	else
		operation = M_OP::Mirror;
}

bool controlDataDialog::confirm()
{
	char confirm = 'n';

	(*output) << "You have selected to create a " << controlNames[static_cast<int>(dataSet)] << " control structure"
			  << " for the data type: " << dataTypeNames[static_cast<int>(dataType)] << ".\n"
			  << "With an resolution of (ra x dec): " << resRA << " x " << resDec
			  << " and a signal strength of: " << signalStrength << ".\n";

	if(dataSet == CONTROLTYPE::Regional)
	{
		(*output) << "The parameters for the " << controlNames[static_cast<int>(dataSet)] << " are: \n"
				  << "\tTop:    " << top << "\n"
				  << "\tBottom: " << bottom << "\n"
				  << "\tLeft:   " << from << "\n"
				  << "\tRight:  " << to << "\n";
	}
	else if(dataSet == CONTROLTYPE::Checker)
	{
		(*output) << "The parameters for the " << controlNames[static_cast<int>(dataSet)] << " are: \n"
				  << "\tChecker Width:  " << checkRA << "\n"
				  << "\tChecker Height: " << checkDec << "\n";
	}
	else if(dataSet == CONTROLTYPE::Delta)
	{
		(*output) << "The parameters for the " << controlNames[static_cast<int>(dataSet)] << " are: \n"
				  << "\tRA  Point: " << peakRA << "\n"
				  << "\tDec Point: " << peakDec << "\n";
	}
	else if(dataSet == CONTROLTYPE::Gaussian)
	{
		(*output) << "The parameters for the " << controlNames[static_cast<int>(dataSet)] << " are: \n"
				  << "\tRA  Point: " << peakRA << "\n"
				  << "\tDec Point: " << peakDec << "\n"
				  << "\tStd Dev:   " << fwhm << "\n";
	}
	else if(dataSet == CONTROLTYPE::Harmonic)
	{
		(*output) << "The parameters for the " << controlNames[static_cast<int>(dataSet)] << " are: \n"
				  << "\tl: " << l << "\n"
				  << "\tm: " << m << "\n";
	}

	do
	{
		clearInput();
		(*output) << "Confirm Y | N.\t";
	}while(		!((*input)>>confirm)
				|| !(   confirm == 'Y' || confirm == 'y'
					 || confirm == 'N' || confirm == 'n'));

	return confirm == 'y' || confirm == 'Y' ? true : false;
}

void controlDataDialog::buildControlData(FILETYPE f, bool b)
{
	successF(f, b);
}

void controlDataDialog::dataCreationCancelled()
{
	cancelF();
}

bool controlDataDialog::validate()
{
	return true;
}

void controlDataDialog::help()
{

}
