/***************************************************************************
 *   healpixdlg.cpp                                                        *
 *   Copyright (C) 2014 by Daniel Suson                                    *
 *   suson@calumet.purdue.edu                                              *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU General Public License     *
 *   along with this program; if not, write to the                         *
 *   Free Software Foundation, Inc.,                                       *
 *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
 *                                                                         *
 *   In addition, as a special exception, the copyright holders give       *
 *   permission to link the code of this program with any edition of       *
 *   the Qt library by Trolltech AS, Norway (or with modified versions     *
 *   of Qt that use the same license as Qt), and distribute linked         *
 *   combinations including the two.  You must obey the GNU General        *
 *   Public License in all respects for all of the code used other than    *
 *   Qt.  If you modify this file, you may extend this exception to        *
 *   your version of the file, but you are not obligated to do so.  If     *
 *   you do not wish to do so, delete this exception statement from        *
 *   your version.                                                         *
 ***************************************************************************
 * Description:                                                            *
 *                                                                         *
 * This class defines the healpix dialog structure associated with         *
 * the Qt4 user interface.                                                 *
 * ----------------------- Change Log ------------------------------------ *
 * Date    Name         Description                                        *
 *                                                                         *
 ***************************************************************************
 * This software evolved from work that was done by Eric Hivon at the      *
 * California Institute of Technology on the MASTER algorithm (Hivon, E.,  *
 * et al., ApJ, vol 567, p 2).  It adapts or interfaces with these         *
 * packages:                                                               *
 *                                                                         *
 * HealPix         (http://www.eso.org/science/healpix/)                   *
 * FTOOLS & FITSIO (http://heasarc.gsfc.nasa.gov/docs/corp/software.html)  *
 *                                                                         *
 * Any publications or presentations that use results generated by this    *
 * program must reference the fact that it was developed by Daniel Suson   *
 ***************************************************************************/
#include <math.h>
#include <limits>

#include "healpixdlg.h"

#include "../libanalyzer/matrixdata.h"
#include "../libanalyzer/healpix.h"

#include "../healpixdlgpar.h"

#define SIDERES 0.00001

healpixDialog::healpixDialog(association* assoc, std::istream* i, std::ostream* o, std::function<void()> s, std::function<void()> c)
              : healpixDialogParent(assoc)
{
	input = i;
	output = o;
	successFunc = s;
	cancelFunc = c;
}

healpixDialog::~healpixDialog()
{
}

void healpixDialog::execute()
{
	double raRes = 0.0, decRes = 0.0;
    if (dataAssoc->exists(fileType::InputWeights))
	{
      raRes = dataAssoc->inputWeights()->RARes();
      decRes = dataAssoc->inputWeights()->DecRes();
    }

    if (dataAssoc->exists(fileType::InputData))
	{
      raRes = dataAssoc->inputData()->RARes();
      decRes = dataAssoc->inputData()->DecRes();
    }

    double skyRes = (decRes >= raRes) ? decRes : raRes;

    int skySides = sides(skyRes);
    double logSides = log(skySides)/log(2); // log base 2 of skySides

	// if log2(skySides) has a decimal
    if (abs(logSides - (int)logSides) > SIDERES)
	{
      skySides = std::pow(2,(int)logSides);
      skyRes = resolution(skySides);
    }


    nSides = skySides;
    res = skyRes;

	clearScreen();

	setNSides();
	setIndexing();
	setOverpixelization();

	if(confirm())
		pixelizeData();
	else
		pixelizationCancelled();
}

void healpixDialog::setNSides()
{
	int sides = nSides;
	char defOk = 'n';

	do
	{
		clearInput();
		(*output) << "NSides: " << nSides << " Resolution: " << res << "\n";
		(*output) << "Accept. (Y|N)\t";
	} while( 	!((*input) >>  defOk)
			|| 	!( defOk == 'Y' || defOk == 'y'
			||     defOk == 'N' || defOk == 'n'));

	while(defOk == 'n' || defOk == 'N')
	{
		do
		{
			do
			{
				clearInput();
				(*output) << "\033[1A\033[J";
				(*output) << "NSides must be power of 2. Enter desired nsides value.\t";
			} while( !((*input) >> sides) || !power2(sides));

			double r = resolution(sides);
			(*output) << "\033[2A\033[JNSides: " << sides << " Resolution: " << r << "\n";
			(*output) << "Accept. (Y|N)\t";

		}while( 	!((*input) >>  defOk)
				|| 	!( defOk == 'Y' || defOk == 'y'
				||     defOk == 'N' || defOk == 'n'));
	}

	nSides = sides;
	res = resolution(nSides);
}

void healpixDialog::setIndexing()
{
	int index = 0;

	do
	{
		clearInput();
		(*output) << "Choose the index method.\n"
			  << "\t0. Ring\n"
			  << "\t1. Nested\n";
	}while(		!((*input)>>index)
				|| index < 0
				|| index > 1);

	if(index == 0)
		nestedFlag = false;
	else
		nestedFlag = true;
}

void healpixDialog::setOverpixelization()
{
	int overPixelMethod = 0;

	do
	{
		clearInput();
		clearScreen();

		(*output) << "Choose the overpixelization method.\n"
			  << "\t0. None\n"
			  << "\t1. Pixel Mean\n"
			  << "\t2. Pixel Variance\n"
			  << "\t3. Pixel Deviance\n"
			  << "\t4. Mean Normalization\n"
			  << "\t5. Variance Normalization\n"
			  << "\t6. Min Max Scaling\n";

	}while(		!((*input)>>overPixelMethod)
				|| overPixelMethod < 0
				|| overPixelMethod > 6);

	if(overPixelMethod == 1)
		usePixAvg = true;
	else if(overPixelMethod == 2)
		usePixVar = true;
	else if(overPixelMethod == 3)
		usePixDev = true;
	else if(overPixelMethod == 4)
		doAvgNorm = true;
	else if(overPixelMethod == 5)
		doVarNorm = true;
	else if(overPixelMethod == 6)
		doMinMax = true;
}

bool healpixDialog::confirm()
{
	char confirm = 'n';

	clearScreen();

	(*output) << "You have selected to pixelize with an nsides of: " << nSides << " equating to a resolution of: " << res << ".\n";
	(*output) << "You are using: " << (nestedFlag ? " nested" :" ringed") << " indexing and have selected to use ";

	if(usePixAvg)
		(*output) << "pixel average";
	else if(usePixVar)
		(*output) << "pixel variance";
	else if(usePixDev)
		(*output) << "pixel deviance";
	else if(doAvgNorm)
		(*output) << "mean normalization";
	else if(doVarNorm)
		(*output) << "variance normalization";
	else if(doMinMax)
		(*output) << "min max scaling";
	else
		(*output) << "no";

	(*output) << " overpixelization method.\n";

	do
	{
		clearInput();
		(*output) << "Confirm (Y|N).\t";
	} while( 	!((*input) >>  confirm)
			|| 	!( confirm == 'Y' || confirm == 'y'
			||     confirm == 'N' || confirm == 'n'));

	clearScreen();

	if(confirm == 'Y' || confirm == 'y')
		return true;
	else
		return false;
}

bool healpixDialog::power2(int s)
{
	double log2S = log(s)/log(2); // log base 2 of s

	// if log2(s) has a decimal
    if (abs(log2S - (int)log2S) > SIDERES)
		return false;
    else
		return true;
}

void healpixDialog::clearInput()
{
	input->clear();
	input->ignore(std::numeric_limits<std::streamsize>::max(), '\n');
}

void healpixDialog::clearScreen()
{
	(*output) << "\033[H\033[J";
}

void healpixDialog::configure()
{
}

void healpixDialog::reset()
{
  usePixAvg = false;
  usePixDev = false;
  usePixVar = false;
  doAvgNorm = false;
  doVarNorm = false;
  doMinMax  = false;

  nestedFlag = true;
  dirty = false;
  isConfigured = false;
}

void healpixDialog::validate()
{
}

void healpixDialog::syncSides()
{
	/*
  QString title, message;

  int userSides = ui->sideEdit->text().toInt();
  double logSides = log(userSides)/log(2);
  if (abs(logSides - (int)logSides) > SIDERES) {
    int modSides = std::pow(2,(int)logSides);
    title = QString(tr("Invalid number of sides entered"));
    message = QString(tr("Number of sides must be a multiple of two\nWould you like to use %1 instead?")).arg(modSides);
    int result = QMessageBox::question(this,title,message,QMessageBox::Yes | QMessageBox::No,QMessageBox::Yes);
    if (result == QMessageBox::Yes)
      userSides = modSides;
    else {
      message = QString(tr("Please enter a valid number of sides"));
      QMessageBox::information(this,title,message);
      return;
    }
  }
  nSides = userSides;
  res = resolution(nSides);
  ui->resEdit->clear();
  ui->resEdit->insert(QString::number(res));
  repaint();
  */
}

void healpixDialog::finalize()
{
}

void healpixDialog::help()
{
}

void healpixDialog::cancel()
{
}
