/***************************************************************************
 *   mapperdlg.cpp                                                         *
 *   Copyright (C) 2014 by Daniel Suson                                    *
 *   suson@calumet.purdue.edu                                              *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU General Public License     *
 *   along with this program; if not, write to the                         *
 *   Free Software Foundation, Inc.,                                       *
 *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
 *                                                                         *
 *   In addition, as a special exception, the copyright holders give       *
 *   permission to link the code of this program with any edition of       *
 *   the Qt library by Trolltech AS, Norway (or with modified versions     *
 *   of Qt that use the same license as Qt), and distribute linked         *
 *   combinations including the two.  You must obey the GNU General        *
 *   Public License in all respects for all of the code used other than    *
 *   Qt.  If you modify this file, you may extend this exception to        *
 *   your version of the file, but you are not obligated to do so.  If     *
 *   you do not wish to do so, delete this exception statement from        *
 *   your version.                                                         *
 ***************************************************************************
 * Description:                                                            *
 *                                                                         *
 * This class defines the mapper dialog structure associated with          *
 * the Qt4 user interface.                                                 *
 * ----------------------- Change Log ------------------------------------ *
 * Date    Name         Description                                        *
 *                                                                         *
 ***************************************************************************
 * This software evolved from work that was done by Eric Hivon at the      *
 * California Institute of Technology on the MASTER algorithm (Hivon, E.,  *
 * et al., ApJ, vol 567, p 2).  It adapts or interfaces with these         *
 * packages:                                                               *
 *                                                                         *
 * HealPix         (http://www.eso.org/science/healpix/)                   *
 * FTOOLS & FITSIO (http://heasarc.gsfc.nasa.gov/docs/corp/software.html)  *
 *                                                                         *
 * Any publications or presentations that use results generated by this    *
 * program must reference the fact that it was developed by Daniel Suson   *
 ***************************************************************************/
#include "mapperdlg.h"
#include "../../libgraphics/mapper.h"

#include <sys/ioctl.h>
#include <unistd.h>

mapperDialog::mapperDialog(association *assoc, std::istream* i, std::ostream* o, std::function<void()> s, std::function<void()> c)
				: mapperDialogParent(assoc)
{
	input = i;
	output = o;
	successFunc = s;
	cancelFunc = c;
}

mapperDialog::~mapperDialog()
{
}

void mapperDialog::execute()
{
	setDims();
	setProjection();
	setColorScale();
	setCoordSystem();

	if(confirm())
	{
		if(dataAssoc->exists(dataEngines::Mapping))
			dataAssoc->reset(ALLTYPES::Mapping);

		dataAssoc->addEngine(dataEngines::Mapping, projection);

		dataAssoc->mappingEngine()->layout(projection);

		dataAssoc->mappingEngine()->width(xSize);
		dataAssoc->mappingEngine()->height(ySize);
		dataAssoc->mappingEngine()->orientation(longConvention);
		dataAssoc->mappingEngine()->colorScheme(hue);

		dataAssoc->mappingEngine()->raOffset(raOffset);
		dataAssoc->mappingEngine()->decOffset(decOffset);

		mapperReady();
	}
	else
		mapperCancelled();
}

void mapperDialog::setDims()
{
	struct winsize w;

    // Query standard output for window dimensions
    if (ioctl(STDOUT_FILENO, TIOCGWINSZ, &w) == 0)
	{
		xSize = w.ws_col;
		ySize = w.ws_row;
	}
    else
	{
		(*output) << "ERROR, unable to get default screen size.\n";
		mapperCancelled();
	}

	char defOk = 'n';
	do
	{
		clearInput();

		(*output) << "Configuring Mapper.  Default size is Height: " << ySize << " Width: " << xSize << "\n";
		(*output) << "Accept. (Y|N)\t";
	} while( 	!((*input) >>  defOk)
			|| 	!( defOk == 'Y' || defOk == 'y'
			||     defOk == 'N' || defOk == 'n'));

	int x = xSize;
	int y = ySize;

	if(defOk == 'n' || defOk == 'N')
	{
		do
		{
			clearInput();
			(*output) << "Enter the new Height: \t";
		}while(!((*input) >> y)
			   || y < 0);

		do
		{
			clearInput();
			(*output) << "Enter the new Width: \t";
		}while(!((*input) >> x)
				|| x < 0);
	}

	xSize = x;
	ySize = y;
}

void mapperDialog::setProjection()
{
	int proj = 0;
	do
	{
		clearInput();

		(*output) << "Enter the projection method.\n"
				  << "\t1. Mollweide\n"
				  << "\t2. Aitoff\n"
				  << "\t3. Gnomonic\n";
	} while( !((*input) >> proj)
		     || proj < 1
			 || proj > 3);

	if(proj == 1)
		projection = Mollweide;
	else if(proj == 2)
		projection = Aitoff;
	else
		projection = Gnomonic;
}

void mapperDialog::setColorScale()
{
	int scale = 0;
	do
	{
		clearInput();

		(*output) << "Enter the color scale style.\n"
				  << "\t1. Linear\n"
				  << "\t2. Log\n"
				  << "\t3. Super Log\n";
	} while( !((*input) >> scale)
		     || scale < 1
			 || scale > 3);

	if(scale == 1)
		hue = Linear;
	else if(scale == 2)
		hue = Log;
	else
		hue = SuperLog;
}

void mapperDialog::setCoordSystem()
{
	int coords = 0;
	do
	{
		clearInput();

		(*output) << "Enter the coordinate system.\n"
				  << "\t1. Astronomical\n"
				  << "\t2. Terrestrial\n";
	} while( !((*input) >> coords)
		     || coords < 1
			 || coords > 2);

	if(coords == 1)
		longConvention = Astronomical;
	else if(coords == 2)
		longConvention = Terrestrial;
}

bool mapperDialog::confirm()
{
	char confirm = 'n';

	(*output) << "You have selected to create the maps to be (height x width): " << ySize << " x " << xSize << "\n";
	(*output) << "Using a projection of: ";

	if(projection == Mollweide)
		(*output) << "Mollweide";
	else if(projection == Aitoff)
		(*output) << "Aitoff";
	else if(projection == Gnomonic)
		(*output) << "Gnomonic";

	(*output) << " and a color scale of: ";
	if(hue == Linear)
		(*output) << "Linear";
	else if(hue == Log)
		(*output) << "Log";
	else if(hue == SuperLog)
		(*output) << "Super Log";

	(*output) << " with a coordinate system of: ";
	if(longConvention == Astronomical)
		(*output) << "Astronomical.\n";
	else if(longConvention == Terrestrial)
		(*output) << "Terrestrial.\n";

	do
	{
		clearInput();
		(*output) << "Confirm (Y|N).\t";
	} while( 	!((*input) >>  confirm)
			|| 	!( confirm == 'Y' || confirm == 'y'
			||     confirm == 'N' || confirm == 'n'));

	if(confirm == 'Y' || confirm == 'y')
		return true;
	else
		return false;
}

void mapperDialog::configure()
{
    execute();
}


void mapperDialog::clearInput()
{
	input->clear();
	input->ignore(std::numeric_limits<std::streamsize>::max(), '\n');
}
