/***************************************************************************
 *   mapselectdlg.cpp                                                      *
 *   Copyright (C) 2014 by Daniel Suson                                    *
 *   suson@calumet.purdue.edu                                              *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU General Public License     *
 *   along with this program; if not, write to the                         *
 *   Free Software Foundation, Inc.,                                       *
 *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
 *                                                                         *
 *   In addition, as a special exception, the copyright holders give       *
 *   permission to link the code of this program with any edition of       *
 *   the Qt library by Trolltech AS, Norway (or with modified versions     *
 *   of Qt that use the same license as Qt), and distribute linked         *
 *   combinations including the two.  You must obey the GNU General        *
 *   Public License in all respects for all of the code used other than    *
 *   Qt.  If you modify this file, you may extend this exception to        *
 *   your version of the file, but you are not obligated to do so.  If     *
 *   you do not wish to do so, delete this exception statement from        *
 *   your version.                                                         *
 ***************************************************************************
 * Description:                                                            *
 *                                                                         *
 * This class defines the map select dialog structure associated with      *
 * the Qt4 user interface.                                                 *
 * ----------------------- Change Log ------------------------------------ *
 * Date    Name         Description                                        *
 *                                                                         *
 ***************************************************************************
 * This software evolved from work that was done by Eric Hivon at the      *
 * California Institute of Technology on the MASTER algorithm (Hivon, E.,  *
 * et al., ApJ, vol 567, p 2).  It adapts or interfaces with these         *
 * packages:                                                               *
 *                                                                         *
 * HealPix         (http://www.eso.org/science/healpix/)                   *
 * FTOOLS & FITSIO (http://heasarc.gsfc.nasa.gov/docs/corp/software.html)  *
 *                                                                         *
 * Any publications or presentations that use results generated by this    *
 * program must reference the fact that it was developed by Daniel Suson   *
 ***************************************************************************/
#include "mapselectdlg.h"
#include "../../libanalyzer/atypes.h"

mapSelectDialog::mapSelectDialog(association *assoc, std::istream* i, std::ostream* o,
								 std::function<void(ASSOCIATEDMAP m)> s, std::function<void()> c): mapSelectDialogParent(assoc)
{
	input = i;
	output = o;
	successFunc = s;
	cancelFunc = c;
}

mapSelectDialog::~mapSelectDialog()
{
}

void mapSelectDialog::execute()
{
	int mapChosen = 0;
	do
	{
		clearInput();
		clearScreen();

		(*output) << "Here are the Existing maps: \n";
		ASSOCIATEDMAP mapType = associatedMap::Null;
		int type = static_cast<int>(mapType);

		while (mapType <  associatedMap::ASSOCIATEDMAP_LIMIT) // run over graphable data types
		{
			if (mapType == associatedMap::Null)
			{
				mapType = static_cast<ASSOCIATEDMAP>(++type);
				continue;
			}

			if(dataMgr->exists(mapType))
				(*output) << "\t" << type << ": " << associatedMapNames[type] << "\n";

			mapType = static_cast<ASSOCIATEDMAP>(++type);
		}

		(*output) << "Enter the number for the map wanted.\t";

	} while ( !((*input) >> mapChosen)
		     || mapChosen <= static_cast<int>(ASSOCIATEDMAP::Null)
			 || mapChosen >= static_cast<int>(ASSOCIATEDMAP::ASSOCIATEDMAP_LIMIT));

	mapSelected(static_cast<ASSOCIATEDMAP>(mapChosen));
}

void mapSelectDialog::clearInput()
{
	input->clear();
	input->ignore(std::numeric_limits<std::streamsize>::max(), '\n');
}

void mapSelectDialog::clearScreen()
{
	(*output) << "\033[H\033[J";
}
