/***************************************************************************
 *   energydlg.cpp                                                         *
 *   Copyright (C) 2014 by Daniel Suson                                    *
 *   suson@calumet.purdue.edu                                              *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU General Public License     *
 *   along with this program; if not, write to the                         *
 *   Free Software Foundation, Inc.,                                       *
 *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
 *                                                                         *
 *   In addition, as a special exception, the copyright holders give       *
 *   permission to link the code of this program with any edition of       *
 *   the Qt library by Trolltech AS, Norway (or with modified versions     *
 *   of Qt that use the same license as Qt), and distribute linked         *
 *   combinations including the two.  You must obey the GNU General        *
 *   Public License in all respects for all of the code used other than    *
 *   Qt.  If you modify this file, you may extend this exception to        *
 *   your version of the file, but you are not obligated to do so.  If     *
 *   you do not wish to do so, delete this exception statement from        *
 *   your version.                                                         *
 ***************************************************************************
 * Description:                                                            *
 *                                                                         *
 * This class defines the energy dialog structure associated with          *
 * the Qt4 user interface.                                                 *
 * ----------------------- Change Log ------------------------------------ *
 * Date    Name         Description                                        *
 *                                                                         *
 ***************************************************************************
 * This software evolved from work that was done by Eric Hivon at the      *
 * California Institute of Technology on the MASTER algorithm (Hivon, E.,  *
 * et al., ApJ, vol 567, p 2).  It adapts or interfaces with these         *
 * packages:                                                               *
 *                                                                         *
 * HealPix         (http://www.eso.org/science/healpix/)                   *
 * FTOOLS & FITSIO (http://heasarc.gsfc.nasa.gov/docs/corp/software.html)  *
 *                                                                         *
 * Any publications or presentations that use results generated by this    *
 * program must reference the fact that it was developed by Daniel Suson   *
 ***************************************************************************/
#include "multipleselectiondlg.h"
#include <../libanalyzer/filemanager.h>

multipleSelectionDialog::multipleSelectionDialog(association* s_assoc, std::istream* i, std::ostream* o,
												std::function<void(int, int)> s, std::function<void()> c)
			: multipleSelectionDialogParent(s_assoc)
{
	input = i;
	output = o;
	successFunc = s;
	cancelFunc = c;
}

multipleSelectionDialog::~multipleSelectionDialog()
{
}

void multipleSelectionDialog::execute()
{
	fileManager* fm = dataAssoc->fileIOEngine();
	int slices = fm->slices();

	(*output) << std::left << "Available energy slices: \n";
	for(int i = 0; i < slices; i += 1)
	{
		string desc1 = "\tSlice " + std::to_string(i) + " energy: " + std::to_string(fm->min_energy(i));
		string desc2 = "\tSlice " + std::to_string(i) + " energy: " + std::to_string(fm->max_energy(i));

		(*output) << std::setw(15) << desc1 << desc2 << "\n";
	}

	int minSlice = 0;
	int maxSlice = 0;
	do
	{
		do
		{
			clearInput();
			(*output) << "Enter the min slice: \t";
		}while(		!((*input) >> minSlice)
					|| minSlice < 0
					|| minSlice > slices-1);


		do
		{
			clearInput();
			(*output) << "Enter the max slice: \t";
		}while(		!((*input) >> maxSlice)
					|| maxSlice < 0
					|| maxSlice > slices-1);

		if(maxSlice < minSlice)
			(*output) << "ERROR, max slice must be >= min slice\n";
	} while(maxSlice < minSlice);

	char confirm = 'n';
	do
	{
		(*output) << "You have selected to read from slice " << minSlice << " energy: "<< fm->min_energy(minSlice)
				  << " to slice " <<  maxSlice << " energy: " << fm->max_energy(maxSlice) << "\n" << "Confirm (Y|N).\t";
	} while( 	!((*input) >>  confirm)
			|| 	!( confirm == 'Y' || confirm == 'y'
			||     confirm == 'N' || confirm == 'n'));

	clearScreen();

	if(confirm == 'Y' || confirm == 'y')
		slicesSelected(minSlice, maxSlice);
	else
		energySelectionCancelled();
}

void multipleSelectionDialog::clearInput()
{
	input->clear();
	input->ignore(std::numeric_limits<std::streamsize>::max(), '\n');
}

void multipleSelectionDialog::clearScreen()
{
	(*output) << "\033[H\033[J";
}

void multipleSelectionDialog::configure()
{
}

void multipleSelectionDialog::reset()
{
}

void multipleSelectionDialog::validate()
{
}

void multipleSelectionDialog::finalize()
{
}

void multipleSelectionDialog::help()
{
}

void multipleSelectionDialog::cancel()
{
}
