/***************************************************************************
 *   shellwindow.h                                                          *
 *   Copyright (C) {} 2014 by Daniel Suson                                    *
 *   suson@calumet.purdue.edu                                              *
 *                                                                         *
 *   This program is free software you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation either version 2 of the License, or     *
 *   (at your option) {} any later version.                                   *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU General Public License     *
 *   along with this program if not, write to the                         *
 *   Free Software Foundation, Inc.,                                       *
 *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
 *                                                                         *
 *   In addition, as a special exception, the copyright holders give       *
 *   permission to link the code of this program with any edition of       *
 *   the Qt library by Trolltech AS, Norway (or with modified versions     *
 *   of Qt that use the same license as Qt) {}, and distribute linked         *
 *   combinations including the two.  You must obey the GNU General        *
 *   Public License in all respects for all of the code used other than    *
 *   Qt.  If you modify this file, you may extend this exception to        *
 *   your version of the file, but you are not obligated to do so.  If     *
 *   you do not wish to do so, delete this exception statement from        *
 *   your version.                                                         *
 ***************************************************************************
 * Description:                                                            *
 *                                                                         *
 * This class defines the main window structure associated with the user   *
 * Qt5 user interface.                                                     *
 * ----------------------- Change Log ------------------------------------ *
 * Date    Name         Description                                        *
 *                                                                         *
 ***************************************************************************
 * This software evolved from work that was done by Eric Hivon at the      *
 * California Institute of Technology on the MASTER algorithm (Hivon, E.,  *
 * et al., ApJ, vol 567, p 2) {}.  It adapts or interfaces with these         *
 * packages:                                                               *
 *                                                                         *
 * HealPix         (http://www.eso.org/science/healpix/) {}                   *
 * FTOOLS & FITSIO (http://heasarc.gsfc.nasa.gov/docs/corp/software.html) {}  *
 *                                                                         *
 * Any publications or presentations that use results generated by this    *
 * program must reference the fact that it was developed by Daniel Suson   *
 ***************************************************************************/

#include "shellwindow.h"
#include "controldatadlg.h"
#include "healpixdlg.h"
#include "rshtdlg.h"
#include "spectrumdlg.h"

#include <limits>
#include <iomanip>

ShellWindow::ShellWindow() : GUIManager()
{
	//prevent synchonization with c and c++ input output buffers
	// note we cannot use c IO now!
	std::ios_base::sync_with_stdio(false);

	input =  &(std::cin);
	output = &(std::cout);

	associationVector = new std::vector<association*>();
	try
	{
		associationVector->push_back(new association(this,  ShellWindow::progressBarWrapper,
															ShellWindow::progressTextWrapper,
															ShellWindow::errorMessageWrapper));

		s_association = (*associationVector)[0];
	}
	catch (const std::overflow_error &e)
	{
		errorMessage("The attempt to create a new data association failed due to overflow error.");
		return;
	}
	catch (const std::runtime_error &e)
	{
		errorMessage("The attempt to create a new data association failed due to runtime error.");
		return;
	}
	catch (const std::exception &e)
	{
		errorMessage("The attempt to create a new data association failed due to exception error.");
		return;
	}
	catch (...)
	{
		errorMessage("The attempt to create a new data association failed.");
		return;
	}

	ctrlDlg = new controlDataDialog(s_association, input, output,
									[this](FILETYPE f, bool b) { this->createControlData(f, b);},
									[=](){(*output) << "Control Data Creation canceled.\n";});

	healpixDlg = new healpixDialog(s_association, input, output,
								   [this]() {this->pixelize();},
								   [=](){(*output) << "Pixelization canceled.\n";});

	rshtDlg = new rshtDialog(s_association, input, output,
							 [this]() {this->transform();},
							 [=]() {(*output) << "Transformation canceled.\n";});

	specDlg = new spectrumDialog(input, output,
								 [this]() {this->analyze();},
								 [=]() {(*output) << "Analyze canceled\n"; });

	/* create dialogs needed to pass signals back and forth */
	/*
	assocDlg = new associationSelectDialog(associationVector);
	assocDlg->setCurrAssoc(s_association);

	ctrlDlg = new controlDataDialog(s_association);
	energyDlg = new energyDialog();
	multSelDlg = new multipleSelectionDialog(s_association);
	pixSelectDlg = new pixelizerDialog(s_association);
	transSelectDlg = new transformerDialog(s_association);
	rshtDlg = new rshtDialog(s_association);
	analSelectDlg = new analyzerDialog(s_association);
	specDlg = new spectrumDialog();

	mapperDlg = new mapperDialog(s_association);
	mapSelectDlg = new mapSelectDialog(s_association);
	grapherDlg = new graphDialog(s_association);
	graphSelectDlg = new graphSelectDialog(s_association);

	selectedDataType = fileType::Null;
	selectedDataStream = genericType::NoGeneric;
	*/

	/* set up Qt signal/slot connections */
	/*
	connect(ui->controlAction, &QAction::triggered, [=](bool open){ctrlDlg->configure(false);});
	connect(ui->openAction, &QAction::triggered, [=](){openFile();});
	connect(ui->saveAction, &QAction::triggered, [=](){saveFile();});

	connect(ui->addAssociationAction, &QAction::triggered, [=](){addAssociation(); });
	connect(ui->selectAssociation, &QAction::triggered, [=](){assocDlg->configure();});

	connect(dynamic_cast<associationSelectDialog*>(assocDlg), &associationSelectDialog::associationSelected, [=](association* newAssoc){setAssociation(newAssoc);});

	//  connect(ui->informationAction, Q_SIGNAL(triggered(bool)), this, Q_SLOT());
	//  connect(ui->printAction, Q_SIGNAL(triggered(bool)), this, Q_SLOT());
	connect(ui->clearAction, &QAction::triggered, [=](){reset();});
	connect(ui->exitAction, &QAction::triggered, [=](){close();});
	connect(ui->pixelizeAction, &QAction::triggered, [=](){selectPixelizer();});
	connect(ui->transformAction, &QAction::triggered, [=](){selectTransformer();});
	//connect(ui->analyzeAction, &QAction::triggered, [=](){analyze();});

	connect(ui->analyzeAction, &QAction::triggered, [=](){selectAnalzyer();});

	//  connect(ui->inverseAction, Q_SIGNAL(triggered(bool)), this, Q_SLOT());
	connect(ui->selectMapsAction, &QAction::triggered, [=](){mapSelectDlg->configure();});
	connect(ui->selectGraphsAction, &QAction::triggered, [=](){graphSelectDlg->configure();});
	//  connect(ui->zoomInAction, Q_SIGNAL(triggered(bool)), this, Q_SLOT());
	//  connect(ui->zoomOutAction, Q_SIGNAL(triggered(bool)), this, Q_SLOT());
	//  connect(ui->zoomNormalAction, Q_SIGNAL(triggered(bool)), this, Q_SLOT());
	//  connect(ui->configureMapper, Q_SIGNAL(triggered()), this, Q_SLOT(setupMapper()));
	//  connect(ui->configurePoxelizer, Q_SIGNAL(triggered(bool)), this, Q_SLOT());
	//  connect*ui->configureTransformer, Q_SIGNAL(triggered(bool)), this, Q_SLOT());
	//  connect(ui->HandbookAction, Q_SIGNAL(triggered(bool)), this, Q_SLOT());
	//  connect(ui->aboutAnalyzerAction, Q_SIGNAL(triggered(bool)), this, Q_SLOT());
	connect(dynamic_cast<controlDataDialog*>(ctrlDlg), &controlDataDialog::buildControlData, [=](FILETYPE value,bool complete){createControlData(value,complete);});


	connect(this, &mainWindow::saveDataSets, [=](){dataSelectDlg->configure();});
	connect(this, &mainWindow::readDataSets, [=](FILETYPE* dataTypes, int* numTypes){dataSelectDlg->configure(dataTypes, numTypes);});

	connect(this,&mainWindow::selectEnergies,[=](double low, double high){energyDlg->configure(low,high);});
	connect(this,&mainWindow::selectSlices,[=](){multSelDlg->configure(); });

	//connect(energyDlg,&energyDialog::energySelected,[=](double low, double high){readData(low,high);});
	connect(mapperDlg, &mapperDialog::mapperReady, [=](){buildMaps();});
	connect(this, &mainWindow::selectMapDisplay, [=](unsigned int selection){mapSelectDlg->configure(selection);});
	connect(mapSelectDlg, &mapSelectDialog::mapSelected, [=](ASSOCIATEDMAP map){displayMap(map);});
	connect(grapherDlg, &graphDialog::grapherReady, [=](){buildGraphs();});
	connect(this, &mainWindow::selectGraphDisplay, [=](unsigned int selection){graphSelectDlg->configure(selection);});
	connect(graphSelectDlg, &graphSelectDialog::graphSelected, [=](associatedSpectrum graph){displayGraph(graph);});
	connect(dynamic_cast<pixelizerDialog*>(pixSelectDlg), &pixelizerDialog::pixelizerSelected, [=](PIXELSCHEME scheme){configurePixelizer(scheme);});
	connect(dynamic_cast<transformerDialog*>(transSelectDlg), &transformerDialog::transformerSelected, [=](TRANSFORMERSCHEME scheme){configureTransformer(scheme);});

	connect(dynamic_cast<analyzerDialog*>(analSelectDlg), &analyzerDialog::analyzerSelected, [=](){configureAnalyzer();});

	connect(dynamic_cast<healpixDialog*>(healpixDlg), &healpixDialog::pixelizeData, [=](){pixelize();});
	connect(dynamic_cast<rshtDialog*>(rshtDlg), &rshtDialog::transformData, [=](){transform();});
	connect(dynamic_cast<spectrumDialog*>(specDlg), &spectrumDialog::spectrumReady, [=](){analyze();});
	//  connect(this, Q_SIGNAL(redrawMap()), ui->mapTab, Q_SLOT(paintEvent(QPaintEvent*)));
	//  connect(ctrlDlg, Q_SIGNAL(controlDataSet()), this, Q_SLOT(checkMapper()));
	//  connect(mapperDlg, Q_SIGNAL(mapperSet(MAPTYPE,long,long,ORIENTATION)), this, Q_SLOT(createMaps(MAPTYPE,long,long,ORIENTATION)));
	//  connect(this, Q_SIGNAL(imageConfigured(association*,FILETYPE*)), mapSelectDlg, configure(association*,FILETYPE*));
	//  connect(this, Q_SIGNAL(mapSelected(QWidget*)), this, drawImage(QWidget*));

	// set initial directory to user's home directory
	directory = QDir::home();
	*/
}

ShellWindow::~ShellWindow()
{

}

void ShellWindow::progressBarWrapper(void* uiObj, int value)
{
	ShellWindow* here = (ShellWindow*)uiObj;
	here->updateProgressBar(value);
}

void ShellWindow::progressTextWrapper(void* uiObj, const char* updateName)
{
	ShellWindow* here = (ShellWindow*)uiObj;
	here->updateProgressText(updateName);
}

void ShellWindow::errorMessageWrapper(void* uiObj, const char* errMess)
{
	ShellWindow* here = (ShellWindow*)uiObj;
	here->errorMessage(errMess);
}

void ShellWindow::updateProgressBar(int value)
{
	const int barWidth = 50;

	(*output) << "\r\033[?25l" << "[";

	int pos = value * barWidth / 100;
    for (int i = 0; i < barWidth; i += 1)
	{
        if (i < pos)
			(*output) << "\033[32m=";
        else if (i == pos)
			(*output) << "\033[0m>";
        else
			(*output) << " ";
    }

    (*output) << "\033[0m" << "] " << value << "%";
    output->flush();

	if(value == 100)
		(*output) << "\033[?25h\n";
}

void ShellWindow::updateProgressText(const char* updateName)
{
	(*output) << updateName << "\n";
}

void ShellWindow::errorMessage(const char* errMess)
{
	(*output) << "\033[31m" << errMess << "\033[0m" << "\n";
}

void ShellWindow::displayMessage(const char* mess)
{
	(*output) << "\033[36m" << mess << "\033[0m" << "\n";
}

bool ShellWindow::addDataMessage(const char* errMess)
{
	char add = 'n';
	do
	{
		clearInput();
		(*output) << "\033[33m" << errMess << "(Y|N)" << "\033[0m";
	} while(	!((*input)>>add)
				|| !(   add == 'Y' || add == 'y'
				|| 		add == 'N' || add == 'n'));

	return add == 'y' || add == 'Y' ? true : false;
}

bool ShellWindow::replaceDataChain(const char* mess)
{
	char add = 'n';
	do
	{
		clearInput();
		(*output) << "\033[33m" << mess << "(Y|N)" << "\033[0m";
	} while(	!((*input)>>add)
				|| !(   add == 'Y' || add == 'y'
				|| 		add == 'N' || add == 'n'));

	return add == 'y' || add == 'Y' ? true : false;
}

void ShellWindow::printAssocStatus()
{
	(*output) << std::left;

	for(fileType ft = FILETYPE::InputData; ft != FILETYPE::FILETYPE_LIMIT; ft = static_cast<FILETYPE>(static_cast<int>(ft)+1))
	{
		if(s_association->exists(ft))
		{
			(*output) << "\033[32m";
			(*output) << std::setw(70) << dataTypeNames[static_cast<int>(ft)] << "\t\tdoes    exist.";
			(*output) << "\033[0m\n";
		}
		else
		{
			(*output) << "\033[31m";
			(*output) << std::setw(70) << dataTypeNames[static_cast<int>(ft)] << "\t\tdoesn't exist.";
			(*output) << "\033[0m\n";
		}
	}
}

void ShellWindow::execute()
{
	printMenu();

	for(int choice = getChoice(); choice != 0; choice = getChoice())
	{
		if(choice == 1)
			static_cast<controlDataDialog*>(ctrlDlg)->execute();
		else if(choice == 2)
			(*output) << "Open File\n";
		else if(choice == 3)
			(*output) << "Save File\n";
		else if(choice == 4)
			static_cast<healpixDialog*>(healpixDlg)->execute();
		else if(choice == 5)
			static_cast<rshtDialog*>(rshtDlg)->execute();
		else if(choice == 6)
			static_cast<spectrumDialog*>(specDlg)->execute();
		else if(choice == 7)
			printAssocStatus();
		else
		{
			clearInput();
			printInvalidChoice();
		}

		printMenu();
	}
}

void ShellWindow::printMenu()
{
	(*output) << "MENU CHOICES: \n";
	(*output) << "\t0. Exit\n"
			  << "\t1. Create Control Data\n"
			  << "\t2. Open File\n"
			  << "\t3. Save File\n"
			  << "\t4. Pixelize\n"
			  << "\t5. Transform\n"
			  << "\t6. Analyze\n"
			  << "\t7. View Progress\n";
}

int ShellWindow::getChoice()
{
	int choice = 0;

	if((*input) >> choice)
		return choice;

	do
	{
		clearInput();
		printInvalidChoice();
	}
	while(! ((*input) >> choice));

	return choice;
}

void ShellWindow::clearInput()
{
	input->clear();
	input->ignore(std::numeric_limits<std::streamsize>::max(), '\n');
}

void ShellWindow::printInvalidChoice()
{
	(*output) << "Invalid choice please choose again.\n";
	printMenu();
}

void ShellWindow::addAssociation()
{}

void ShellWindow::setAssociation(association* newAssoc)
{}

void ShellWindow::selectFileName(bool read)
{}

void ShellWindow::emitReadDataSets(FILETYPE* dataTypes, int* numTypes)
{}

void ShellWindow::emitSelectSlices()
{}

void ShellWindow::emitSelectEnergies()
{}

void ShellWindow::emitSaveDataSets()
{}

bool ShellWindow::handleMissingTransformer()
{
	return true;
}

void ShellWindow::selectPixelizer()
{
	int count = 0, i = 1;
	PIXELSCHEME pixCount = static_cast<PIXELSCHEME>(i);

	while(true)
	{
		if (pixCount == PIXELIZER_LIMIT)
			break;
		count++;
		pixCount = static_cast <PIXELSCHEME>(++i);
	}

	if (count > 1)
	{
		if (!pixSelectDlg->configured())
			pixSelectDlg->configure();
	}
	else
	{
		static_cast<healpixDialog*>(healpixDlg)->execute();
	}
}

void ShellWindow::configurePixelizer(PIXELSCHEME scheme)
{}

void ShellWindow::selectTransformer()
{
	int count = 0, i = 1;
	TRANSFORMERSCHEME transCount = static_cast<TRANSFORMERSCHEME>(i);

	while (true)
	{
		if (transCount == TRANSFORMER_LIMIT)
			break;
		count++;
		transCount = static_cast <TRANSFORMERSCHEME>(++i);
	}

	if (count > 1)
	{
		if (!transSelectDlg->configured())
			transSelectDlg->configure();
	}
	else
	{
		if (!rshtDlg->configured())
			rshtDlg->configure();
	}
}

void ShellWindow::configureTransformer(TRANSFORMERSCHEME scheme)
{}

void ShellWindow::selectAnalzyer()
{}

void ShellWindow::configureAnalyzer()
{}

void ShellWindow::configureDisplay(FILETYPE dataType)
{
	(*output) << dataTypeNames[static_cast<int>(dataType)] << " created successfully\n";
}

void ShellWindow::displayGraph(ASSOCIATEDSPECTRUM graph)
{}

void ShellWindow::displayMap(ASSOCIATEDMAP map)
{}
