/***************************************************************************
 *   shellwindow.h                                                          *
 *   Copyright (C) {} 2014 by Daniel Suson                                    *
 *   suson@calumet.purdue.edu                                              *
 *                                                                         *
 *   This program is free software you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation either version 2 of the License, or     *
 *   (at your option) {} any later version.                                   *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU General Public License     *
 *   along with this program if not, write to the                         *
 *   Free Software Foundation, Inc.,                                       *
 *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
 *                                                                         *
 *   In addition, as a special exception, the copyright holders give       *
 *   permission to link the code of this program with any edition of       *
 *   the Qt library by Trolltech AS, Norway (or with modified versions     *
 *   of Qt that use the same license as Qt) {}, and distribute linked         *
 *   combinations including the two.  You must obey the GNU General        *
 *   Public License in all respects for all of the code used other than    *
 *   Qt.  If you modify this file, you may extend this exception to        *
 *   your version of the file, but you are not obligated to do so.  If     *
 *   you do not wish to do so, delete this exception statement from        *
 *   your version.                                                         *
 ***************************************************************************
 * Description:                                                            *
 *                                                                         *
 * This class defines the main window structure associated with the user   *
 * Qt5 user interface.                                                     *
 * ----------------------- Change Log ------------------------------------ *
 * Date    Name         Description                                        *
 *                                                                         *
 ***************************************************************************
 * This software evolved from work that was done by Eric Hivon at the      *
 * California Institute of Technology on the MASTER algorithm (Hivon, E.,  *
 * et al., ApJ, vol 567, p 2) {}.  It adapts or interfaces with these         *
 * packages:                                                               *
 *                                                                         *
 * HealPix         (http://www.eso.org/science/healpix/) {}                   *
 * FTOOLS & FITSIO (http://heasarc.gsfc.nasa.gov/docs/corp/software.html) {}  *
 *                                                                         *
 * Any publications or presentations that use results generated by this    *
 * program must reference the fact that it was developed by Daniel Suson   *
 ***************************************************************************/
#include "../libgraphics/mapper.h"
#include "../libgraphics/grapher.h"

#include "shellwindow.h"
#include "controldatadlg.h"
#include "pixelizerdlg.h"
#include "healpixdlg.h"
#include "transformerdlg.h"
#include "rshtdlg.h"
#include "analyzerdlg.h"
#include "spectrumdlg.h"

#include "associationselectdlg.h"

#include "dataselectdlg.h"
#include "multipleselectiondlg.h"

#include "mapperdlg.h"
#include "mapselectdlg.h"
#include "graphdlg.h"
#include "graphselectdlg.h"

#include <limits>
#include <iomanip>
#include <filesystem>
#include <readline/readline.h>
#include <readline/history.h>


ShellWindow::ShellWindow() : GUIManager(5)
{
	//prevent synchonization with c and c++ input output buffers
	// note we cannot use c IO now!
	//std::ios_base::sync_with_stdio(false);

	input =  &(std::cin);
	output = &(std::cout);

	ctrlDlg = new controlDataDialog(s_association, input, output,
									[this](FILETYPE f, bool b) { this->createControlData(f, b);},
									[=](){(*output) << "Control Data Creation canceled.\n";});

	pixSelectDlg = new pixelizerDialog(s_association, input, output,
									   [this](PIXELSCHEME p){configurePixelizer(p);},
									   [=](){(*output) << "Pixelizer selection canceled.\n";});

	healpixDlg = new healpixDialog(s_association, input, output,
								   [this]() {this->pixelize();},
								   [=](){(*output) << "Pixelization canceled.\n";});

	transSelectDlg = new transformerDialog(s_association, input, output,
										   [this](TRANSFORMERSCHEME t){configureTransformer(t);},
										   [=](){(*output) << "Transformer selection canceled.\n";});

	rshtDlg = new rshtDialog(s_association, input, output,
							 [this]() {this->transform();},
							 [=]() {(*output) << "Transformation canceled.\n";});

	analSelectDlg = new analyzerDialog(s_association, input, output,
									   [this](){configureAnalyzer();},
									   [=](){(*output) << "Analyzer selection canceled.\n";});

	specDlg = new spectrumDialog(input, output,
								 [this]() {this->analyze();},
								 [=]() {(*output) << "Analyze canceled\n"; });

	multSelDlg = new multipleSelectionDialog(s_association, input, output,
											 [this](int min, int max) {s_association->fileIOEngine()->minSlice(min);
																	   s_association->fileIOEngine()->maxSlice(max);},
											 [=](){(*output) << "Multiple Selection Canceled\n";});

	assocDlg = new associationSelectDialog(associationVector, input, output,
										   [this](association* a) {setAssociation(a);},
										   [=](){(*output) << "Canceled\n";});

	mapperDlg = new mapperDialog(s_association, input, output,
								 [this](){this->buildMaps();},
								 [=]() {(*output) << "Mapper Canceled\n";});

	mapSelectDlg = new mapSelectDialog(s_association, input, output,
									   [this](ASSOCIATEDMAP m){this->displayMap(m);},
									   [=]{(*output) << "Map Select Canceled.\n";});

	grapherDlg = new graphDialog(s_association, input, output,
							   [this](){this->buildGraphs();},
							   [=](){(*output) << "Grapher Cancelled\n";});

	graphSelectDlg = new graphSelectDialog(s_association, input, output,
										   [this](ASSOCIATEDSPECTRUM s){this->displayGraph(s);},
										   [=](){(*output) << "Graph select canceled\n";});
}

ShellWindow::~ShellWindow()
{

}

void ShellWindow::updateProgressBar(int value)
{
	const int barWidth = 50;

	(*output) << "\r\033[?25l" << "[";

	int pos = value * barWidth / 100;
    for (int i = 0; i < barWidth; i += 1)
	{
        if (i < pos)
			(*output) << "\033[32m=";
        else if (i == pos)
			(*output) << "\033[0m>";
        else
			(*output) << " ";
    }

    (*output) << "\033[0m" << "] " << value << "%";
    output->flush();

	if(value == 100)
		(*output) << "\033[?25h\n";
}

void ShellWindow::updateProgressText(const char* updateName)
{
	(*output) << updateName << "\n";
}

void ShellWindow::errorMessage(const char* errMess)
{
	(*output) << "\033[31m" << errMess << "\033[0m" << "\n";
}

void ShellWindow::displayMessage(const char* mess)
{
	(*output) << "\033[36m" << mess << "\033[0m" << "\n";
}

bool ShellWindow::addDataMessage(const char* errMess)
{
	char add = 'n';
	do
	{
		clearInput();
		(*output) << "\033[33m" << errMess << "\033[0m\n";
		(*output) << "Create: c, Open: o, No: n" << "\t";
	} while(	!((*input)>>add)
				|| !(   add == 'C' || add == 'c'
					||	add == 'O' || add == 'o'
					|| 	add == 'N' || add == 'n'));

	if(add == 'c' || add == 'C')
		static_cast<controlDataDialog*>(ctrlDlg)->execute();
	else if(add == 'o' || add == 'O')
		(*output) << "OPEN FILE\n";
	else
		return false;

	return true;
}

bool ShellWindow::replaceDataChain(const char* mess)
{
	char add = 'n';
	do
	{
		clearInput();
		(*output) << "\033[33m" << mess << "(Y|N)" << "\033[0m";
	} while(	!((*input)>>add)
				|| !(   add == 'Y' || add == 'y'
				|| 		add == 'N' || add == 'n'));

	return add == 'y' || add == 'Y' ? true : false;
}

void ShellWindow::printAssocStatus()
{
	clearScreen();

	(*output) << std::left;

	for(fileType ft = FILETYPE::InputData; ft != FILETYPE::FILETYPE_LIMIT; ft = static_cast<FILETYPE>(static_cast<int>(ft)+1))
	{
		if(s_association->exists(ft))
		{
			(*output) << "\033[32m";
			(*output) << std::setw(70) << dataTypeNames[static_cast<int>(ft)] << "\t\tdoes    exist.";
			(*output) << "\033[0m\n";
		}
		else
		{
			if(ft != FILETYPE::MAP_LIMIT && ft != FILETYPE::GRAPH_LIMIT && ft != FILETYPE::TRANSFORM_LIMIT)
			{
				(*output) << "\033[31m";
				(*output) << std::setw(70) << dataTypeNames[static_cast<int>(ft)] << "\t\tdoesn't exist.";
				(*output) << "\033[0m\n";
			}
		}
	}

	(*output) << "Press any key to continue to main menu.\n";
	clearInput();
	input->get();
}

void ShellWindow::execute()
{
	printMenu();

	for(int choice = getChoice(); choice != 0; choice = getChoice())
	{
		if(choice == 1)
			static_cast<controlDataDialog*>(ctrlDlg)->execute();
		else if(choice == 2)
			openFile();
		else if(choice == 3)
			saveFile();
		else if(choice == 4)
			selectPixelizer(); //static_cast<healpixDialog*>(healpixDlg)->execute();
		else if(choice == 5)
			selectTransformer(); //static_cast<rshtDialog*>(rshtDlg)->execute();
		else if(choice == 6)
			selectAnalzyer(); //static_cast<spectrumDialog*>(specDlg)->execute();
		else if(choice == 7)
			(*output) << "Option currently unavailable.\n";//static_cast<mapSelectDialog*>(mapSelectDlg)->execute();
		else if(choice == 8)
			(*output) << "Option currently unavailable.\n";//static_cast<graphSelectDialog*>(graphSelectDlg)->execute();
		else if(choice == 9)
			printAssocStatus();
		else if(choice == 10)
			addAssociation();
		else if(choice == 11)
			static_cast<associationSelectDialog*>(assocDlg)->execute();
		else
		{
			clearInput();
			printInvalidChoice();
		}

		clearScreen();
		printMenu();
	}
}

void ShellWindow::printMenu()
{
	(*output) << "MENU CHOICES: \n";
	(*output) << "\t0.  Exit\n"
			  << "\t1.  Create Control Data\n"
			  << "\t2.  Open File\n"
			  << "\t3.  Save File\n"
			  << "\t4.  Pixelize\n"
			  << "\t5.  Transform\n"
			  << "\t6.  Analyze\n"
			  << "\t7.  Display Map\n"
			  << "\t8.  Display Graph\n"
			  << "\t9.  View Progress\n"
			  << "\t10. Add Association\n"
			  << "\t11. Change Association.\n";
}

int ShellWindow::getChoice()
{
	int choice = 0;

	if((*input) >> choice)
		return choice;

	do
	{
		clearInput();
		printInvalidChoice();
	}
	while(! ((*input) >> choice));

	return choice;
}

void ShellWindow::printInvalidChoice()
{
	(*output) << "Invalid choice please choose again.\n";
	printMenu();
}

void ShellWindow::clearInput()
{
	input->clear();
	input->ignore(std::numeric_limits<std::streamsize>::max(), '\n');
}

void ShellWindow::clearScreen()
{
	(*output) << "\033[H\033[J";
}

bool ShellWindow::selectFileName(bool read)
{
	rl_bind_key('\t', rl_complete);
	rl_completion_suppress_append = 0;

	if(read)
	{
		std::filesystem::path inputFile = "";
		do
		{
			char* inFl = readline("Enter the filename to read data from.\n");
			add_history(inFl);

			if(!inFl || inFl[0] == '\0')
			{
				errorMessage("Quitting reading file.\n");
				return false;
			}

			// we have to check for whitespace because auto complete adds a trailing space!
			string file = string(inFl);
			size_t trailWS = file.find_last_not_of(" \t\n\r\f\v");

			if (trailWS != std::string::npos)
				file.erase(trailWS + 1);

			inputFile = file;
			if(!std::filesystem::exists(inputFile))
			{
				errorMessage(string("File: " + inputFile.string() + " does not exist.\n").c_str());
			}
		}while(! std::filesystem::exists(inputFile));


		// parse the file type ie csv fits hdf5
		std::string ext = inputFile.extension();

		if(ext == ".fit" || ext == ".fits" || ext == ".fts")
			dataFormat = Fits;
		else if(ext == ".csv" || ext == ".txt")
			dataFormat = CSV;
		else if(ext == ".hdf5" || ext == ".h5")
			dataFormat = HDF5;
		else
		{
			errorMessage(string("Unknown file format: " + ext + " quiting open file operation.\n").c_str());
			return false;
		}

		fileName = inputFile.string();

		// get the observatory;
		std::string obsNames = "";
		int obsInd = 1;// 0 is unknown we dont' want that to be an option
		for(obsInd = 1; obsInd < static_cast<int>(OBSERVATORY::OBSERVATORY_LIMIT); obsInd += 1)
			obsNames += "\t" + std::to_string(obsInd) + ". " + observatoryNames[obsInd] + "\n";

		do
		{
			clearInput();

			(*output) << "Enter the observatory the data is from.\n";
			(*output) << obsNames;
		}while(	!((*input)>>obsInd)
				|| obsInd < 1
				|| obsInd >= static_cast<int>(OBSERVATORY_LIMIT));

		dataSource = static_cast<OBSERVATORY>(obsInd);
	}
	else
	{
		std::filesystem::path outFile = "";
		//do
		//{
			char* outFl = readline("Enter the filename to write data to.\n");
			add_history(outFl);

			if(!outFl || outFl[0] == '\0')
			{
				errorMessage("Quitting writing file.\n");
				return false;
			}

			// we have to check for whitespace because auto complete adds a trailing space!
			string file = string(outFl);
			size_t trailWS = file.find_last_not_of(" \t\n\r\f\v");

			if (trailWS != std::string::npos)
				file.erase(trailWS + 1);

			outFile = file;
			if(std::filesystem::exists(outFile))
				displayMessage(string("File: " + outFile.string() + " already exists.\n").c_str());

		//}while(std::filesystem::exists(outFile));


		// parse the file type ie csv fits hdf5
		std::string ext = outFile.extension();

		if(ext == ".fit" || ext == ".fits" || ext == ".fts")
			dataFormat = Fits;
		else if(ext == ".csv" || ext == ".txt")
			dataFormat = CSV;
		else if(ext == ".hdf5" || ext == ".h5")
			dataFormat = HDF5;
		else
		{
			errorMessage(string("Unknown file format: " + ext + " quiting open file operation.\n").c_str());
			return false;
		}

		fileName = outFile.string();
	}

	return true;
}

void ShellWindow::emitReadDataSets(FILETYPE* dataTypes, int* numTypes)
{
	dataSelectDlg = new dataSelectDialog(s_association, input, output,
										 [this](int size, FILETYPE types[]){this->readData(size, types);},
										 [=](){(*output) << "Data Selection Canceled\n";},
										 RWMode::Read);

	static_cast<dataSelectDialog*>(dataSelectDlg)->execute(dataTypes, numTypes);
}

void ShellWindow::emitSelectSlices()
{
	static_cast<multipleSelectionDialog*>(multSelDlg)->execute();
}

void ShellWindow::emitSelectEnergies()
{}

void ShellWindow::emitSaveDataSets()
{
	dataSelectDlg = new dataSelectDialog(s_association, input, output,
										 [this](int size, FILETYPE types[]){this->writeData(size, types);},
										 [=](){(*output) << "Data Selection Canceled\n";},
										 RWMode::Read);

	static_cast<dataSelectDialog*>(dataSelectDlg)->execute();
}

bool ShellWindow::handleMissingTransformer()
{
	return true;
}

void ShellWindow::emitSelectMapDisplay(int displayData)
{
	static_cast<mapSelectDialog*>(mapSelectDlg)->execute();
}

void ShellWindow::configureDisplay(FILETYPE ft)
{
	// leave empty to avoid from having to display maps which are ugly in this version and very error prone.
}

void ShellWindow::paintMap(unsigned char* map)
{
	activeMap = map;
	int rows = s_association->mappingEngine()->height();
	int cols = s_association->mappingEngine()->width();

	FILETYPE mapType = s_association->mappingEngine()->display();
	std::string mapName = dataTypeNames[static_cast<int>(mapType)];
	std::string spacing((cols-mapName.size())/2, ' ');

	std::cout << spacing << mapName << spacing << "\n";
	for(int rInd = 0; rInd < rows; rInd += 1)
	{
		for(int cInd = 0; cInd < cols; cInd += 1)
		{
			int pixelIndex = ((rInd * cols) + cInd) * 3;

			unsigned char r = map[pixelIndex + 0];
			unsigned char g = map[pixelIndex + 1];
			unsigned char b = map[pixelIndex + 2];

			// \033[38;2; says we are using 24 bit true color, r g b are the r g b values, \u2588 is a box what we will use as a pixel
			(*output) << "\033[38;2;" + std::to_string(r) + ";" + std::to_string(g) + ";" + std::to_string(b) + "m\u2588";
		}
		(*output) << "\033[0m\n";
	}

	//(*output) << "Press any key to continue to main menu.\n";
	clearInput();
	input->get();
}

void ShellWindow::clearMaps()
{
	clearScreen();
}

void ShellWindow::emitSelectGraphDisplay(int displayData)
{
	static_cast<graphSelectDialog*>(graphSelectDlg)->execute();
}

void ShellWindow::paintGraph(unsigned char* graph)
{
	activeGraph = graph;
	int rows = s_association->mappingEngine()->height();
	int cols = s_association->mappingEngine()->width();

	FILETYPE graphType = s_association->graphingEngine()->dataType();
	std::string graphName = dataTypeNames[static_cast<int>(graphType)];
	std::string spacing((cols-graphName.size())/2, ' ');

	std::cout << spacing << graphName << spacing << "\n";
	for(int rInd = 0; rInd < rows; rInd += 1)
	{
		for(int cInd = 0; cInd < cols; cInd += 1)
		{
			int pixelIndex = ((rInd * cols) + cInd) * 3;

			unsigned char r = graph[pixelIndex + 0];
			unsigned char g = graph[pixelIndex + 1];
			unsigned char b = graph[pixelIndex + 2];

			// \033[38;2; says we are using 24 bit true color, r g b are the r g b values, \u2588 is a box what we will use as a pixel
			(*output) << "\033[38;2;" + std::to_string(r) + ";" + std::to_string(g) + ";" + std::to_string(b) + "m\u2588";
		}
		(*output) << "\033[0m\n";
	}

	//(*output) << "Press any key to continue to main menu.\n";
	clearInput();
	input->get();
}

void ShellWindow::clearGraphs()
{
	clearScreen();
}

