/***************************************************************************
 *   spectrumdlg.cpp                                                       *
 *   Copyright (C) 2014 by Daniel Suson                                    *
 *   suson@calumet.purdue.edu                                              *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU General Public License     *
 *   along with this program; if not, write to the                         *
 *   Free Software Foundation, Inc.,                                       *
 *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
 *                                                                         *
 *   In addition, as a special exception, the copyright holders give       *
 *   permission to link the code of this program with any edition of       *
 *   the Qt library by Trolltech AS, Norway (or with modified versions     *
 *   of Qt that use the same license as Qt), and distribute linked         *
 *   combinations including the two.  You must obey the GNU General        *
 *   Public License in all respects for all of the code used other than    *
 *   Qt.  If you modify this file, you may extend this exception to        *
 *   your version of the file, but you are not obligated to do so.  If     *
 *   you do not wish to do so, delete this exception statement from        *
 *   your version.                                                         *
 ***************************************************************************
 * Description:                                                            *
 *                                                                         *
 * This class defines the spectrum dialog structure associated with        *
 * the Qt4 user interface.                                                 *
 * ----------------------- Change Log ------------------------------------ *
 * Date    Name         Description                                        *
 *                                                                         *
 ***************************************************************************
 * This software evolved from work that was done by Eric Hivon at the      *
 * California Institute of Technology on the MASTER algorithm (Hivon, E.,  *
 * et al., ApJ, vol 567, p 2).  It adapts or interfaces with these         *
 * packages:                                                               *
 *                                                                         *
 * HealPix         (http://www.eso.org/science/healpix/)                   *
 * FTOOLS & FITSIO (http://heasarc.gsfc.nasa.gov/docs/corp/software.html)  *
 *                                                                         *
 * Any publications or presentations that use results generated by this    *
 * program must reference the fact that it was developed by Daniel Suson   *
 ***************************************************************************/
#include "spectrumdlg.h"

#include <limits>
#include <iomanip>

spectrumDialog::spectrumDialog(std::istream* i, std::ostream* o, std::function<void()> s, std::function<void()> c)
			: spectrumDialogParent()
{
	input = i;
	output = o;
	successFunc = s;
	cancelFunc = c;
}

spectrumDialog::~spectrumDialog()
{
}

void spectrumDialog::execute()
{
	setBinSize();
	setEnsAvg();
	setMaskIndex();

	if(confirm())
		spectrumReady();
	else
		powerSpectrumCancelled();
}

void spectrumDialog::setBinSize()
{
	(*output) << std::left;
	int numL;
	do
	{
		clearInput();
		(*output) << std::setw(60) << "Enter the number of l's per bin.";
	}while(		!((*input) >> numL)
				|| numL < 2);

	binSize = numL;
}

void spectrumDialog::setEnsAvg()
{
	(*output) << std::left;
	int numIter;
	do
	{
		clearInput();
		(*output) << std::setw(60) << "Enter the number of ensemble averages to perform.";
	}while(		!((*input) >> numIter)
				|| numIter < 1);

	ensIter = numIter;
}

void spectrumDialog::setMaskIndex()
{
	(*output) << std::left;
	int index;
	do
	{
		clearInput();
		(*output) << std::setw(60) << "Enter the indexes you wish to mask out.";
	}while(		!((*input) >> index)
				|| index < 0);

	maskInd = index;
}

bool spectrumDialog::confirm()
{
	(*output) << "You have selected to analyze using "
			  << binSize << " l's per bin, perform "
			  << ensIter << " ensemble averages, and mask out the first "
			  << maskInd << " indexes.\n";

	char confirm = 'n';
	do
	{
		clearInput();
		(*output) << "Confirm Y | N.\t";
	}while(		!((*input)>>confirm)
				|| !(   confirm == 'Y' || confirm == 'y'
					 || confirm == 'N' || confirm == 'n'));

	return confirm == 'y' || confirm == 'Y' ? true : false;
}

void spectrumDialog::clearInput()
{
	input->clear();
	input->ignore(std::numeric_limits<std::streamsize>::max(), '\n');
}

void spectrumDialog::configure()
{
}

void spectrumDialog::reset()
{
}

void spectrumDialog::validate()
{
}


void spectrumDialog::finalize()
{
}

void spectrumDialog::help()
{
}

void spectrumDialog::cancel()
{
}
