/***************************************************************************
 *   graphselectdlg.cpp                                                    *
 *   Copyright (C) 2014 by Daniel Suson                                    *
 *   suson@calumet.purdue.edu                                              *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU General Public License     *
 *   along with this program; if not, write to the                         *
 *   Free Software Foundation, Inc.,                                       *
 *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
 *                                                                         *
 *   In addition, as a special exception, the copyright holders give       *
 *   permission to link the code of this program with any edition of       *
 *   the Qt library by Trolltech AS, Norway (or with modified versions     *
 *   of Qt that use the same license as Qt), and distribute linked         *
 *   combinations including the two.  You must obey the GNU General        *
 *   Public License in all respects for all of the code used other than    *
 *   Qt.  If you modify this file, you may extend this exception to        *
 *   your version of the file, but you are not obligated to do so.  If     *
 *   you do not wish to do so, delete this exception statement from        *
 *   your version.                                                         *
 ***************************************************************************
 * Description:                                                            *
 *                                                                         *
 * This class defines the graph select dialog structure associated with    *
 * the Qt4 user interface.                                                 *
 * ----------------------- Change Log ------------------------------------ *
 * Date    Name         Description                                        *
 *                                                                         *
 ***************************************************************************
 * This software evolved from work that was done by Eric Hivon at the      *
 * California Institute of Technology on the MASTER algorithm (Hivon, E.,  *
 * et al., ApJ, vol 567, p 2).  It adapts or interfaces with these         *
 * packages:                                                               *
 *                                                                         *
 * HealPix         (http://www.eso.org/science/healpix/)                   *
 * FTOOLS & FITSIO (http://heasarc.gsfc.nasa.gov/docs/corp/software.html)  *
 *                                                                         *
 * Any publications or presentations that use results generated by this    *
 * program must reference the fact that it was developed by Daniel Suson   *
 ***************************************************************************/
#include "graphselectdlg.h"
#include "ui_graphselectdlg.h"

graphSelectDialog::graphSelectDialog(association* assoc) :
                   ui(new Ui::graphSelectDialog) {
  /* set up the user interface first */
  ui->setupUi(this);
  
  /* initialize internal variables*/
  graphType = associatedSpectrum::Null;
  dirty = false;
  activeGraphs = 0;
  dataAssoc = assoc;
  
  /* enable all graphs */
  ui->dataButton->setEnabled(true);
  ui->weightButton->setEnabled(true);
  ui->noiseButton->setEnabled(true);
  ui->filterButton->setEnabled(true);
  ui->beamButton->setEnabled(true);

  ui->combinedDataButton->setEnabled(true);
  ui->EnsAvgSpectrumButton->setEnabled(true);
  ui->weightedNoiseButton->setEnabled(true);
  ui->EnsAvgNoiseSpectrumButton->setEnabled(true);

  //ui->spectDataButton->setEnabled(true);
  //ui->ensembleButton->setEnabled(true);

  ui->extrapolatedSpectrumButton->setEnabled(true);
  ui->extrapolatedInstrumentSpectrumButton->setEnabled(true);
  ui->binnedSpectrumButton->setEnabled(true);
  ui->binnedExtrapolatedSpectrumButton->setEnabled(true);
  ui->binnedExtrapolatedInstrumentSpectrumButton->setEnabled(true);

  //ui->EnsAvgBinnedSpectrumButton->setEnabled(true);

  /* set up signals and slots */
  connect(ui->buttonBox, &QDialogButtonBox::accepted, this, &graphSelectDialog::finalize);
  connect(ui->buttonBox, &QDialogButtonBox::rejected, this, &graphSelectDialog::cancel);
  connect(ui->buttonBox, &QDialogButtonBox::helpRequested, this, &graphSelectDialog::help);
}

graphSelectDialog::~graphSelectDialog() {
  delete ui;
}

void graphSelectDialog::validate() {
  dirty = false; // assume nothing has changed
  
  ASSOCIATEDSPECTRUM oldGraphType = graphType;
  if (ui->dataButton->isChecked())
    graphType = associatedSpectrum::TransformedDataSpectrum;

  if (ui->weightButton->isChecked())
    graphType = associatedSpectrum::TransformedWeightsSpectrum;

  if (ui->noiseButton->isChecked())
    graphType = associatedSpectrum::TransformedNoiseSpectrum;

  if (ui->filterButton->isChecked())
    graphType = associatedSpectrum::TransformedFilterSpectrum;

  if (ui->beamButton->isChecked())
    graphType = associatedSpectrum::TransformedBeamSpectrum;

  if (ui->combinedDataButton->isChecked())
    graphType = associatedSpectrum::WeightedTransformSpectrum;

  if(ui->EnsAvgSpectrumButton->isChecked())
    graphType = associatedSpectrum::EnsembleAveragedSpectrumSpectrum;

  if (ui->weightedNoiseButton->isChecked())
    graphType = associatedSpectrum::TransformedWeightedNoiseSpectrum;

  if(ui->EnsAvgNoiseSpectrumButton->isChecked())
    graphType = associatedSpectrum::EnsembleAveragedNoiseSpectrum;

  /*
  if (ui->spectDataButton->isChecked())
    graphType = associatedSpectrum::SpectralDataSpectrum;
  if (ui->ensembleButton->isChecked())
    graphType = associatedSpectrum::EnsembleDataSpectrum;
  */

  if(ui->extrapolatedSpectrumButton->isChecked())
    graphType = associatedSpectrum::ExtrapolatedSpectrumSpectrum;

  if(ui->extrapolatedInstrumentSpectrumButton->isChecked())
    graphType = associatedSpectrum::ExtrapolatedInstrumentSpectrumSpectrum;

  if(ui->binnedSpectrumButton->isChecked())
    graphType = associatedSpectrum::BinnedSpectrumSpectrum;

  if(ui->binnedExtrapolatedSpectrumButton->isChecked())
    graphType = associatedSpectrum::BinnedExtrapolatedSpectrumSpectrum;

  if(ui->binnedExtrapolatedInstrumentSpectrumButton->isChecked())
    graphType = associatedSpectrum::BinnedExtrapolatedInstrumentedSpectrumSpectrum;

  //if(ui->EnsAvgBinnedSpectrumButton->isChecked())
  //  graphType = associatedSpectrum::EnsembleAveragedBinnedSpectrumSpectrum;

  if (graphType != oldGraphType)
    dirty = true;
  
  return;
}

void graphSelectDialog::configure(unsigned int availableGraphs) {
  dirty = false;
  activeGraphs = availableGraphs;
  
  ui->dataButton->setEnabled(false);
  ui->weightButton->setEnabled(false);
  ui->noiseButton->setEnabled(false);
  ui->filterButton->setEnabled(false);
  ui->beamButton->setEnabled(false);

  ui->combinedDataButton->setEnabled(false);
  ui->EnsAvgSpectrumButton->setEnabled(false);
  ui->weightedNoiseButton->setEnabled(false);
  ui->EnsAvgNoiseSpectrumButton->setEnabled(false);

  //ui->spectDataButton->setEnabled(true);
  //ui->ensembleButton->setEnabled(true);

  ui->extrapolatedSpectrumButton->setEnabled(false);
  ui->extrapolatedInstrumentSpectrumButton->setEnabled(false);
  ui->binnedSpectrumButton->setEnabled(false);
  ui->binnedExtrapolatedSpectrumButton->setEnabled(false);
  ui->binnedExtrapolatedInstrumentSpectrumButton->setEnabled(false);

  ASSOCIATEDSPECTRUM graphType = associatedSpectrum::ASSOCIATEDSPECTRUM_LIMIT;
  int type = static_cast<int>(graphType);
  
  /*
  while (true)
  { // run over graphable data types
    if(graphType == associatedSpectrum::Null) {
      graphType = static_cast<ASSOCIATEDSPECTRUM>(++type);
      continue;
    }
    
    if (graphType == associatedSpectrum::ASSOCIATEDSPECTRUM_LIMIT)
      break;
    
    bool selected = activeGraphs & (1 << (type-1));
    switch (graphType)
    {
      case associatedSpectrum::TransformedDataSpectrum:
        if (selected && dataAssoc->exists(fileType::TransformedData))
          ui->dataButton->setEnabled(true);
        break;
      case associatedSpectrum::TransformedWeightsSpectrum:
        if (selected && dataAssoc->exists(fileType::TransformedWeights))
          ui->weightButton->setEnabled(true);
        break;
      case associatedSpectrum::TransformedNoiseSpectrum:
        if (selected && dataAssoc->exists(fileType::TransformedNoise))
          ui->noiseButton->setEnabled(true);
        break;
      case associatedSpectrum::TransformedFilterSpectrum:
        if (selected && dataAssoc->exists(fileType::TransformedFilter))
          ui->filterButton->setEnabled(true);
        break;
      case associatedSpectrum::TransformedBeamSpectrum:
        if (selected && dataAssoc->exists(fileType::TransformedBeam))
          ui->beamButton->setEnabled(true);
        break;
      case associatedSpectrum::WeightedTransformSpectrum:
        if (selected && dataAssoc->exists(fileType::WeightedTransform))
          ui->combinedDataButton->setEnabled(true);
        break;
      case associatedSpectrum::EnsembleAveragedSpectrumSpectrum:
        if(selected && dataAssoc->exists(fileType::EnsembleAveragedSpectrum))
          ui->EnsAvgSpectrumButton->setEnabled(true);
        break;
      case associatedSpectrum::TransformedWeightedNoiseSpectrum:
        if(selected && dataAssoc->exists(fileType::TransformedWeightedNoise))
          ui->weightedNoiseButton->setEnabled(true);
        break;
      case associatedSpectrum::EnsembleAveragedNoiseSpectrum:
        if(selected && dataAssoc->exists(fileType::EnsembleAveragedNoise))
          ui->EnsAvgNoiseSpectrumButton->setEnabled(true);
        break;

      //case associatedSpectrum::SpectralDataSpectrum:
      //  if (selected)
      //    ui->spectDataButton->setEnabled(true);
      //  break;
      //case associatedSpectrum::EnsembleDataSpectrum:
      //  if (selected)
      //    ui->ensembleButton->setEnabled(true);
      //  break;
      case associatedSpectrum::ExtrapolatedSpectrumSpectrum:
        if(selected && dataAssoc->exists(fileType::ExtrapolatedSpectrum))
          ui->extrapolatedSpectrumButton->setEnabled(true);
        break;
      case associatedSpectrum::ExtrapolatedInstrumentSpectrumSpectrum:
        if(selected && dataAssoc->exists(fileType::ExtrapolatedInstrumentSpectrum))
          ui->extrapolatedInstrumentSpectrumButton->setEnabled(true);
        break;
      case associatedSpectrum::BinnedSpectrumSpectrum:
        if(selected && dataAssoc->exists(fileType::BinnedSpectrum))
          ui->binnedSpectrumButton->setEnabled(true);
        break;
      case associatedSpectrum::BinnedExtrapolatedSpectrumSpectrum:
        if(selected && dataAssoc->exists(fileType::BinnedExtrapolatedSpectrum))
          ui->binnedExtrapolatedSpectrumButton->setEnabled(true);
        break;
      case associatedSpectrum::BinnedExtrapolatedInstrumentedSpectrumSpectrum:
        if(selected && dataAssoc->exists(fileType::BinnedExtrapolatedInstrumentedSpectrum))
          ui->binnedExtrapolatedInstrumentSpectrumButton->setEnabled(true);
        break;
      //case associatedSpectrum::EnsembleAveragedBinnedSpectrumSpectrum:
      //  if(selected && dataAssoc->exists(fileType::EnsembleAveragedBinnedSpectrum))
      //    ui->EnsAvgBinnedSpectrumButton->setEnabled(true);
      //  break;
    }
    graphType = static_cast<ASSOCIATEDSPECTRUM>(++type);
  }

  exec();
  */

  while(graphType >  associatedSpectrum::Null) // run over graphable data types
  {
    if (graphType == associatedSpectrum::ASSOCIATEDSPECTRUM_LIMIT)
    {
      graphType = static_cast<associatedSpectrum>(--type);
      continue;
    }

    if (graphType == associatedSpectrum::Null)
      break;

    switch (graphType)
    {
      case associatedSpectrum::TransformedDataSpectrum:
        if (dataAssoc->exists(graphType)) {
          ui->dataButton->setEnabled(true);
          ui->dataButton->setChecked(true);
        }
        break;
      case associatedSpectrum::TransformedWeightsSpectrum:
        if (dataAssoc->exists(graphType)) {
          ui->weightButton->setEnabled(true);
          ui->weightButton->setChecked(true);
        }
        break;
      case associatedSpectrum::WeightedTransformSpectrum:
        if (dataAssoc->exists(graphType)) {
          ui->combinedDataButton->setEnabled(true);
          ui->combinedDataButton->setChecked(true);
        }
        break;
      case associatedSpectrum::TransformedNoiseSpectrum:
        if (dataAssoc->exists(graphType)) {
          ui->noiseButton->setEnabled(true);
          ui->noiseButton->setChecked(true);
        }
        break;
      case associatedSpectrum::TransformedWeightedNoiseSpectrum:
        if (dataAssoc->exists(graphType)) {
          ui->weightedNoiseButton->setEnabled(true);
          ui->weightedNoiseButton->setChecked(true);
        }
        break;
      case associatedSpectrum::TransformedFilterSpectrum:
        if(dataAssoc->exists(graphType))
        {
          ui->filterButton->setEnabled(true);
          ui->filterButton->setChecked(true);
        }
        break;
      case associatedSpectrum::TransformedBeamSpectrum:
        if (dataAssoc->exists(graphType)) {
          ui->beamButton->setEnabled(true);
          ui->beamButton->setChecked(true);
        }
        break;
      case associatedSpectrum::EnsembleAveragedSpectrumSpectrum:
        if (dataAssoc->exists(graphType)) {
          ui->EnsAvgSpectrumButton->setEnabled(true);
          ui->EnsAvgSpectrumButton->setChecked(true);
        }
        break;
      case associatedSpectrum::EnsembleAveragedNoiseSpectrum:
        if (dataAssoc->exists(graphType)) {
          ui->EnsAvgNoiseSpectrumButton->setEnabled(true);
          ui->EnsAvgNoiseSpectrumButton->setChecked(true);
        }
        break;
      case associatedSpectrum::ExtrapolatedSpectrumSpectrum:
        if (dataAssoc->exists(graphType)) {
          ui->extrapolatedSpectrumButton->setEnabled(true);
          ui->extrapolatedSpectrumButton->setChecked(true);
        }
        break;
      case associatedSpectrum::ExtrapolatedInstrumentSpectrumSpectrum:
        if (dataAssoc->exists(graphType)) {
          ui->extrapolatedInstrumentSpectrumButton->setEnabled(true);
          ui->extrapolatedInstrumentSpectrumButton->setChecked(true);
        }
        break;
      case associatedSpectrum::BinnedSpectrumSpectrum:
        if (dataAssoc->exists(graphType)) {
          ui->binnedSpectrumButton->setEnabled(true);
          ui->binnedSpectrumButton->setChecked(true);
        }
        break;
      case associatedSpectrum::BinnedExtrapolatedSpectrumSpectrum:
        if(dataAssoc->exists(graphType))
        {
          ui->binnedExtrapolatedSpectrumButton->setEnabled(true);
          ui->binnedExtrapolatedSpectrumButton->setChecked(true);
        }
        break;
      case associatedSpectrum::BinnedExtrapolatedInstrumentedSpectrumSpectrum:
        if (dataAssoc->exists(graphType)) {
          ui->binnedExtrapolatedInstrumentSpectrumButton->setEnabled(true);
          ui->binnedExtrapolatedInstrumentSpectrumButton->setChecked(true);
        }
        break;
    }

    graphType = static_cast<associatedSpectrum>(--type);
  }

  exec();
}

void graphSelectDialog::reset() {
  activeGraphs = 0;
  graphType = associatedSpectrum::Null;

  ui->dataButton->setEnabled(true);
  ui->weightButton->setEnabled(true);
  ui->noiseButton->setEnabled(true);
  ui->filterButton->setEnabled(true);
  ui->beamButton->setEnabled(true);

  ui->combinedDataButton->setEnabled(true);
  ui->EnsAvgSpectrumButton->setEnabled(true);
  ui->weightedNoiseButton->setEnabled(true);
  ui->EnsAvgNoiseSpectrumButton->setEnabled(true);

  //ui->spectDataButton->setEnabled(true);
  //ui->ensembleButton->setEnabled(true);

  ui->extrapolatedSpectrumButton->setEnabled(true);
  ui->extrapolatedInstrumentSpectrumButton->setEnabled(true);
  ui->binnedSpectrumButton->setEnabled(true);
  ui->binnedExtrapolatedSpectrumButton->setEnabled(true);
  ui->binnedExtrapolatedInstrumentSpectrumButton->setEnabled(true);


  dirty = false;
}

void graphSelectDialog::finalize() {
  validate();
  Q_EMIT graphSelected(graphType);
  accept();
}

void graphSelectDialog::cancel() {
  if (dirty)
    dirty = false;
  close();
}

void graphSelectDialog::help() {

}
