/***************************************************************************
 *   mainwindow.cpp                                                        *
 *   Copyright (C) 2014 by Daniel Suson                                    *
 *   suson@calumet.purdue.edu                                              *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU General Public License     *
 *   along with this program; if not, write to the                         *
 *   Free Software Foundation, Inc.,                                       *
 *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
 *                                                                         *
 *   In addition, as a special exception, the copyright holders give       *
 *   permission to link the code of this program with any edition of       *
 *   the Qt library by Trolltech AS, Norway (or with modified versions     *
 *   of Qt that use the same license as Qt), and distribute linked         *
 *   combinations including the two.  You must obey the GNU General        *
 *   Public License in all respects for all of the code used other than    *
 *   Qt.  If you modify this file, you may extend this exception to        *
 *   your version of the file, but you are not obligated to do so.  If     *
 *   you do not wish to do so, delete this exception statement from        *
 *   your version.                                                         *
 ***************************************************************************
 * Description:                                                            *
 *                                                                         *
 * This class defines the main window structure associated with the user   *
 * Qt5 user interface.                                                     *
 * ----------------------- Change Log ------------------------------------ *
 * Date    Name         Description                                        *
 *                                                                         *
 ***************************************************************************
 * This software evolved from work that was done by Eric Hivon at the      *
 * California Institute of Technology on the MASTER algorithm (Hivon, E.,  *
 * et al., ApJ, vol 567, p 2).  It adapts or interfaces with these         *
 * packages:                                                               *
 *                                                                         *
 * HealPix         (http://www.eso.org/science/healpix/)                   *
 * FTOOLS & FITSIO (http://heasarc.gsfc.nasa.gov/docs/corp/software.html)  *
 *                                                                         *
 * Any publications or presentations that use results generated by this    *
 * program must reference the fact that it was developed by Daniel Suson   *
 ***************************************************************************/
#include <QFileInfo>

#include "mainwindow.h"
#include "ui_mainwindow.h"

#include "../libanalyzer/fitsmanager.h"
#include "../libanalyzer/hdf5manager.h"
#include "../libanalyzer/csvmanager.h"

mainWindow::mainWindow() :
            GUIManager(),
            ui(new Ui::MainWindow)
{
  associationVector = new std::vector<association*>();
  try
  {
    associationVector->push_back(new association(this,  mainWindow::progressBarWrapper,
                                                        mainWindow::progressTextWrapper,
                                                        mainWindow::errorMessageWrapper));

    s_association = (*associationVector)[0];
  }
  catch (const std::overflow_error &e)
  {
    errorMessage("The attempt to create a new data association failed due to overflow error.");
    return;
  }
  catch (const std::runtime_error &e)
  {
    errorMessage("The attempt to create a new data association failed due to runtime error.");
    return;
  }
  catch (const std::exception &e)
  {
    errorMessage("The attempt to create a new data association failed due to exception error.");
    return;
  }
  catch (...)
  {
    errorMessage("The attempt to create a new data association failed.");
    return;
  }

  /* set up the user interface */
  ui->setupUi(this);


  /* create data stream association */
  QString title, message;

  /* create dialogs needed to pass signals back and forth */
  assocDlg = new associationSelectDialog(associationVector);
  assocDlg->setCurrAssoc(s_association);

  ctrlDlg = new controlDataDialog(s_association);
  energyDlg = new energyDialog();
  multSelDlg = new multipleSelectionDialog(s_association);
  pixSelectDlg = new pixelizerDialog(s_association);
  healpixDlg = new healpixDialog(s_association);
  transSelectDlg = new transformerDialog(s_association);
  rshtDlg = new rshtDialog(s_association);
  analSelectDlg = new analyzerDialog(s_association);
  specDlg = new spectrumDialog();

  mapperDlg = new mapperDialog(s_association);
  mapSelectDlg = new mapSelectDialog(s_association);
  grapherDlg = new graphDialog(s_association);
  graphSelectDlg = new graphSelectDialog(s_association);

  /* initialize progress bar */
  ui->progressBar->reset();
  ui->progressBar->setRange(0,100);
  ui->progressLabel->setText(QString(tr("Ready")));
  s_progressInterface = new progress(this,progressBarWrapper);

  /* set LED indicators */
  selectedDataType = fileType::Null;
  selectedDataStream = genericType::NoGeneric;
  ui->inputDataLED->setState(QLedLabel::missing);
  ui->inputMaskLED->setState(QLedLabel::missing);
  ui->inputNoiseLED->setState(QLedLabel::notNecessary);
  ui->inputFilterLED->setState(QLedLabel::notNecessary);
  ui->inputBeamLED->setState(QLedLabel::notNecessary);
  ui->pixelDataLED->setState(QLedLabel::missing);
  ui->pixelMaskLED->setState(QLedLabel::missing);
  ui->pixelNoiseLED->setState(QLedLabel::notNecessary);
  ui->pixelFilterLED->setState(QLedLabel::notNecessary);
  ui->pixelBeamLED->setState(QLedLabel::notNecessary);
  ui->transDataLED->setState(QLedLabel::missing);
  ui->transMaskLED->setState(QLedLabel::missing);
  ui->transNoiseLED->setState(QLedLabel::notNecessary);
  ui->transFilterLED->setState(QLedLabel::notNecessary);
  ui->transBeamLED->setState(QLedLabel::notNecessary);
  ui->almDataLED->setState(QLedLabel::missing);
  ui->almMaskLED->setState(QLedLabel::missing);
  ui->almNoiseLED->setState(QLedLabel::notNecessary);
  ui->almFilterLED->setState(QLedLabel::notNecessary);
  ui->almBeamLED->setState(QLedLabel::notNecessary);
  ui->inverseDataLED->setState(QLedLabel::missing);
  ui->inverseMaskLED->setState(QLedLabel::missing);
  ui->inverseNoiseLED->setState(QLedLabel::notNecessary);
  ui->inverseFilterLED->setState(QLedLabel::notNecessary);
  ui->inverseBeamLED->setState(QLedLabel::notNecessary);


  /* set up Qt signal/slot connections */
  connect(ui->controlAction, &QAction::triggered, [=](bool open){ctrlDlg->configure(false);});
  connect(ui->openAction, &QAction::triggered, [=](){openFile();});
  connect(ui->saveAction, &QAction::triggered, [=](){saveFile();});

  connect(ui->addAssociationAction, &QAction::triggered, [=](){addAssociation(); });
  connect(ui->selectAssociation, &QAction::triggered, [=](){assocDlg->configure();});

  connect(dynamic_cast<associationSelectDialog*>(assocDlg), &associationSelectDialog::associationSelected, [=](association* newAssoc){setAssociation(newAssoc);});

//  connect(ui->informationAction, Q_SIGNAL(triggered(bool)), this, Q_SLOT());
//  connect(ui->printAction, Q_SIGNAL(triggered(bool)), this, Q_SLOT());
  connect(ui->clearAction, &QAction::triggered, [=](){reset();});
  connect(ui->exitAction, &QAction::triggered, [=](){close();});
  connect(ui->pixelizeAction, &QAction::triggered, [=](){selectPixelizer();});
  connect(ui->transformAction, &QAction::triggered, [=](){selectTransformer();});
  //connect(ui->analyzeAction, &QAction::triggered, [=](){analyze();});

  connect(ui->analyzeAction, &QAction::triggered, [=](){selectAnalzyer();});

//  connect(ui->inverseAction, Q_SIGNAL(triggered(bool)), this, Q_SLOT());
  connect(ui->selectMapsAction, &QAction::triggered, [=](){mapSelectDlg->configure();});
  connect(ui->selectGraphsAction, &QAction::triggered, [=](){graphSelectDlg->configure();});
//  connect(ui->zoomInAction, Q_SIGNAL(triggered(bool)), this, Q_SLOT());
//  connect(ui->zoomOutAction, Q_SIGNAL(triggered(bool)), this, Q_SLOT());
//  connect(ui->zoomNormalAction, Q_SIGNAL(triggered(bool)), this, Q_SLOT());
//  connect(ui->configureMapper, Q_SIGNAL(triggered()), this, Q_SLOT(setupMapper()));
//  connect(ui->configurePoxelizer, Q_SIGNAL(triggered(bool)), this, Q_SLOT());
//  connect*ui->configureTransformer, Q_SIGNAL(triggered(bool)), this, Q_SLOT());
//  connect(ui->HandbookAction, Q_SIGNAL(triggered(bool)), this, Q_SLOT());
//  connect(ui->aboutAnalyzerAction, Q_SIGNAL(triggered(bool)), this, Q_SLOT());
  connect(dynamic_cast<controlDataDialog*>(ctrlDlg), &controlDataDialog::buildControlData, [=](FILETYPE value,bool complete){createControlData(value,complete);});


  connect(this, &mainWindow::saveDataSets, [=](){dataSelectDlg->configure();});
  connect(this, &mainWindow::readDataSets, [=](FILETYPE* dataTypes, int* numTypes){dataSelectDlg->configure(dataTypes, numTypes);});

  connect(this,&mainWindow::selectEnergies,[=](double low, double high){energyDlg->configure(low,high);});
  connect(this,&mainWindow::selectSlices,[=](){multSelDlg->configure(); });

  //connect(energyDlg,&energyDialog::energySelected,[=](double low, double high){readData(low,high);});
  connect(mapperDlg, &mapperDialog::mapperReady, [=](){buildMaps();});
  connect(this, &mainWindow::selectMapDisplay, [=](unsigned int selection){mapSelectDlg->configure(selection);});
  connect(mapSelectDlg, &mapSelectDialog::mapSelected, [=](ASSOCIATEDMAP map){displayMap(map);});
  connect(grapherDlg, &graphDialog::grapherReady, [=](){buildGraphs();});
  connect(this, &mainWindow::selectGraphDisplay, [=](unsigned int selection){graphSelectDlg->configure(selection);});
  connect(graphSelectDlg, &graphSelectDialog::graphSelected, [=](associatedSpectrum graph){displayGraph(graph);});
  connect(dynamic_cast<pixelizerDialog*>(pixSelectDlg), &pixelizerDialog::pixelizerSelected, [=](PIXELSCHEME scheme){configurePixelizer(scheme);});
  connect(dynamic_cast<transformerDialog*>(transSelectDlg), &transformerDialog::transformerSelected, [=](TRANSFORMERSCHEME scheme){configureTransformer(scheme);});

  connect(dynamic_cast<analyzerDialog*>(analSelectDlg), &analyzerDialog::analyzerSelected, [=](){configureAnalyzer();});

  connect(dynamic_cast<healpixDialog*>(healpixDlg), &healpixDialog::pixelizeData, [=](){pixelize();});
  connect(dynamic_cast<rshtDialog*>(rshtDlg), &rshtDialog::transformData, [=](){transform();});
  connect(dynamic_cast<spectrumDialog*>(specDlg), &spectrumDialog::spectrumReady, [=](){analyze();});
//  connect(this, Q_SIGNAL(redrawMap()), ui->mapTab, Q_SLOT(paintEvent(QPaintEvent*)));
//  connect(ctrlDlg, Q_SIGNAL(controlDataSet()), this, Q_SLOT(checkMapper()));
//  connect(mapperDlg, Q_SIGNAL(mapperSet(MAPTYPE,long,long,ORIENTATION)), this, Q_SLOT(createMaps(MAPTYPE,long,long,ORIENTATION)));
//  connect(this, Q_SIGNAL(imageConfigured(association*,FILETYPE*)), mapSelectDlg, configure(association*,FILETYPE*));
//  connect(this, Q_SIGNAL(mapSelected(QWidget*)), this, drawImage(QWidget*));

  // set initial directory to user's home directory
  directory = QDir::home();

  // create progress interface
//  progressInterface = analyzer_set_progress_callback(this,progressBarWrapper);
}

mainWindow::~mainWindow() {
  // delete primary user interface
  delete ui;

  // delete associated dialog boxes
  delete ctrlDlg;
  delete energyDlg;
  delete pixSelectDlg;
  delete healpixDlg;
  delete transSelectDlg;
  delete rshtDlg;
  delete specDlg;
  delete mapperDlg;
  delete mapSelectDlg;
  delete grapherDlg;
  delete graphSelectDlg;
}

void mainWindow::progressBarWrapper(void* uiObj, int value)
{
  mainWindow* here = (mainWindow*) uiObj;
  here->updateProgressBar(value);
}

void mainWindow::progressTextWrapper(void* uiObj, const char* updateName)
{
  mainWindow* here = (mainWindow*) uiObj;
  here->updateProgressText(updateName);
}

void mainWindow::errorMessageWrapper(void* uiObj, const char* errMess)
{
  mainWindow* here = (mainWindow*) uiObj;
  here->errorMessage(errMess);
}

void mainWindow::updateProgressBar(int value)
{
  ui->progressBar->setValue(value);
}

void mainWindow::updateProgressText(const char* updateName)
{
  ui->progressLabel->setText(updateName);
  ui->progressLabel->adjustSize();
  //ui->progressLabel->parentWidget()->layout()->update();
}

void mainWindow::errorMessage(const char* errMess)
{
  QMessageBox::critical(this, "Error", errMess);
}

void mainWindow::displayMessage(const char* mess)
{
  QMessageBox::information(this, "Info Box", mess);
}

bool mainWindow::addDataMessage(const char* mess)
{
  QMessageBox questionBox;
  questionBox.setWindowTitle("Data Missing");
  questionBox.setText(mess);

  QPushButton *createButton = questionBox.addButton(tr("Create"),QMessageBox::ActionRole);
  QPushButton *openButton = questionBox.addButton(tr("Open"),QMessageBox::ActionRole);
  QPushButton *noneButton = questionBox.addButton(tr("No"),QMessageBox::ActionRole);

  questionBox.exec();
  if (questionBox.clickedButton() == createButton)
    ctrlDlg->configure(false);

  if (questionBox.clickedButton() == openButton)
    openFile();

  if (questionBox.clickedButton() == noneButton)
    return false;

  return true;
}

bool mainWindow::replaceDataChain(const char* mess)
{
  QMessageBox::StandardButton reply = QMessageBox::question(this, "Replace Current Data Chain?", mess,
                                                            QMessageBox::Yes | QMessageBox::No, QMessageBox::No);
  if (reply == QMessageBox::Yes)
    return true;
  else
    return false;
}

void mainWindow::emitReadDataSets(FILETYPE* dataTypes, int* numTypes)
{
  dataSelectDlg = new dataSelectDialog(s_association, RWMode::Read);
  connect(dynamic_cast<dataSelectDialog*>(dataSelectDlg), &dataSelectDialog::dataSelected,
              [=](int size, FILETYPE types[])
              {
                dynamic_cast<dataSelectDialog*>(dataSelectDlg)->accept();
                readData(size, types);
              });

  Q_EMIT readDataSets(dataTypes, numTypes);
}

void mainWindow::selectFileName(bool read)
{
  QString title, fileTypes, fName;

  QComboBox *observatoryBox = new QComboBox();
  int obs = static_cast<int>(Unknown);

  while (static_cast<OBSERVATORY>(obs) != OBSERVATORY_LIMIT)
  {
    QString obsName = QString(observatoryNames[obs].c_str());
    observatoryBox->addItem(obsName);
    obs += 1;
  }

  if(read)
  {
    title = QString(tr("Open File"));
    fileTypes = QString(tr("Input Files (*.fits *.hdf5 *.csv)"));
  }
  else// write
  {
    // extend the standard QFileDialog by adding the data types as a combo box
    title = QString(tr("Save File"));
    fileTypes = QString(tr("Fits File (*.fits);; HDF5 File (*.hdf5);; CSV File (*.csv);;"));
  }

  QFileDialog* fileDialog = new QFileDialog(this, title, QDir::homePath(), fileTypes);
  fileDialog->setOption(QFileDialog::DontUseNativeDialog);
  fileDialog->setDirectory(directory);

  QLayout *layout = fileDialog->layout();
  QGridLayout *gridbox = qobject_cast<QGridLayout*>(layout);

  fileDialog->setLayout(gridbox);

  if(read)
  {
    fileDialog->setAcceptMode(QFileDialog::AcceptOpen);

    if(gridbox)
    {
      gridbox->addWidget(new QLabel(tr("Observatory:")));
      gridbox->addWidget(observatoryBox);
    }
  }
  else // write
  {
    fileDialog->setAcceptMode(QFileDialog::AcceptSave);
    fileDialog->setOption(QFileDialog::DontConfirmOverwrite);
  }

  // execute the new dialog box
  if (fileDialog->exec())
  {
    // get current directory
    directory = fileDialog->directory();

    // get file name
    QStringList selectedFileNames;
    selectedFileNames = fileDialog->selectedFiles();

    if (selectedFileNames.size() > 1)
      errorMessage("To many files selected.");

    // check that file type is a supported type
    fName = selectedFileNames[0];
    fileName = fName.toStdString();

    QString filter = fileDialog->selectedNameFilter();

    if (fName.contains(".fits",Qt::CaseInsensitive))
    {
      dataFormat = Fits;

      QFileInfo checkFile(fName);
      if (checkFile.exists() && checkFile.isFile())
        fName = "!" + fName;
    }

    if (fName.contains(".hdf5", Qt::CaseInsensitive) || fName.contains(".h5", Qt::CaseInsensitive))
      dataFormat = HDF5;

    if (fName.contains(".csv",Qt::CaseInsensitive))
      dataFormat = CSV;

    if (dataFormat == None)
      errorMessage("File Format must be FITS, HDF5 or CSV.");

    if(read)
    {
      obs = observatoryBox->currentIndex();
      dataSource = static_cast<OBSERVATORY>(obs);

      if(obs == static_cast<int>(OBSERVATORY::Unknown))
        errorMessage("Invalid observatory selected");
    }
  }
}

void mainWindow::emitSaveDataSets()
{
  dataSelectDlg = new dataSelectDialog(s_association, RWMode::Write);
  connect(dynamic_cast<dataSelectDialog*>(dataSelectDlg), &dataSelectDialog::dataSelected,
          [=](int numTypes, FILETYPE dataTypes[])
          {
            dynamic_cast<dataSelectDialog*>(dataSelectDlg)->accept();
            writeData(numTypes, dataTypes);
          });

  Q_EMIT saveDataSets();
}

void mainWindow::emitSelectSlices()
{
  connect(dynamic_cast<multipleSelectionDialog*>(multSelDlg), &multipleSelectionDialog::slicesSelected,
          [=](int min, int max)
          {
            s_association->fileIOEngine()->minSlice(min);
            s_association->fileIOEngine()->maxSlice(max);
          });

  Q_EMIT selectSlices();
}

void mainWindow::emitSelectEnergies()
{
  double minEnergy = s_association->fileIOEngine()->min_energy();
  double maxEnergy = s_association->fileIOEngine()->max_energy();

  // let user change energy range before reading data
  Q_EMIT selectEnergies(minEnergy, maxEnergy);
}
void mainWindow::addAssociation()
{
  try
  {
    association* newAssoc = new association(this,   GUIManager::progressBarWrapper,
                                                    GUIManager::progressTextWrapper,
                                                    GUIManager::errorMessageWrapper);
    associationVector->push_back(newAssoc);
    setAssociation(newAssoc);
  }
  catch (const std::overflow_error &e)
  {
    errorMessage("The attempt to create a new data association failed due to overflow error.");
    return;
  }
  catch (const std::runtime_error &e)
  {
    errorMessage("The attempt to create a new data association failed due to runtime error.");
    return;
  }
  catch (const std::exception &e)
  {
    errorMessage("The attempt to create a new data association failed due to exception error.");
    return;
  }
  catch (...)
  {
    errorMessage("The attempt to create a new data association failed.");
    return;
  }

   mapperDlg->configured(false);
  grapherDlg->configured(false);

  ctrlDlg->reset();

  QMessageBox addSuccessful;
  addSuccessful.setText("Addition Successful. Now using the new addition.");
  addSuccessful.setStandardButtons(QMessageBox::Ok);
  addSuccessful.exec();
}

void mainWindow::setAssociation(association* newAssoc)
{
  s_association = newAssoc;

  assocDlg->setCurrAssoc(s_association);

  if(dataSelectDlg)
    dataSelectDlg->setAssociation(s_association);

         ctrlDlg->setAssociation(s_association);
       energyDlg->setAssociation(s_association);
      multSelDlg->setAssociation(s_association);
    pixSelectDlg->setAssociation(s_association);
      healpixDlg->setAssociation(s_association);
  transSelectDlg->setAssociation(s_association);
         rshtDlg->setAssociation(s_association);
       mapperDlg->setAssociation(s_association);
    mapSelectDlg->setAssociation(s_association);
      grapherDlg->setAssociation(s_association);
  graphSelectDlg->setAssociation(s_association);

         ctrlDlg->configured(false);
       energyDlg->configured(false);
      multSelDlg->configured(false);
    pixSelectDlg->configured(false);
      healpixDlg->configured(false);
  transSelectDlg->configured(false);
         rshtDlg->configured(false);
         specDlg->configured(false);

  clearMaps();
  clearGraphs();
}

void mainWindow::setControlDlgConfigured(bool config)
{
    ctrlDlg->configure(config);
}

void mainWindow::setPixelizerAttr()
{
  switch (s_association->pixelizationEngineType())
  {
    case HealPIX:
      s_association->addEngine(dataEngines::Pixelization, HealPIX);
      s_association->pixelizationEngine()->scale(healpixDlg->scale());

      s_association->pixelizationEngine()->usePixelAvg(healpixDlg->usePixelAvg());
      s_association->pixelizationEngine()->usePixelDev(healpixDlg->usePixelDev());
      s_association->pixelizationEngine()->usePixelVar(healpixDlg->usePixelVar());

      s_association->pixelizationEngine()->doAvgNormalize(healpixDlg->doAvgNormalize());
      s_association->pixelizationEngine()->doVarNormalize(healpixDlg->doVarNormalize());
      s_association->pixelizationEngine()->doMinMaxScale(healpixDlg->doMinMaxScale());

      if (healpixDlg->order())
        s_association->pixelizationEngine()->pixelLayout(Nest);
      else
        s_association->pixelizationEngine()->pixelLayout(Ring);

      s_association->pixelizationEngine()->configured(true);
      break;
    default:
      selectPixelizer();
  }
}

void mainWindow::setTransformerAttr()
{
  switch (s_association->transformationEngineType())
  {
    case Rsht:
      s_association->addEngine(dataEngines::Transformation, Rsht);
      s_association->transformationEngine()->minIndex(rshtDlg->minimumIndex());
      s_association->transformationEngine()->maxIndex(rshtDlg->maximumIndex());
      s_association->transformationEngine()->iterations(rshtDlg->iterations());
      s_association->transformationEngine()->configured(true);
      break;
    default:
      selectTransformer();
  }
}

void mainWindow::setAnalyzerAttr()
{
  s_association->addEngine(dataEngines::PseudoSpectrum);
  s_association->powerSpectraEngine()->binning(specDlg->binSpectrum());
  s_association->powerSpectraEngine()->computeInverse(specDlg->invertTransforms());
  s_association->powerSpectraEngine()->weight(specDlg->weighIndices());
  s_association->powerSpectraEngine()->numLPerBin(specDlg->indicesPerBin());
  s_association->powerSpectraEngine()->maskIndex(specDlg->maskLowestIndices());
  s_association->powerSpectraEngine()->ensembleIterations(specDlg->ensembleIterations());
  s_association->powerSpectraEngine()->configured(true);
}

bool mainWindow::handleMissingTransformer()
{
  selectTransformer();

  return true;
}

void mainWindow::configureDisplay(FILETYPE dataType)
{
  //If running pixelizer
  //ui->progressBar->setValue(value);  
  
  
  switch (dataType) {
    case fileType::InputData:
    case fileType::InputWeights:
    case fileType::WeightedData:
    case fileType::InputNoise:
    case fileType::InputWeightedNoise:
    case fileType::InputFilter:
    case fileType::InputBeam:
    case fileType::PixelizedData:
    case fileType::PixelizedWeights:
    case fileType::WeightedPixel:
    case fileType::PixelizedNoise:
    case fileType::PixelizedWeightedNoise:
    case fileType::PixelizedFilter:
    case fileType::PixelizedBeam:
    case fileType::PixelOccupancy:
    case fileType::InverseData:
    case fileType::InverseWeights:
    case fileType::WeightedInverse:
    case fileType::InverseNoise:
    case fileType::InverseWeightedNoise:
    case fileType::InverseFilter:
    case fileType::InverseBeam:
      configureMaps();
      break;
    case fileType::TransformedData:
    case fileType::TransformedWeights:
    case fileType::WeightedTransform:
    case fileType::TransformedNoise:
    case fileType::TransformedWeightedNoise:
    case fileType::TransformedFilter:
    case fileType::TransformedBeam:
    //case fileType::SpectralData:
    //case fileType::EnsembleData:
    case fileType::EnsembleAveragedNoise:
    case fileType::EnsembleAveragedSpectrum:
    case fileType::ExtrapolatedSpectrum:
    case fileType::ExtrapolatedInstrumentSpectrum:
    case fileType::BinnedSpectrum:
    case fileType::BinnedExtrapolatedSpectrum:
    case fileType::BinnedExtrapolatedInstrumentedSpectrum:
    //case fileType::EnsembleAveragedBinnedSpectrum:
      configureGraphs();
      break;
    default:
      break;
  }
}

void mainWindow::configureMaps() {
  if (!mapperDlg->configured())
    mapperDlg->configure();
  buildMaps();
}

void mainWindow::buildMaps() {
  QString title, message;
  
  if (!s_association->exists(dataEngines::Mapping))
    s_association->addEngine(dataEngines::Mapping,Mollweide);
  Mapper* mapEng = s_association->mappingEngine();

  int numMaps = 0, displayData = 0;
  FILETYPE dataType = fileType::Null;
  ASSOCIATEDMAP mapType = associatedMap::Null;
  ASSOCIATEDMAP current = associatedMap::Null;
  ALLTYPES   allMapType = allTypes::FILETYPE_LIMIT;
  int type = static_cast<int>(current);
  int assocType = static_cast<int>(mapType);
  int allType = static_cast<int>(allMapType);
  
  while (type >= 0) {
    if (dataType == fileType::Null) {
      dataType = static_cast<FILETYPE>(++type);
      mapType = static_cast<ASSOCIATEDMAP>(++assocType);
      allMapType = static_cast<ALLTYPES>(++allType);
      continue;
    }

    if (dataType == fileType::MAP_LIMIT)
      break;

    if (s_association->exists(dataType)) {
      if(s_association->exists(mapType))
        s_association->reset(allMapType);
      try {
        s_association->generateMap(dataType);
      }
      catch (ERRORCODES error) {
        title = QString(tr("Error code returned"));
        message = QString(tr("The attempt to create the map for data type %1 failed.\nError code %2"))
                              .arg(QString::fromStdString(s_association->dataNames((int)dataType)))
                              .arg(QString::fromStdString(s_association->errorDetails(error)));
        QMessageBox::critical(this,title,message);
        return;
      }
      numMaps++;
      displayData += (1 << (type-1));
      current = mapType;
    }
    dataType = static_cast<FILETYPE>(++type);
    mapType = static_cast<ASSOCIATEDMAP>(++assocType);
    allMapType = static_cast<ALLTYPES>(++allType);
  }

  if (numMaps) {
    if (numMaps > 1)
      Q_EMIT selectMapDisplay(displayData);
    else
      displayMap(current);
  }
}

void mainWindow::displayMap(ASSOCIATEDMAP map) {
  QString title, message;

  activeMap = 0;

  switch (map) {
    case associatedMap::InputDataMap:
      activeMap = s_association->inputDataMap()->transferRGBData();
      break;
    case associatedMap::InputWeightsMap:
      activeMap = s_association->inputWeightsMap()->transferRGBData();
      break;
    case associatedMap::WeightedDataMap:
      activeMap = s_association->inputMap()->transferRGBData();
      break;
    case associatedMap::InputNoiseMap:
      activeMap = s_association->inputNoiseMap()->transferRGBData();
      break;
    case associatedMap::InputWeightedNoiseMap:
      activeMap = s_association->weightedNoiseMap()->transferRGBData();
      break;
    case associatedMap::InputFilterMap:
      activeMap = s_association->inputFilterMap()->transferRGBData();
      break;
    case associatedMap::InputBeamMap:
      activeMap = s_association->inputBeamMap()->transferRGBData();
      break;

    case associatedMap::PixelizedDataMap:
      activeMap = s_association->pixelDataMap()->transferRGBData();
      break;
    case associatedMap::PixelizedWeightsMap:
      activeMap = s_association->pixelWeightsMap()->transferRGBData();
      break;
    case associatedMap::WeightedPixelMap:
      activeMap = s_association->pixelMap()->transferRGBData();
      break;
    case associatedMap::PixelOccupancyMap:
      activeMap = s_association->pixelOccupancyMap()->transferRGBData();
      break;
    case associatedMap::PixelizedNoiseMap:
      activeMap = s_association->pixelNoiseMap()->transferRGBData();
      break;
    case associatedMap::PixelizedWeightedNoiseMap:
      activeMap = s_association->pixelWeightedNoiseMap()->transferRGBData();
      break;
    case associatedMap::PixelizedFilterMap:
      activeMap = s_association->pixelFilterMap()->transferRGBData();
      break;
    case associatedMap::PixelizedBeamMap:
      activeMap = s_association->pixelBeamMap()->transferRGBData();
      break;

    case associatedMap::InverseDataMap:
      activeMap = s_association->invDataMap()->transferRGBData();
      break;
    case associatedMap::InverseWeightsMap:
      activeMap = s_association->invWeightsMap()->transferRGBData();
      break;
    case associatedMap::WeightedInverseMap:
      activeMap = s_association->invMap()->transferRGBData();
      break;
    case associatedMap::InverseNoiseMap:
      activeMap = s_association->invNoiseMap()->transferRGBData();
      break;
    case associatedMap::InverseWeightedNoiseMap:
      activeMap = s_association->invWeightedNoiseMap()->transferRGBData();
      break;
    case associatedMap::InverseFilterMap:
      activeMap = s_association->invFilterMap()->transferRGBData();
      break;
    case associatedMap::InverseBeamMap:
      activeMap = s_association->invBeamMap()->transferRGBData();
      break;
    default:
      activeMap = 0;
  }

  if (activeMap == 0) {
    title = QString(tr("Error code returned"));
    message = QString(tr("The attempt to display the map for data type %1 failed.\nError: %2"))
                      .arg(QString::fromStdString(s_association->dataNames((int)map)))
                      .arg(QString::fromStdString(s_association->errorDetails(noDatamapError)));
    QMessageBox::critical(this,title,message);
    return;
  }
  paintMap(activeMap);
}

void mainWindow::paintMap(unsigned char* map) {
  QString title, message;
  int width = 0;
  int height = 0;
  activeMap = map;
  
  // create QImage to display
  if (!s_association->exists(dataEngines::Mapping)) {
    title = QString(tr("No mapping engine defined"));
    message = QString(tr("Cannot display the requested map.\nThere isn't any mapping engine defined!"));
    QMessageBox::critical(this,title,message);
  }
  width = s_association->mappingEngine()->width();
  height = s_association->mappingEngine()->height();
  QImage image = QImage(width,height,QImage::Format_RGB32);
  QRgb colorValue;
  
  int mapEnd = height * width * 3;
  int offset = 0, i = 0, j = 0;
  while (offset < mapEnd) {
    i = (offset/3) % width;
    j = (offset/3) / width;
    colorValue = qRgb(activeMap[offset],activeMap[offset+1],activeMap[offset+2]); // read RGB values at point (i,j)
    image.setPixel(i,j,colorValue);
    offset += 3;
  }
 
  // convert QImage to QPixmap and load into graphicsScene
  QPixmap pMap(width,height);
  pMap.convertFromImage(image);
  QGraphicsScene *display = new QGraphicsScene();
  display->addPixmap(pMap);
  
  // display map by loading graphics scene
  ui->tabWidget->setCurrentWidget(ui->mapTab);
  ui->mapView->setScene(display);
  ui->mapView->show();
  repaint();
}

void mainWindow::clearMaps()
{
  QGraphicsScene *display = ui->mapView->scene();
  if (display) {
    display->clear();
    ui->mapView->update();
  }
}

void mainWindow::configureGraphs() {
  if (!grapherDlg->configured())
    grapherDlg->configure();
  buildGraphs();
}

void mainWindow::buildGraphs() {
  QString title, message;

  if (!s_association->exists(dataEngines::Graphing))
    s_association->addEngine(dataEngines::Graphing);
  Grapher* graphEng = s_association->graphingEngine();

  int numGraphs = 0, displayData = 0;
  FILETYPE dataType = fileType::MAP_LIMIT;
  ASSOCIATEDSPECTRUM graphType = associatedSpectrum::Null;
  ASSOCIATEDSPECTRUM current = associatedSpectrum::Null;
  ALLTYPES allGraphType = allTypes::ASSOCIATEMAP_LIMIT;
  int type = static_cast<int>(current);
  int assocType = static_cast<int>(graphType);
  int allType = static_cast<int>(allGraphType);
  
  while (type >= (int)fileType::MAP_LIMIT) {
    if (dataType == fileType::MAP_LIMIT) {
      dataType = static_cast<FILETYPE>(++type);
      graphType = static_cast<ASSOCIATEDSPECTRUM>(++assocType);
      allGraphType = static_cast<ALLTYPES>(++allType);
      continue;
    }

    if (dataType == fileType::GRAPH_LIMIT)
      break;

    if (s_association->exists(dataType))
    {
      if (s_association->exists(graphType))
        s_association->reset(allGraphType);

      try {
        s_association->generateGraph(dataType);
      }
      catch (ERRORCODES error) {
        title = QString(tr("Error code returned"));
        message = QString(tr("The attempt to create the graph for data type %1 failed.\nError code %2"))
                              .arg(QString::fromStdString(s_association->dataNames((int)dataType)))
                              .arg(QString::fromStdString(s_association->errorDetails(noDatagraphError)));
        QMessageBox::critical(this,title,message);
        return;
      }
      numGraphs++;
      displayData += (1 << (type-1));
      current = graphType;
    }
    dataType = static_cast<FILETYPE>(++type);
    graphType = static_cast<ASSOCIATEDSPECTRUM>(++assocType);
    allGraphType = static_cast<ALLTYPES>(++allType);
  }

  if (numGraphs) {
    if (numGraphs > 1)
      Q_EMIT selectGraphDisplay(displayData);
    else
      displayGraph(current);
  }
}

void mainWindow::displayGraph(ASSOCIATEDSPECTRUM graph) {
  QString title, message;

  activeGraph = 0;

  switch (graph) {
    case associatedSpectrum::TransformedDataSpectrum:
      activeGraph = s_association->transDataGraph()->transferRGBData();
      break;
    case associatedSpectrum::TransformedWeightsSpectrum:
      activeGraph = s_association->transWeightsGraph()->transferRGBData();
      break;
    case associatedSpectrum::WeightedTransformSpectrum:
      activeGraph = s_association->transGraph()->transferRGBData();
      break;
    case associatedSpectrum::TransformedNoiseSpectrum:
      activeGraph = s_association->transNoiseGraph()->transferRGBData();
      break;
    case associatedSpectrum::TransformedWeightedNoiseSpectrum:
      activeGraph = s_association->transWeightedNoiseGraph()->transferRGBData();
      break;
    case associatedSpectrum::TransformedFilterSpectrum:
      activeGraph = s_association->transFilterGraph()->transferRGBData();
      break;
    case associatedSpectrum::TransformedBeamSpectrum:
      activeGraph = s_association->transBeamGraph()->transferRGBData();
      break;
    /*
    case associatedSpectrum::SpectralDataSpectrum:
      activeGraph = s_association->spectrumGraph()->transferRGBData();
      break;
    case associatedSpectrum::EnsembleDataSpectrum:
      activeGraph = s_association->ensembleGraph()->transferRGBData();
      break;
    */
    case associatedSpectrum::EnsembleAveragedNoiseSpectrum:
      activeGraph = s_association->EnsembleAveragedNoiseGraph()->transferRGBData();
      break;
    case associatedSpectrum::EnsembleAveragedSpectrumSpectrum:
      activeGraph = s_association->EnsembleAveragedSpectrumGraph()->transferRGBData();
      break;
    case associatedSpectrum::ExtrapolatedSpectrumSpectrum:
      activeGraph = s_association->ExtrapolatedSpectrumGraph()->transferRGBData();
      break;
    case associatedSpectrum::ExtrapolatedInstrumentSpectrumSpectrum:
      activeGraph = s_association->ExtrapolatedInstrumentSpectrumGraph()->transferRGBData();
      break;
    case associatedSpectrum::BinnedSpectrumSpectrum:
      activeGraph = s_association->BinnedSpectrumGraph()->transferRGBData();
      break;
    case associatedSpectrum::BinnedExtrapolatedSpectrumSpectrum:
      activeGraph = s_association->BinnedExtrapolatedSpectrumGraph()->transferRGBData();
      break;
    case associatedSpectrum::BinnedExtrapolatedInstrumentedSpectrumSpectrum:
      activeGraph = s_association->BinnedExtrapolatedInstrumentSpectrumGraph()->transferRGBData();
      break;
    /*
    case associatedSpectrum::EnsembleAveragedBinnedSpectrumSpectrum:
      activeGraph = s_association->EnsembleAveragedBinnedSpectrumGraph()->transferRGBData();
      break;
    */
    default:
      activeGraph = 0;
      break;
  }

  if (activeGraph == 0) {
    title = QString(tr("Error code returned"));
    message = QString(tr("The attempt to display the spectra for data type %1 failed.\nError: %2"))
                      .arg(QString::fromStdString(s_association->dataNames((int)graph)))
                      .arg(QString::fromStdString(s_association->errorDetails(noDatagraphError)));
    QMessageBox::critical(this,title,message);
    return;
  }
  paintGraph(activeGraph);
}

void mainWindow::paintGraph(unsigned char* graph) {
  QString title, message;
  int width = 0;
  int height = 0;
  activeGraph = graph;
  
  // create QImage to display
  if (!s_association->exists(dataEngines::Graphing)) {
    title = QString(tr("No graphing engine defined"));
    message = QString(tr("Cannot display the requested spectrum.\nThere isn't any graphing engine defined!"));
    QMessageBox::critical(this,title,message);
  }

  width = s_association->graphingEngine()->width();
  height = s_association->graphingEngine()->height();
  QImage image = QImage(width,height,QImage::Format_RGB32);
  QRgb colorValue;
  
  int mapEnd = height * width * 3;
  int offset = 0, i = 0, j = 0;
  while (offset < mapEnd) {
    i = (offset/3) % width;
    j = (offset/3) / width;
    colorValue = qRgb(activeGraph[offset],activeGraph[offset+1],activeGraph[offset+2]); // read RGB values at point (i,j)
    image.setPixel(i,j,colorValue);
    offset += 3;
  }
 
  // convert QImage to QPixmap and load into graphicsScene
  QPixmap pGraph(width,height);
  pGraph.convertFromImage(image);
  QGraphicsScene *display = new QGraphicsScene();
  display->addPixmap(pGraph);
  
  // display map by loading graphics scene
  ui->powerView->setScene(display);
  ui->tabWidget->setCurrentWidget(ui->powerTab);
  ui->powerView->show();
}

void mainWindow::clearGraphs()
{
  QGraphicsScene *display = ui->powerView->scene();
  if (display) {
    display->clear();
    ui->powerView->update();
  }
}

void mainWindow::selectPixelizer() {
  int count = 0, i = 1;
  PIXELSCHEME pixCount = static_cast<PIXELSCHEME>(i);
  
  while (i) {
    if (pixCount == PIXELIZER_LIMIT)
      break;
    count++;
    pixCount = static_cast <PIXELSCHEME>(++i);
  }

  if (count > 1) {
    if (!pixSelectDlg->configured())
      pixSelectDlg->configure();
  }
  else {
    if (!healpixDlg->configured())
      healpixDlg->configure();
  }

  return;
}

void mainWindow::selectTransformer() {
  int count = 0, i = 1;
  TRANSFORMERSCHEME transCount = static_cast<TRANSFORMERSCHEME>(i);
  
  while (i) {
    if (transCount == TRANSFORMER_LIMIT)
      break;
    count++;
    transCount = static_cast <TRANSFORMERSCHEME>(++i);
  }  

  if (count > 1)
  {
    if (!transSelectDlg->configured())
      transSelectDlg->configure();
  }
  else
  {
    if (!rshtDlg->configured())
      rshtDlg->configure();
  }

  return;
}

void mainWindow::selectAnalzyer()
{
  if (!specDlg->configured())
    specDlg->configure();
}

void mainWindow::configurePixelizer(PIXELSCHEME scheme)
{
  bool error = false;

  switch (scheme) {
    case HealPIX:
      healpixDlg->configure();
      break;
    default:
      error = true;
  }

  if (error)
    errorMessage("An invalid pixelization engine was specified.\nPixelization aborted.");
}

void mainWindow::configureTransformer(TRANSFORMERSCHEME scheme)
{
  bool error = false;

  switch (scheme) {
    case Rsht:
      rshtDlg->configure();
      break;
    default:
      error = true;
  }

  if (error)
    errorMessage("An invalid transformation engine was specified. \nTransformation aborted.");
}

void mainWindow::configureAnalyzer()
{
  if(!specDlg->configured())
    specDlg->configure();

}

void mainWindow::reset() {
  ctrlDlg->reset();
  mapperDlg->reset();
  mapSelectDlg->reset();
  pixSelectDlg->reset();
  healpixDlg->reset();
  transSelectDlg->reset();
  rshtDlg->reset();
  specDlg->reset();
    
  clearMaps();
  clearGraphs();

  s_association->reset();

  delete s_progressInterface;
  s_progressInterface = 0;
  ui->progressBar->reset();
}
