/***************************************************************************
 *   dataselectdlg.h                                                        *
 *   Copyright (C) 2014 by Daniel Suson                                    *
 *   suson@calumet.purdue.edu                                              *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU General Public License     *
 *   along with this program; if not, write to the                         *
 *   Free Software Foundation, Inc.,                                       *
 *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
 *                                                                         *
 *   In addition, as a special exception, the copyright holders give       *
 *   permission to link the code of this program with any edition of       *
 *   the Qt library by Trolltech AS, Norway (or with modified versions     *
 *   of Qt that use the same license as Qt), and distribute linked         *
 *   combinations including the two.  You must obey the GNU General        *
 *   Public License in all respects for all of the code used other than    *
 *   Qt.  If you modify this file, you may extend this exception to        *
 *   your version of the file, but you are not obligated to do so.  If     *
 *   you do not wish to do so, delete this exception statement from        *
 *   your version.                                                         *
 ***************************************************************************
 * Description:                                                            *
 *                                                                         *
 * This class defines the map select dialog box structure associated       *
 * with the Qt4 user interface.                                            *
 * ----------------------- Change Log ------------------------------------ *
 * Date    Name         Description                                        *
 *                                                                         *
 ***************************************************************************
 * This software evolved from work that was done by Eric Hivon at the      *
 * California Institute of Technology on the MASTER algorithm (Hivon, E.,  *
 * et al., ApJ, vol 567, p 2).  It adapts or interfaces with these         *
 * packages:                                                               *
 *                                                                         *
 * HealPix         (http://www.eso.org/science/healpix/)                   *
 * FTOOLS & FITSIO (http://heasarc.gsfc.nasa.gov/docs/corp/software.html)  *
 *                                                                         *
 * Any publications or presentations that use results generated by this    *
 * program must reference the fact that it was developed by Daniel Suson   *
 ***************************************************************************/
#ifndef _DATASELECTDIALOGPARENT_H_
#define _DATASELECTDIALOGPARENT_H_

#include <vector>
#include "../libanalyzer/atypes.h"
#include "../libanalyzer/association.h"

class dataSelectDialogParent
{
  
  public:
    dataSelectDialogParent(association* assoc, RWMode m = RWMode::Write);
    ~dataSelectDialogParent() {}

	void setMode(RWMode selectedMode) {mode = selectedMode;}
    RWMode getMode()                  {return mode;}
    void setData(FILETYPE* dataTypes, int numTypes) { for(int i = 0; i < numTypes; i += 1) dataSets->push_back(dataTypes[i]); }
    void setAssociation(association* newAssoc) {dataMgr = newAssoc;}

  //Q_SIGNALS:
    virtual void dataSelected(int size, FILETYPE data[]) = 0;

   //Q_SLOTS:
	void configure() {configure(mode);}

    virtual void configure(RWMode uiMode) = 0;
    virtual void configure(FILETYPE* dataTypes, int* numTypes) = 0;
	virtual void execute(FILETYPE* dataTypes, int* numTypes) = 0;
	virtual void execute() = 0;
    virtual void reset() = 0;

  protected:
    virtual void validate() = 0;
    virtual void selectAll() = 0;

    association * dataMgr;
    FILETYPE dataType;
    bool dirty;
    RWMode mode;
    std::vector<FILETYPE> *dataSets;
    
  // Q_SLOTS:
    virtual void help() = 0;
    virtual void finalize() = 0;
    virtual void cancel() = 0;
};
#endif
