/***************************************************************************
 *   GUIManager.cpp                                                        *
 *   Copyright (C) 2014 by Daniel Suson                                    *
 *   suson@calumet.purdue.edu                                              *
 *                                                                         *
 *   This program is free software{} you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation{} either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY{} without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU General Public License     *
 *   along with this program{} if not, write to the                         *
 *   Free Software Foundation, Inc.,                                       *
 *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
 *                                                                         *
 *   In addition, as a special exception, the copyright holders give       *
 *   permission to link the code of this program with any edition of       *
 *   the Qt library by Trolltech AS, Norway (or with modified versions     *
 *   of Qt that use the same license as Qt), and distribute linked         *
 *   combinations including the two.  You must obey the GNU General        *
 *   Public License in all respects for all of the code used other than    *
 *   Qt.  If you modify this file, you may extend this exception to        *
 *   your version of the file, but you are not obligated to do so.  If     *
 *   you do not wish to do so, delete this exception statement from        *
 *   your version.                                                         *
 ***************************************************************************
 * Description:                                                            *
 *                                                                         *
 * This class defines the gui structure                                    *
 * ----------------------- Change Log ------------------------------------ *
 * Date    Name         Description                                        *
 *                                                                         *
 ***************************************************************************
 * This software evolved from work that was done by Eric Hivon at the      *
 * California Institute of Technology on the MASTER algorithm (Hivon, E.,  *
 * et al., ApJ, vol 567, p 2).  It adapts or interfaces with these         *
 * packages:                                                               *
 *                                                                         *
 * HealPix         (http://www.eso.org/science/healpix/)                   *
 * FTOOLS & FITSIO (http://heasarc.gsfc.nasa.gov/docs/corp/software.html)  *
 *                                                                         *
 * Any publications or presentations that use results generated by this    *
 * program must reference the fact that it was developed by Daniel Suson   *
 ***************************************************************************/

#include "GUIManager.h"
#include "../libanalyzer/atypes.h"
#include "../libgraphics/grapher.h"
#include "../libgraphics/mapper.h"

GUIManager::GUIManager(int fSize) : fontSize(fSize)
{
    dataSource = OBSERVATORY::Analyzer;
    fileName = "";
    dataFormat = FORMAT::None;

	associationVector = new std::vector<association*>();
	try
	{
		associationVector->push_back(new association(this));
		s_association = (*associationVector)[0];
	}
	catch (const std::overflow_error &e)
	{
		errorMessage("The attempt to create a new data association failed due to overflow error.");
		return;
	}
	catch (const std::runtime_error &e)
	{
		errorMessage("The attempt to create a new data association failed due to runtime error.");
		return;
	}
	catch (const std::exception &e)
	{
		errorMessage("The attempt to create a new data association failed due to exception error.");
		return;
	}
	catch (...)
	{
		errorMessage("The attempt to create a new data association failed.");
		return;
	}
}

GUIManager::~GUIManager()
{
    for(association* s : (*associationVector))
        delete s;

    delete associationVector;
}

void GUIManager::errorMessage(const char* errMess)
{
	std::cerr << errMess << "\n";
}

void GUIManager::addAssociation()
{
  try
  {
    association* newAssoc = new association(this);
    associationVector->push_back(newAssoc);
    setAssociation(newAssoc);
  }
  catch (const std::overflow_error &e)
  {
    errorMessage("The attempt to create a new data association failed due to overflow error.");
    return;
  }
  catch (const std::runtime_error &e)
  {
    errorMessage("The attempt to create a new data association failed due to runtime error.");
    return;
  }
  catch (const std::exception &e)
  {
    errorMessage("The attempt to create a new data association failed due to exception error.");
    return;
  }
  catch (...)
  {
    errorMessage("The attempt to create a new data association failed.");
    return;
  }

   mapperDlg->configured(false);
  grapherDlg->configured(false);

  ctrlDlg->reset();

  displayMessage("Association addition successful.\n Now using the new addition.\n");
}

void GUIManager::setAssociation(association* newAssoc)
{
  s_association = newAssoc;

  assocDlg->setCurrAssoc(s_association);

  if(dataSelectDlg)
    dataSelectDlg->setAssociation(s_association);

         ctrlDlg->setAssociation(s_association);
//       energyDlg->setAssociation(s_association);
      multSelDlg->setAssociation(s_association);
    pixSelectDlg->setAssociation(s_association);
      healpixDlg->setAssociation(s_association);
  transSelectDlg->setAssociation(s_association);
         rshtDlg->setAssociation(s_association);
       mapperDlg->setAssociation(s_association);
    mapSelectDlg->setAssociation(s_association);
      grapherDlg->setAssociation(s_association);
  graphSelectDlg->setAssociation(s_association);

         ctrlDlg->configured(false);
       //energyDlg->configured(false);
      multSelDlg->configured(false);
    pixSelectDlg->configured(false);
      healpixDlg->configured(false);
  transSelectDlg->configured(false);
         rshtDlg->configured(false);
         specDlg->configured(false);

  clearMaps();
  clearGraphs();
}

void GUIManager::writeData(int numTypes, FILETYPE dataTypes[])
{
    try
    {
        s_association->fileIOEngine()->saveBase(fileName.c_str(), &numTypes, dataTypes);
        s_association->fileIOEngine()->save(&numTypes, dataTypes);
    }
    catch(ERRORCODES error)
    {
        errorMessage(s_association->errorDetails().c_str());
    }
}

void GUIManager::saveFile()
{
    selectFileName(false);

    if (s_association->exists(dataEngines::fileIO))
        s_association->reset(allTypes::fileIO);
    s_association->addEngine(dataEngines::fileIO, fileName.c_str(), dataFormat, selectedDataType, Write);

    emitSaveDataSets();

    displayMessage("Save Successfull.");
}

void GUIManager::readData(int numTypes, FILETYPE dataTypes[])
{
    try
    {
        if (s_association->fileIOEngine()->slices() > 1)
        {
            if(dataSource == Fermi || dataSource == Egret)
            {
                emitSelectSlices();

                s_association->fileIOEngine()->open(&numTypes, dataTypes);
            }
            else
                emitSelectEnergies();
        }
        else
            s_association->fileIOEngine()->open(&numTypes, dataTypes);
    }
    catch (ERRORCODES error)
    {
        errorMessage((s_association->errorDetails().c_str()));
    }
}

void GUIManager::openFile()
{
	if(!selectFileName(true))
		return;

    if (s_association->exists(dataEngines::fileIO))
        s_association->reset(allTypes::fileIO);

    s_association->addEngine(dataEngines::fileIO, fileName.c_str(), dataFormat, selectedDataType, Read);
    s_association->fileIOEngine()->observatory(dataSource);

    int* numTypes = new int(0);
    FILETYPE* dataTypes = s_association->fileIOEngine()->getHeaders(numTypes);

    emitReadDataSets(dataTypes, numTypes);

    // this vector represents whether
    // we have to map or graph or both
    std::vector<FILETYPE> types(2);
    types.assign(2, fileType::Null);

    for(int i = 0; i < *numTypes; i += 1)
    {
      switch(dataTypes[i])
      {
        // these are all maps
        case fileType::InputData:
        case fileType::InputWeights:
        case fileType::WeightedData:
        case fileType::InputNoise:
        case fileType::InputWeightedNoise:
        case fileType::InputFilter:
        case fileType::InputBeam:
        case fileType::PixelizedData:
        case fileType::PixelizedWeights:
        case fileType::WeightedPixel:
        case fileType::PixelizedNoise:
        case fileType::PixelizedWeightedNoise:
        case fileType::PixelizedFilter:
        case fileType::PixelizedBeam:
        case fileType::InverseData:
        case fileType::InverseWeights:
        case fileType::WeightedInverse:
        case fileType::InverseNoise:
        case fileType::InverseWeightedNoise:
        case fileType::InverseFilter:
        case fileType::InverseBeam:
          types[0] = dataTypes[i];
          break;
          // these are all graphs
        case fileType::TransformedData:
        case fileType::TransformedWeights:
        case fileType::WeightedTransform:
        case fileType::TransformedNoise:
        case fileType::TransformedWeightedNoise:
        case fileType::TransformedFilter:
        case fileType::TransformedBeam:
        case fileType::EnsembleAveragedNoise:
        case fileType::EnsembleAveragedSpectrum:
        case fileType::ExtrapolatedSpectrum:
        case fileType::ExtrapolatedInstrumentSpectrum:
        case fileType::BinnedSpectrum:
        case fileType::BinnedExtrapolatedSpectrum:
        case fileType::BinnedExtrapolatedInstrumentedSpectrum:
        //case fileType::EnsembleAveragedBinnedSpectrum:
          types[1] = dataTypes[i];
          break;
      }
    }

    //invert();

    for(fileType type : types)
      configureDisplay(type);

}

void GUIManager::createControlData(FILETYPE dataType, bool complete)
{
    if(s_association->exists(dataType) && s_association->getData(dataType)->current())
	{
		if(replaceDataChain("A data chain currently exists.\nDo you want to replace it?"))
            s_association->discardRelation(dataType);
		else
			displayMessage("You are keeping existing data chain and appending to it.\n");
	}

    CONTROLTYPE dataSet = ctrlDlg->dataPattern();
	double raRes = ctrlDlg->RAResolution();
	double decRes = ctrlDlg->decResolution();
	double strength = ctrlDlg->controlSignalStrength();
	M_OP   op = ctrlDlg->controlOperation();
	double top = ctrlDlg->highDec();
	double bot = ctrlDlg->lowDec();
	double left = ctrlDlg->lowRA();
	double right = ctrlDlg->highRA();
	double peakDec = ctrlDlg->decPeak();
	double peakRA = ctrlDlg->RAPeak();
	double fwhm = ctrlDlg->fullWidthHalfMax();
	double checkRA = ctrlDlg->checkerRAWidth();
	double checkDec = ctrlDlg->checkerDecWidth();
	long l = ctrlDlg->harmonicL();
	long m = ctrlDlg->harmonicM();


    if (!s_association->exists(dataType))
    {
        try
        {
            switch (dataType)
            {
                case fileType::InputData:
                    if (s_association->exists(fileType::InputWeights))
                        s_association->getResolution(fileType::InputWeights, raRes, decRes);
                    break;
                case fileType::InputWeights:
                    if (s_association->exists(fileType::InputData))
                        s_association->getResolution(fileType::InputData, raRes, decRes);
                    break;
                case fileType::InputNoise:
                    if (s_association->exists(fileType::InputData))
                        s_association->getResolution(fileType::InputData, raRes, decRes);
                    else if(s_association->exists(fileType::InputWeights))
                        s_association->getResolution(fileType::InputWeights, raRes, decRes);
                    break;
                case fileType::InputFilter:
                    if (s_association->exists(fileType::InputData))
                        s_association->getResolution(fileType::InputData, raRes, decRes);
                    else if(s_association->exists(fileType::InputWeights))
                        s_association->getResolution(fileType::InputWeights, raRes, decRes);
                    break;
                case fileType::InputBeam:
                    if (s_association->exists(fileType::InputData))
                        s_association->getResolution(fileType::InputData, raRes, decRes);
                    else if(s_association->exists(fileType::InputWeights))
                        s_association->getResolution(fileType::InputWeights, raRes, decRes);
                    break;
            }
        }
        catch(ERRORCODES err)
        {
            errorMessage("An error was encountered getting the resolution");
            return;
        }

        try
        {
            s_association->createEmptyDataSet(dataType,raRes,decRes);
        }
        catch (ERRORCODES error)
        {
            errorMessage("An error was encountered creating the data set");
            return;
        }
    }

    matrixData<double>* current = 0;
    inputMatrixData* workspace = 0;

    try
    {
        if(dataSet == Uniform)
            s_association->createUniformSky(dataType, strength, op);
        else if(dataSet == Regional)
            s_association->createUniformPatch(dataType, top, bot, left, right, strength, op);
        else if(dataSet == Checker)
            s_association->createCheckerboard(dataType, checkRA, checkDec, strength, op);
        else if(dataSet == Delta)
            s_association->createDeltaFunction(dataType, peakRA, peakDec, strength, op);
        else if(dataSet == Gaussian)
            s_association->createGaussian(dataType, peakRA, peakDec, fwhm, strength, op);
        else if(dataSet == Harmonic)
            s_association->createHarmonic(dataType, (int)l, (int)m, strength, op);
        else
            errorMessage("Unknown Control Data Type.");
    }
    catch(ERRORCODES err)
    {
        errorMessage("An error was encountered creating the control data");
        return;
    }

    if(    s_association->exists(fileType::InputData)
        && s_association->exists(fileType::InputWeights))
        s_association->generateWeightedData(fileType::WeightedData);


    if( s_association->exists(fileType::InputNoise) &&
        s_association->exists(fileType::InputWeights) &&
       !s_association->exists(fileType::InputWeightedNoise))
        s_association->generateWeightedData(fileType::InputWeightedNoise);

    configureDisplay(dataType);

    if (complete)
    {
        s_association->getData(dataType)->dataType(dataType);
        s_association->getData(dataType)->current(true);
    }
    else
        ctrlDlg->configured(true);
}

void GUIManager::selectPixelizer()
{
	int count = 0, i = 1;
	PIXELSCHEME pixCount = static_cast<PIXELSCHEME>(i);

	while (i)
	{
		if (pixCount == PIXELIZER_LIMIT)
			break;
		count++;
		pixCount = static_cast <PIXELSCHEME>(++i);
	}

	if (count > 1)
	{
		if (!pixSelectDlg->configured())
			pixSelectDlg->execute();
	}
	else
	{
		if (!healpixDlg->configured())
			healpixDlg->execute();
	}

	return;
}

void GUIManager::configurePixelizer(PIXELSCHEME scheme)
{
	bool error = false;

	switch (scheme)
	{
		case HealPIX:
			healpixDlg->execute();
			break;
		default:
			error = true;
	}

	if (error)
		errorMessage("An invalid pixelization engine was specified.\nPixelization aborted.");
}

void GUIManager::setPixelizerAttr()
{
	switch (s_association->pixelizationEngineType())
	{
		case HealPIX:
			s_association->addEngine(dataEngines::Pixelization, HealPIX);
			s_association->pixelizationEngine()->scale(healpixDlg->scale());

			s_association->pixelizationEngine()->usePixelAvg(healpixDlg->usePixelAvg());
			s_association->pixelizationEngine()->usePixelDev(healpixDlg->usePixelDev());
			s_association->pixelizationEngine()->usePixelVar(healpixDlg->usePixelVar());

			s_association->pixelizationEngine()->doAvgNormalize(healpixDlg->doAvgNormalize());
			s_association->pixelizationEngine()->doVarNormalize(healpixDlg->doVarNormalize());
			s_association->pixelizationEngine()->doMinMaxScale(healpixDlg->doMinMaxScale());

			if (healpixDlg->order())
				s_association->pixelizationEngine()->pixelLayout(Nest);
			else
				s_association->pixelizationEngine()->pixelLayout(Ring);

			s_association->pixelizationEngine()->configured(true);
			break;
		default:
			selectPixelizer();
	}
}

int GUIManager::pixelize()
{
    int count = 0;

    // create the pixelization engine, if it doesn't already exist
    if (!s_association->exists(dataEngines::Pixelization))
        setPixelizerAttr();
    else
    {
        if (s_association->pixelizationEngine()->configured() == false)
        {
            s_association->reset(allTypes::Pixelization);
            setPixelizerAttr();
        }
    }

    // walk through all input data types
    FILETYPE inputChain = fileType::InputData;
    FILETYPE pixelChain = fileType::PixelizedData;
    int type = (int)fileType::InputData;
    int offset = (int)fileType::PixelizedData - (int)fileType::InputData;

    int value = 0;
    while (inputChain <= fileType::InputBeam)
    {
		if(pixelize(inputChain, pixelChain))
			count++;

        inputChain = static_cast<FILETYPE>(++type);
        pixelChain = static_cast<FILETYPE>(offset+type);
        if (pixelChain == fileType::PixelOccupancy)
        {
            offset++;
            pixelChain = static_cast<FILETYPE>(offset+type);
        }
    }

    if(count)
        configureDisplay(fileType::PixelizedData);

    return count;
}

bool GUIManager::pixelize(FILETYPE inputDataType, FILETYPE pixelDataType)
{
    switch(inputDataType)
    {
        case fileType::InputData:
        {
            if (!s_association->exists(fileType::InputData))
            {
                if(!addDataMessage("No data map has been specified.  Do you wish to create or input a data map?"))
					return false;
            }

            if (!s_association->exists(pixelDataType))
				s_association->generatePixelData(s_association->pixelizationEngine(),inputDataType);

            break;
        }
        case fileType::InputWeights:
        {
            if (!s_association->exists(fileType::InputWeights))
            {
                if(!addDataMessage("No mask map has been specified.  Do you wish to create or input a mask map?"))
                    return false;
            }

            if (!s_association->exists(pixelDataType))
				s_association->generatePixelData(s_association->pixelizationEngine(),inputDataType);

            break;
        }
        case fileType::WeightedData:
        {
            if(!s_association->exists(fileType::WeightedData))
            {
                if( s_association->exists(fileType::InputData) &&
                    s_association->exists(fileType::InputWeights))
                {
                    s_association->generateWeightedData(fileType::WeightedData);

					if(!s_association->exists(pixelDataType))
						s_association->generatePixelData(s_association->pixelizationEngine(), inputDataType);
                }
            }

			if(!s_association->exists(fileType::WeightedPixel))
			{
				if (s_association->exists(inputDataType) && !s_association->exists(pixelDataType))
					s_association->generatePixelData(s_association->pixelizationEngine(),inputDataType);

				if(  s_association->exists(fileType::PixelizedData) &&
                     s_association->exists(fileType::PixelizedWeights) &&
					!s_association->exists(fileType::WeightedPixel))
						s_association->generateWeightedData(fileType::WeightedPixel);
			}

			break;
		}
		case fileType::InputWeightedNoise:
		{
			if(!s_association->exists(fileType::InputWeightedNoise))
			{
                if(	s_association->exists(fileType::InputNoise) &&
					s_association->exists(fileType::InputWeights))
				{
					s_association->generateWeightedData(fileType::InputWeightedNoise);

					if(!s_association->exists(pixelDataType))
						s_association->generatePixelData(s_association->pixelizationEngine(), inputDataType);
				}
			}

			if(s_association->exists(inputDataType) && !s_association->exists(pixelDataType))
				s_association->generatePixelData(s_association->pixelizationEngine(), inputDataType);

			if(  s_association->exists(fileType::PixelizedNoise)   &&
				 s_association->exists(fileType::PixelizedWeights) &&
				!s_association->exists(fileType::PixelizedWeightedNoise))
						s_association->generateWeightedData(fileType::WeightedPixel);

			break;
		default:
			if (s_association->exists(inputDataType) && !s_association->exists(pixelDataType))
				s_association->generatePixelData(s_association->pixelizationEngine(),inputDataType);

			break;
        }
    }

    if (s_association->exists(pixelDataType))
        return true;
    else
        return false;
}

bool GUIManager::handleMissingTransformer()
{
	selectTransformer();
	return true;
}

void GUIManager::selectTransformer()
{
	int count = 0, i = 1;
	TRANSFORMERSCHEME transCount = static_cast<TRANSFORMERSCHEME>(i);

	while (i)
	{
		if (transCount == TRANSFORMER_LIMIT)
			break;
		count++;
		transCount = static_cast <TRANSFORMERSCHEME>(++i);
	}

	if (count > 1)
	{
		if (!transSelectDlg->configured())
		transSelectDlg->execute();
	}
	else
	{
		if (!rshtDlg->configured())
		rshtDlg->execute();
	}

	return;
}

void GUIManager::configureTransformer(TRANSFORMERSCHEME scheme)
{
	bool error = false;

	switch (scheme)
	{
		case Rsht:
			rshtDlg->execute();
			break;
		default:
			error = true;
	}

	if (error)
		errorMessage("An invalid transformation engine was specified. \nTransformation aborted.");
}

void GUIManager::setTransformerAttr()
{
	switch (s_association->transformationEngineType())
	{
		case Rsht:
			s_association->addEngine(dataEngines::Transformation, Rsht);
			s_association->transformationEngine()->minIndex(rshtDlg->minimumIndex());
			s_association->transformationEngine()->maxIndex(rshtDlg->maximumIndex());
			s_association->transformationEngine()->iterations(rshtDlg->iterations());
			s_association->transformationEngine()->configured(true);
			break;
		default:
			selectTransformer();
	}
}

int GUIManager::transform()
{
    int count = 0;

    // create transformer engine, if it doesn't already exist
    if (!s_association->exists(dataEngines::Transformation))
        setTransformerAttr();
    else
    {
        if (s_association->transformationEngine()->configured() == false)
        {
            s_association->reset(allTypes::Transformation);
            setTransformerAttr();
        }
    }

    // walk through all of the pixelized data types
    FILETYPE pixelChain = fileType::PixelizedData;
    FILETYPE transChain = fileType::TransformedData;
    int type = (int)fileType::PixelizedData;
    int offset = (int)fileType::TransformedData - (int)fileType::PixelizedData;

    while (pixelChain <= fileType::PixelizedBeam)
    {
        if (!s_association->exists(transChain))
        {
            if (transform(pixelChain,transChain))
                count++;
        }

        pixelChain = static_cast<FILETYPE>(++type);
        if (pixelChain == fileType::PixelOccupancy)
        {
            pixelChain = static_cast<FILETYPE>(++type);
            offset--;
        }

        transChain = static_cast<FILETYPE>(offset+type);
    }

    if(count)
        configureDisplay(fileType::TransformedData);

    return count;
}

bool GUIManager::transform(FILETYPE pixelDataType, FILETYPE transDataType)
{
    if (!s_association->exists(pixelDataType))
    {
        if (!s_association->exists(dataEngines::Pixelization))
            selectPixelizer();

        int offset = (int)fileType::PixelizedData - (int)fileType::InputData;
        FILETYPE inputDataType = fileType::Null;
        if (pixelDataType >= fileType::PixelOccupancy)
            inputDataType = static_cast<FILETYPE>((int)pixelDataType - offset - 1);
        else
            inputDataType = static_cast<FILETYPE>((int)pixelDataType - offset);

        pixelize(inputDataType,pixelDataType);
    }

    switch(pixelDataType)
    {
        case fileType::WeightedPixel:
        {
            if(!s_association->exists(fileType::WeightedPixel))
            {
                if( s_association->exists(fileType::PixelizedData) &&
                    s_association->exists(fileType::PixelizedWeights))
                {
                    s_association->generateWeightedData(fileType::WeightedPixel);

                    if(!s_association->exists(fileType::WeightedPixel))
                        s_association->generatePixelData(s_association->pixelizationEngine(), fileType::WeightedPixel);
                }
            }
            break;
        }
        case fileType::PixelizedWeightedNoise:
        {
            if(!s_association->exists(fileType::PixelizedWeightedNoise))
            {
                if( s_association->exists(fileType::PixelizedNoise) &&
                    s_association->exists(fileType::PixelizedWeights))
                {
                    s_association->generateWeightedData(fileType::PixelizedWeightedNoise);

                    if(!s_association->exists(fileType::PixelizedWeightedNoise))
                        s_association->generatePixelData(s_association->pixelizationEngine(), fileType::PixelizedWeightedNoise);
                }
            }
            break;
        }
        default:
            break;
    }

    if (s_association->exists(pixelDataType) && !s_association->exists(transDataType))
    {
        s_association->generateTransformedData(s_association->transformationEngine(),pixelDataType);
        return true;
    }
    else
        return false;
}

int GUIManager::invert()
{
    int count = 0;

    FILETYPE inverseChain = fileType::InverseData;
    FILETYPE almChain     = fileType::AlmData;

    while(almChain <= fileType::AlmBeam)
    {
        if(invert(inverseChain, almChain))
            count++;

        inverseChain = static_cast<FILETYPE>(static_cast<int>(inverseChain) + 1);
        almChain     = static_cast<FILETYPE>(static_cast<int>(almChain) + 1);
    }

    if(count)
        configureDisplay(fileType::InverseData);

    return count;
}

bool GUIManager::invert(FILETYPE inverseType, FILETYPE almType)
{
    if(!s_association->exists(inverseType) && s_association->exists(almType))
        return s_association->generateInverseData(s_association->transformationEngine(), almType);
    else
        return false;
}

void GUIManager::selectAnalyzer()
{
	if (!specDlg->configured())
		specDlg->execute();
}

void GUIManager::configureAnalyzer()
{
	if(!specDlg->configured())
		specDlg->execute();

}

void GUIManager::setAnalyzerAttr()
{
	s_association->addEngine(dataEngines::PseudoSpectrum);
	s_association->powerSpectraEngine()->binning(specDlg->binSpectrum());
	s_association->powerSpectraEngine()->computeInverse(specDlg->invertTransforms());
	s_association->powerSpectraEngine()->weight(specDlg->weighIndices());
	s_association->powerSpectraEngine()->numLPerBin(specDlg->indicesPerBin());
	s_association->powerSpectraEngine()->maskIndex(specDlg->maskLowestIndices());
	s_association->powerSpectraEngine()->ensembleIterations(specDlg->ensembleIterations());
	s_association->powerSpectraEngine()->configured(true);
}

void GUIManager::analyze()
{
    if (!s_association->exists(dataEngines::PseudoSpectrum))
        setAnalyzerAttr();
    else
    {
        if (s_association->powerSpectraEngine()->configured() == false)
        {
            s_association->reset(allTypes::PseudoSpectrum);
            setAnalyzerAttr();
        }
    }

    // check that all of the transformed data exists
    if (!s_association->exists(fileType::TransformedData))
    {
        if(!s_association->exists(fileType::AlmData))
        {
            if (!s_association->exists(dataEngines::Transformation))
            {
                errorMessage("No Transformation engine.");
                if(!handleMissingTransformer()) return;
            }

            if (!transform(fileType::PixelizedData,fileType::TransformedData))
            {
                errorMessage("No transformed data set is available.\nPlease check your data entries to insure that one has been entered correctly.");
                return;
            }
        }
        else
        {
            // generate transformed data from the alm's
            s_association->generateTransformedDataFromAlm(s_association->transformationEngine(), fileType::AlmData);

            // create the inverse map for use when creating the pseudo spectrum
            s_association->generateInverseData(s_association->transformationEngine(), fileType::AlmData);
        }
    }

    if (!s_association->exists(fileType::TransformedWeights))
    {
        if(!s_association->exists(fileType::AlmWeights))
        {
            if (!s_association->exists(dataEngines::Transformation))
            {
                errorMessage("No Transformation engine exists.");
                if(!handleMissingTransformer()) return;
            }

            if (!transform(fileType::PixelizedWeights,fileType::TransformedWeights))
            {
                errorMessage("No transformed mask set is available.\nPlease check your data entries to insure that one has been entered correctly.");
                return;
            }
        }
        else
        {
            s_association->generateTransformedDataFromAlm(s_association->transformationEngine(), fileType::AlmWeights);
            s_association->generateInverseData(s_association->transformationEngine(), fileType::AlmWeights);
        }
    }

    if (!s_association->exists(fileType::WeightedTransform))
    {
        if(!s_association->exists(fileType::WeightedAlm))
        {
            if( s_association->exists(fileType::PixelizedData) &&
                s_association->exists(fileType::PixelizedWeights))
                s_association->generateWeightedData(fileType::WeightedPixel);

            if (!s_association->exists(dataEngines::Transformation))
            {
                errorMessage("No Transformation engine exists.");
                if(!handleMissingTransformer()) return;
            }

            if (!transform(fileType::WeightedPixel, fileType::WeightedTransform))
            {
                errorMessage("No weighted transformed set is available.\nPlease check your data entries to insure that one has been entered correctly.");
                return;
            }
        }
        else
        {
            s_association->generateTransformedDataFromAlm(s_association->transformationEngine(), fileType::WeightedAlm);
            s_association->generateInverseData(s_association->transformationEngine(), fileType::WeightedAlm);
        }
    }

    if (!s_association->exists(fileType::TransformedNoise))
    {
        if(!s_association->exists(fileType::AlmNoise))
        {
            if (!s_association->exists(dataEngines::Transformation))
            {
                errorMessage("No Transformation engine exists.");
                if(!handleMissingTransformer()) return;
            }

            if (!transform(fileType::PixelizedNoise,fileType::TransformedNoise))
            {
                s_association->merge(fileType::TransformedNoise,s_association->transformedData(),false);
                s_association->transformedNoise()->dataType(fileType::TransformedNoise);

                // fill vector with white noise
                //s_association->createWhiteNoise(s_association->transformedNoise());
                //s_association->createShotNoise(s_association->transformedNoise());

                // this is wrong but the math says to subtract the noise which will give negatives
                int rows = s_association->transformedNoise()->rows();
                s_association->transformedNoise()->rwAccess().assign(rows, 0.0);
            }
        }
        else
        {
            s_association->generateTransformedDataFromAlm(s_association->transformationEngine(), fileType::AlmNoise);
            s_association->generateInverseData(s_association->transformationEngine(), fileType::AlmNoise);
        }
    }

    if (!s_association->exists(fileType::TransformedWeightedNoise))
    {
        if(!s_association->exists(fileType::AlmWeightedNoise))
        {
            if(s_association->exists(fileType::PixelizedNoise) &&
                s_association->exists(fileType::PixelizedWeights))
            {
                s_association->generateWeightedData(fileType::PixelizedWeightedNoise);
            }

            if (!s_association->exists(dataEngines::Transformation))
            {
                errorMessage("No Transformation engine exists.");
                if(!handleMissingTransformer()) return;
            }

            if (!transform(fileType::PixelizedWeightedNoise, fileType::TransformedWeightedNoise))
            {
                s_association->merge(fileType::TransformedWeightedNoise, s_association->transformedData(), false);
                s_association->weightedTransformedNoise()->dataType(fileType::TransformedWeightedNoise);
                int rows = s_association->weightedTransformedNoise()->rows();
                s_association->weightedTransformedNoise()->rwAccess().assign(rows, 0);
            }
        }
        else
        {
            s_association->generateTransformedDataFromAlm(s_association->transformationEngine(), fileType::AlmWeightedNoise);
            s_association->generateInverseData(s_association->transformationEngine(), fileType::AlmWeightedNoise);
        }
    }

    if (!s_association->exists(fileType::TransformedFilter))
    {
        if(!s_association->exists(fileType::AlmFilter))
        {
            if (!s_association->exists(dataEngines::Transformation))
            {
                errorMessage("No Transformation Engine exists.");
                if(!handleMissingTransformer()) return;
            }

            if (!transform(fileType::PixelizedFilter,fileType::TransformedFilter))
            {
                s_association->merge(fileType::TransformedFilter,s_association->transformedData(),false);
                s_association->transformedFilter()->dataType(fileType::TransformedFilter);
                int rows = s_association->transformedFilter()->rows();
                //s_association->transformedFilter()->rwAccess().assign(rows,1.0);
                s_association->transformedFilter()->rwAccess().assign(rows, 1.0);
            }
        }
        else
        {
            s_association->generateTransformedDataFromAlm(s_association->transformationEngine(), fileType::AlmFilter);
            s_association->generateInverseData(s_association->transformationEngine(), fileType::AlmFilter);
        }
    }

    if (!s_association->exists(fileType::TransformedBeam))
    {
        if(!s_association->exists(fileType::AlmBeam))
        {
            if (!s_association->exists(dataEngines::Transformation))
            {
                errorMessage("No Transformation Engine exists.");
                if(!handleMissingTransformer()) return;
            }

            if (!transform(fileType::PixelizedBeam,fileType::TransformedBeam))
            {
                s_association->merge(fileType::TransformedBeam,s_association->transformedData(),false);
                s_association->transformedBeam()->dataType(fileType::TransformedBeam);
                int rows = s_association->transformedData()->rows();
                s_association->transformedBeam()->rwAccess().assign(rows, 1.0);
            }
        }
        else
        {
            s_association->generateTransformedDataFromAlm(s_association->transformationEngine(), fileType::AlmBeam);
            s_association->generateInverseData(s_association->transformationEngine(), fileType::AlmBeam);
        }
    }

    // set the number of ls in the spectra
    s_association->powerSpectraEngine()->maxIndex(s_association->weightedTransform()->rows());

    // everything is here and ready to go, so carry out analysis
    // generatePowerSpectrumData will just do everything including ensembling
    s_association->generatePowerSpectrumData(s_association->powerSpectraEngine());

    configureDisplay(fileType::BinnedExtrapolatedInstrumentedSpectrum);
}

void GUIManager::configureDisplay(FILETYPE dataType)
{
	switch (dataType)
	{
		case fileType::InputData:
		case fileType::InputWeights:
		case fileType::WeightedData:
		case fileType::InputNoise:
		case fileType::InputWeightedNoise:
		case fileType::InputFilter:
		case fileType::InputBeam:
		case fileType::PixelizedData:
		case fileType::PixelizedWeights:
		case fileType::WeightedPixel:
		case fileType::PixelizedNoise:
		case fileType::PixelizedWeightedNoise:
		case fileType::PixelizedFilter:
		case fileType::PixelizedBeam:
		case fileType::PixelOccupancy:
		case fileType::InverseData:
		case fileType::InverseWeights:
		case fileType::WeightedInverse:
		case fileType::InverseNoise:
		case fileType::InverseWeightedNoise:
		case fileType::InverseFilter:
		case fileType::InverseBeam:
			configureMaps();
			break;
		case fileType::TransformedData:
		case fileType::TransformedWeights:
		case fileType::WeightedTransform:
		case fileType::TransformedNoise:
		case fileType::TransformedWeightedNoise:
		case fileType::TransformedFilter:
		case fileType::TransformedBeam:
		case fileType::EnsembleAveragedNoise:
		case fileType::EnsembleAveragedSpectrum:
		case fileType::ExtrapolatedSpectrum:
		case fileType::ExtrapolatedInstrumentSpectrum:
		case fileType::BinnedSpectrum:
		case fileType::BinnedExtrapolatedSpectrum:
		case fileType::BinnedExtrapolatedInstrumentedSpectrum:
			configureGraphs();
			break;
		default:
			break;
	}
}

void GUIManager::setMapperAttr()
{
	if(s_association->exists(dataEngines::Mapping))
		s_association->reset(ALLTYPES::Mapping);

	s_association->addEngine(dataEngines::Mapping, mapperDlg->project());

	s_association->mappingEngine()->layout(mapperDlg->project());

	s_association->mappingEngine()->width(mapperDlg->width());
	s_association->mappingEngine()->height(mapperDlg->height());
	s_association->mappingEngine()->orientation(mapperDlg->orientation());
	s_association->mappingEngine()->colorScheme(mapperDlg->colorScheme());

	s_association->mappingEngine()->raOffset(mapperDlg->RAOffset());
	s_association->mappingEngine()->decOffset(mapperDlg->DECOffset());

	s_association->mappingEngine()->configured(true);
	mapperDlg->configured(true);
}

void GUIManager::configureMaps()
{
	if (!mapperDlg->configured())
		mapperDlg->configure();
	else
		buildMaps();
}

void GUIManager::buildMaps()
{
	setMapperAttr();

	if(!s_association->exists(dataEngines::Mapping))
		s_association->addEngine(dataEngines::Mapping, Mollweide);

	Mapper* mapEng = s_association->mappingEngine();

	int numMaps = 0, displayData = 0;
	FILETYPE dataType = fileType::Null;
	ASSOCIATEDMAP mapType = associatedMap::Null;
	ASSOCIATEDMAP current = associatedMap::Null;
	ALLTYPES   allMapType = allTypes::FILETYPE_LIMIT;
	int type = static_cast<int>(current);
	int assocType = static_cast<int>(mapType);
	int allType = static_cast<int>(allMapType);

	while (type >= 0)
	{
		if (dataType == fileType::Null)
		{
			dataType = static_cast<FILETYPE>(++type);
			mapType = static_cast<ASSOCIATEDMAP>(++assocType);
			allMapType = static_cast<ALLTYPES>(++allType);
			continue;
		}

		if (dataType == fileType::MAP_LIMIT)
			break;

		if (s_association->exists(dataType))
		{
			if(s_association->exists(mapType))
				s_association->reset(allMapType);
			try
			{
				s_association->generateMap(dataType);
			}
			catch (ERRORCODES error)
			{
				errorMessage(string("The attempt to create the map for: "
									+ dataTypeNames[(int)dataType]
									+ " failed with error: "
									+ s_association->errorDetails(error)).c_str());

				return;
			}
			numMaps++;
			displayData += (1 << (type-1));
			current = mapType;
		}

		dataType = static_cast<FILETYPE>(++type);
		mapType = static_cast<ASSOCIATEDMAP>(++assocType);
		allMapType = static_cast<ALLTYPES>(++allType);
	}

	if (numMaps)
	{
		if (numMaps > 1)
			emitSelectMapDisplay(displayData);
		else
			displayMap(current);
	}
}

void GUIManager::displayMap(ASSOCIATEDMAP map)
{
	activeMap = 0;

	switch (map)
	{
		case associatedMap::InputDataMap:
			activeMap = s_association->inputDataMap()->transferRGBData(fontSize);
			break;
		case associatedMap::InputWeightsMap:
			activeMap = s_association->inputWeightsMap()->transferRGBData(fontSize);
			break;
		case associatedMap::WeightedDataMap:
			activeMap = s_association->inputMap()->transferRGBData(fontSize);
			break;
		case associatedMap::InputNoiseMap:
			activeMap = s_association->inputNoiseMap()->transferRGBData(fontSize);
			break;
		case associatedMap::InputWeightedNoiseMap:
			activeMap = s_association->weightedNoiseMap()->transferRGBData(fontSize);
			break;
		case associatedMap::InputFilterMap:
			activeMap = s_association->inputFilterMap()->transferRGBData(fontSize);
			break;
		case associatedMap::InputBeamMap:
			activeMap = s_association->inputBeamMap()->transferRGBData(fontSize);
			break;

		case associatedMap::PixelizedDataMap:
			activeMap = s_association->pixelDataMap()->transferRGBData(fontSize);
			break;
		case associatedMap::PixelizedWeightsMap:
			activeMap = s_association->pixelWeightsMap()->transferRGBData(fontSize);
			break;
		case associatedMap::WeightedPixelMap:
			activeMap = s_association->pixelMap()->transferRGBData(fontSize);
			break;
		case associatedMap::PixelOccupancyMap:
			activeMap = s_association->pixelOccupancyMap()->transferRGBData(fontSize);
			break;
		case associatedMap::PixelizedNoiseMap:
			activeMap = s_association->pixelNoiseMap()->transferRGBData(fontSize);
			break;
		case associatedMap::PixelizedWeightedNoiseMap:
			activeMap = s_association->pixelWeightedNoiseMap()->transferRGBData(fontSize);
			break;
		case associatedMap::PixelizedFilterMap:
			activeMap = s_association->pixelFilterMap()->transferRGBData(fontSize);
			break;
		case associatedMap::PixelizedBeamMap:
			activeMap = s_association->pixelBeamMap()->transferRGBData(fontSize);
			break;

		case associatedMap::InverseDataMap:
			activeMap = s_association->invDataMap()->transferRGBData(fontSize);
			break;
		case associatedMap::InverseWeightsMap:
			activeMap = s_association->invWeightsMap()->transferRGBData(fontSize);
			break;
		case associatedMap::WeightedInverseMap:
			activeMap = s_association->invMap()->transferRGBData(fontSize);
			break;
		case associatedMap::InverseNoiseMap:
			activeMap = s_association->invNoiseMap()->transferRGBData(fontSize);
			break;
		case associatedMap::InverseWeightedNoiseMap:
			activeMap = s_association->invWeightedNoiseMap()->transferRGBData(fontSize);
			break;
		case associatedMap::InverseFilterMap:
			activeMap = s_association->invFilterMap()->transferRGBData(fontSize);
			break;
		case associatedMap::InverseBeamMap:
			activeMap = s_association->invBeamMap()->transferRGBData(fontSize);
			break;
		default:
			activeMap = 0;
	}

	if (activeMap == 0)
	{
		errorMessage(string("The attempt to create the map for: "
									+ dataTypeNames[(int)map]
									+ " failed with error: "
									+ s_association->errorDetails(noDatamapError)).c_str());
	}

	paintMap(activeMap);
}

void GUIManager::setGrapherAttr()
{
	if(s_association->exists(dataEngines::Graphing))
		s_association->reset(ALLTYPES::Graphing);

	s_association->addEngine(dataEngines::Graphing);

	s_association->graphingEngine()->width(grapherDlg->width());
	s_association->graphingEngine()->height(grapherDlg->height());
	s_association->graphingEngine()->loglogScale(grapherDlg->logLogScale());
	s_association->graphingEngine()->configured(true);

	grapherDlg->configured(true);
}

void GUIManager::configureGraphs()
{
	if (!grapherDlg->configured())
		grapherDlg->configure();
	else
		buildGraphs();
}

void GUIManager::buildGraphs()
{
	setGrapherAttr();

	if (!s_association->exists(dataEngines::Graphing))
		s_association->addEngine(dataEngines::Graphing);

	Grapher* graphEng = s_association->graphingEngine();

	int numGraphs = 0, displayData = 0;
	FILETYPE dataType = fileType::MAP_LIMIT;
	ASSOCIATEDSPECTRUM graphType = associatedSpectrum::Null;
	ASSOCIATEDSPECTRUM current = associatedSpectrum::Null;
	ALLTYPES allGraphType = allTypes::ASSOCIATEMAP_LIMIT;
	int type = static_cast<int>(current);
	int assocType = static_cast<int>(graphType);
	int allType = static_cast<int>(allGraphType);

	while (type >= (int)fileType::MAP_LIMIT)
	{
		if (dataType == fileType::MAP_LIMIT)
		{
			dataType = static_cast<FILETYPE>(++type);
			graphType = static_cast<ASSOCIATEDSPECTRUM>(++assocType);
			allGraphType = static_cast<ALLTYPES>(++allType);
			continue;
		}

		if (dataType == fileType::GRAPH_LIMIT)
			break;

		if (s_association->exists(dataType))
		{
			if (s_association->exists(graphType))
				s_association->reset(allGraphType);

			try
			{
				s_association->generateGraph(dataType);
			}
			catch (ERRORCODES error)
			{
				errorMessage(string("The attempt to create the map for: "
									+ dataTypeNames[(int)dataType]
									+ " failed with error: "
									+ s_association->errorDetails(error)).c_str());

				return;
			}

			numGraphs++;
			displayData += (1 << (type-1));
			current = graphType;
		}

		dataType = static_cast<FILETYPE>(++type);
		graphType = static_cast<ASSOCIATEDSPECTRUM>(++assocType);
		allGraphType = static_cast<ALLTYPES>(++allType);
	}

	if (numGraphs)
	{
		if (numGraphs > 1)
			emitSelectGraphDisplay(displayData);
		else
			displayGraph(current);
	}
}

void GUIManager::displayGraph(ASSOCIATEDSPECTRUM graph)
{
	activeGraph = 0;

	switch (graph)
	{
		case associatedSpectrum::TransformedDataSpectrum:
			activeGraph = s_association->transDataGraph()->transferRGBData();
			break;
		case associatedSpectrum::TransformedWeightsSpectrum:
			activeGraph = s_association->transWeightsGraph()->transferRGBData();
			break;
		case associatedSpectrum::WeightedTransformSpectrum:
			activeGraph = s_association->transGraph()->transferRGBData();
			break;
		case associatedSpectrum::TransformedNoiseSpectrum:
			activeGraph = s_association->transNoiseGraph()->transferRGBData();
			break;
		case associatedSpectrum::TransformedWeightedNoiseSpectrum:
			activeGraph = s_association->transWeightedNoiseGraph()->transferRGBData();
			break;
		case associatedSpectrum::TransformedFilterSpectrum:
			activeGraph = s_association->transFilterGraph()->transferRGBData();
			break;
		case associatedSpectrum::TransformedBeamSpectrum:
			activeGraph = s_association->transBeamGraph()->transferRGBData();
			break;
		case associatedSpectrum::EnsembleAveragedNoiseSpectrum:
			activeGraph = s_association->EnsembleAveragedNoiseGraph()->transferRGBData();
			break;
		case associatedSpectrum::EnsembleAveragedSpectrumSpectrum:
			activeGraph = s_association->EnsembleAveragedSpectrumGraph()->transferRGBData();
			break;
		case associatedSpectrum::ExtrapolatedSpectrumSpectrum:
			activeGraph = s_association->ExtrapolatedSpectrumGraph()->transferRGBData();
			break;
		case associatedSpectrum::ExtrapolatedInstrumentSpectrumSpectrum:
			activeGraph = s_association->ExtrapolatedInstrumentSpectrumGraph()->transferRGBData();
			break;
		case associatedSpectrum::BinnedSpectrumSpectrum:
			activeGraph = s_association->BinnedSpectrumGraph()->transferRGBData();
			break;
		case associatedSpectrum::BinnedExtrapolatedSpectrumSpectrum:
			activeGraph = s_association->BinnedExtrapolatedSpectrumGraph()->transferRGBData();
			break;
		case associatedSpectrum::BinnedExtrapolatedInstrumentedSpectrumSpectrum:
			activeGraph = s_association->BinnedExtrapolatedInstrumentSpectrumGraph()->transferRGBData();
			break;
		default:
			activeGraph = 0;
			break;
	}

	if (activeGraph == 0)
	{
		errorMessage(string("The attempt to create the map for: "
									+ dataTypeNames[(int)graph]
									+ " failed with error: "
									+ s_association->errorDetails(noDatagraphError)).c_str());
		return;
	}

	paintGraph(activeGraph);
}
