/***************************************************************************
 *   GUIManager.h                                                          *
 *   Copyright (C) 2014 by Daniel Suson                                    *
 *   suson@calumet.purdue.edu                                              *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU General Public License     *
 *   along with this program; if not, write to the                         *
 *   Free Software Foundation, Inc.,                                       *
 *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
 *                                                                         *
 *   In addition, as a special exception, the copyright holders give       *
 *   permission to link the code of this program with any edition of       *
 *   the Qt library by Trolltech AS, Norway (or with modified versions     *
 *   of Qt that use the same license as Qt), and distribute linked         *
 *   combinations including the two.  You must obey the GNU General        *
 *   Public License in all respects for all of the code used other than    *
 *   Qt.  If you modify this file, you may extend this exception to        *
 *   your version of the file, but you are not obligated to do so.  If     *
 *   you do not wish to do so, delete this exception statement from        *
 *   your version.                                                         *
 ***************************************************************************
 * Description:                                                            *
 *                                                                         *
 * This class defines the gui structure                                    *
 * ----------------------- Change Log ------------------------------------ *
 * Date    Name         Description                                        *
 *                                                                         *
 ***************************************************************************
 * This software evolved from work that was done by Eric Hivon at the      *
 * California Institute of Technology on the MASTER algorithm (Hivon, E.,  *
 * et al., ApJ, vol 567, p 2).  It adapts or interfaces with these         *
 * packages:                                                               *
 *                                                                         *
 * HealPix         (http://www.eso.org/science/healpix/)                   *
 * FTOOLS & FITSIO (http://heasarc.gsfc.nasa.gov/docs/corp/software.html)  *
 *                                                                         *
 * Any publications or presentations that use results generated by this    *
 * program must reference the fact that it was developed by Daniel Suson   *
 ***************************************************************************/
#ifndef _GUIMANAGER_H_
#define _GUIMANAGER_H_

#include "../libanalyzer/atypes.h"
#include "../libanalyzer/association.h"
#include "../libanalyzer/filemanager.h"
#include "../libanalyzer/pixelizer.h"
#include "../libanalyzer/transformer.h"
#include "../libanalyzer/spectrum.h"

#include "analyzerdlgpar.h"
#include "associationselectdlgpar.h"
#include "controldatadlgpar.h"
#include "dataselectdlgpar.h"
#include "energydlgpar.h"
#include "healpixdlgpar.h"
#include "multipleselectiondlgpar.h"
#include "pixelizerdlgpar.h"
#include "rshtdlgpar.h"
#include "spectrumdlgpar.h"
#include "transformerdlgpar.h"

#include "mapperdlgpar.h"
#include "mapselectdlgpar.h"
#include "graphdlgpar.h"
#include "graphselectdlgpar.h"

class GUIManager
{
    public:
        GUIManager(int fSize);
        virtual ~GUIManager();

        virtual void updateProgressBar(int value)               = 0;
        virtual void updateProgressText(const char* updateName) = 0;
        virtual void errorMessage(const char* errMess)          = 0;

        virtual void displayMessage(const char* mess)           = 0;
        virtual bool addDataMessage(const char* errMess)        = 0;
        virtual bool replaceDataChain(const char* mess)         = 0;

        void addAssociation();
        void setAssociation(association* newAssoc);

        virtual bool selectFileName(bool read) = 0;

        virtual void emitReadDataSets(FILETYPE* dataTypes, int* numTypes) = 0;
        virtual void emitSelectSlices() = 0;
        virtual void emitSelectEnergies() = 0;
        void readData(int numTypes, FILETYPE dataTypes[]);
        void openFile();

        virtual void emitSaveDataSets() = 0;
        void writeData(int numTypes, FILETYPE dataTypes[]);
        void saveFile();

        void createControlData(FILETYPE dataType, bool complete);

        void setPixelizerAttr();
        int pixelize();
        bool pixelize(FILETYPE inputDataType, FILETYPE pixelDataType);

		bool handleMissingTransformer();
        void setTransformerAttr();
        int transform();
        bool transform(FILETYPE pixelDataType, FILETYPE transDataType);

        int invert();
        bool invert(FILETYPE inverseType, FILETYPE almType);

        void setAnalyzerAttr();
        void analyze();

        virtual void selectPixelizer() = 0;
        virtual void configurePixelizer(PIXELSCHEME scheme) = 0;

        virtual void selectTransformer() = 0;
        virtual void configureTransformer(TRANSFORMERSCHEME scheme) = 0;

        virtual void selectAnalzyer() = 0;
        virtual void configureAnalyzer() = 0;

        virtual void configureDisplay(FILETYPE dataType);

		void setMapperAttr();
		void configureMaps();
		void buildMaps();
		void displayMap(ASSOCIATEDMAP map);
		virtual void clearMaps() = 0;
		virtual void emitSelectMapDisplay(int displayData) = 0;

		void setGrapherAttr();
		void configureGraphs();
		void buildGraphs();
		void displayGraph(ASSOCIATEDSPECTRUM graph);
		virtual void clearGraphs() = 0;
		virtual void emitSelectGraphDisplay(int displayData) = 0;

		virtual void paintMap(unsigned char* map) = 0;
		virtual void paintGraph(unsigned char* graph) = 0;


    protected:
        association               *s_association;
        std::vector<association*> *associationVector;
        FILETYPE                   selectedDataType;
        GENERICTYPE                selectedDataStream;
        FORMAT                     dataFormat;
        std::string                fileName;
        OBSERVATORY                dataSource;

		const int 				   fontSize;
		unsigned char             *activeMap;
		unsigned char             *activeGraph;

        associationSelectDialogParent *assocDlg;
        controlDataDialogParent       *ctrlDlg;
        dataSelectDialogParent        *dataSelectDlg;
        energyDialogParent            *energyDlg;
        multipleSelectionDialogParent *multSelDlg;
        pixelizerDialogParent         *pixSelectDlg;
        healpixDialogParent           *healpixDlg;
        transformerDialogParent       *transSelectDlg;
        rshtDialogParent              *rshtDlg;
        analyzerDialogParent          *analSelectDlg;
        spectrumDialogParent          *specDlg;

		mapperDialogParent            *mapperDlg;
		mapSelectDialogParent         *mapSelectDlg;
		graphDialogParent             *grapherDlg;
		graphSelectDialogParent       *graphSelectDlg;

};
#endif


