/***************************************************************************
 *   GUIManager.cpp                                                        *
 *   Copyright (C) 2014 by Daniel Suson                                    *
 *   suson@calumet.purdue.edu                                              *
 *                                                                         *
 *   This program is free software{} you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation{} either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY{} without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU General Public License     *
 *   along with this program{} if not, write to the                         *
 *   Free Software Foundation, Inc.,                                       *
 *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
 *                                                                         *
 *   In addition, as a special exception, the copyright holders give       *
 *   permission to link the code of this program with any edition of       *
 *   the Qt library by Trolltech AS, Norway (or with modified versions     *
 *   of Qt that use the same license as Qt), and distribute linked         *
 *   combinations including the two.  You must obey the GNU General        *
 *   Public License in all respects for all of the code used other than    *
 *   Qt.  If you modify this file, you may extend this exception to        *
 *   your version of the file, but you are not obligated to do so.  If     *
 *   you do not wish to do so, delete this exception statement from        *
 *   your version.                                                         *
 ***************************************************************************
 * Description:                                                            *
 *                                                                         *
 * This class defines the gui structure                                    *
 * ----------------------- Change Log ------------------------------------ *
 * Date    Name         Description                                        *
 *                                                                         *
 ***************************************************************************
 * This software evolved from work that was done by Eric Hivon at the      *
 * California Institute of Technology on the MASTER algorithm (Hivon, E.,  *
 * et al., ApJ, vol 567, p 2).  It adapts or interfaces with these         *
 * packages:                                                               *
 *                                                                         *
 * HealPix         (http://www.eso.org/science/healpix/)                   *
 * FTOOLS & FITSIO (http://heasarc.gsfc.nasa.gov/docs/corp/software.html)  *
 *                                                                         *
 * Any publications or presentations that use results generated by this    *
 * program must reference the fact that it was developed by Daniel Suson   *
 ***************************************************************************/

#include "GUIManager.h"

GUIManager::GUIManager()
{
    dataSource = OBSERVATORY::Analyzer;
    fileName = "";
    dataFormat = FORMAT::None;
}

GUIManager::~GUIManager()
{
    for(association* s : (*associationVector))
        delete s;

    delete associationVector;
}

void GUIManager::progressBarWrapper(void* ui, int value)
{}

void GUIManager::progressTextWrapper(void* ui, const char* updateName)
{}

void GUIManager::errorMessageWrapper(void* ui, const char* errMess)
{}

void GUIManager::writeData(int numTypes, FILETYPE dataTypes[])
{
    try
    {
        s_association->fileIOEngine()->saveBase(fileName.c_str(), &numTypes, dataTypes);
        s_association->fileIOEngine()->save(&numTypes, dataTypes);
    }
    catch(ERRORCODES error)
    {
        errorMessage(s_association->errorDetails().c_str());
    }
}

void GUIManager::saveFile()
{
    selectFileName(false);

    if (s_association->exists(dataEngines::fileIO))
        s_association->reset(allTypes::fileIO);
    s_association->addEngine(dataEngines::fileIO, fileName.c_str(), dataFormat, selectedDataType, Write);

    emitSaveDataSets();

    displayMessage("Save Successfull.");
}

void GUIManager::readData(int numTypes, FILETYPE dataTypes[])
{
    try
    {
        if (s_association->fileIOEngine()->slices() > 1)
        {
            if(dataSource == Fermi || dataSource == Egret)
            {
                emitSelectSlices();

                s_association->fileIOEngine()->open(&numTypes, dataTypes);
            }
            else
                emitSelectEnergies();
        }
        else
            s_association->fileIOEngine()->open(&numTypes, dataTypes);
    }
    catch (ERRORCODES error)
    {
        errorMessage((s_association->errorDetails().c_str()));
    }
}

void GUIManager::openFile()
{
    selectFileName(true);
    if (s_association->exists(dataEngines::fileIO))
        s_association->reset(allTypes::fileIO);

    s_association->addEngine(dataEngines::fileIO, fileName.c_str(), dataFormat, selectedDataType, Read);
    s_association->fileIOEngine()->observatory(dataSource);

    int* numTypes = new int(0);
    FILETYPE* dataTypes = s_association->fileIOEngine()->getHeaders(numTypes);

    emitReadDataSets(dataTypes, numTypes);

    // this vector represents whether
    // we have to map or graph or both
    std::vector<FILETYPE> types(2);
    types.assign(2, fileType::Null);

    for(int i = 0; i < *numTypes; i += 1)
    {
      switch(dataTypes[i])
      {
        // these are all maps
        case fileType::InputData:
        case fileType::InputWeights:
        case fileType::WeightedData:
        case fileType::InputNoise:
        case fileType::InputWeightedNoise:
        case fileType::InputFilter:
        case fileType::InputBeam:
        case fileType::PixelizedData:
        case fileType::PixelizedWeights:
        case fileType::WeightedPixel:
        case fileType::PixelizedNoise:
        case fileType::PixelizedWeightedNoise:
        case fileType::PixelizedFilter:
        case fileType::PixelizedBeam:
        case fileType::InverseData:
        case fileType::InverseWeights:
        case fileType::WeightedInverse:
        case fileType::InverseNoise:
        case fileType::InverseWeightedNoise:
        case fileType::InverseFilter:
        case fileType::InverseBeam:
          types[0] = dataTypes[i];
          break;
          // these are all graphs
        case fileType::TransformedData:
        case fileType::TransformedWeights:
        case fileType::WeightedTransform:
        case fileType::TransformedNoise:
        case fileType::TransformedWeightedNoise:
        case fileType::TransformedFilter:
        case fileType::TransformedBeam:
        case fileType::EnsembleAveragedNoise:
        case fileType::EnsembleAveragedSpectrum:
        case fileType::ExtrapolatedSpectrum:
        case fileType::ExtrapolatedInstrumentSpectrum:
        case fileType::BinnedSpectrum:
        case fileType::BinnedExtrapolatedSpectrum:
        case fileType::BinnedExtrapolatedInstrumentedSpectrum:
        //case fileType::EnsembleAveragedBinnedSpectrum:
          types[1] = dataTypes[i];
          break;
      }
    }

    invert();

    for(fileType type : types)
      configureDisplay(type);

}

void GUIManager::createControlData(FILETYPE dataType, bool complete)
{
    if(s_association->exists(dataType) && s_association->getData(dataType)->current())
        if(replaceDataChain("A data chain currently exists.\n Do you want to replace it?"))
            s_association->discardRelation(dataType);

    CONTROLTYPE dataSet;
    M_OP op;
    double strength;
    double raRes, decRes;
    double top, bot;
    double left, right;
    double peakDec, peakRA, fwhm;
    double checkRA, checkDec;
    long l, m;

    getControlDataAttr(&dataSet, &strength, &op,
                       &raRes, &decRes,
                       &top, &bot,
                       &left, &right,
                       &peakDec, &peakRA, &fwhm,
                       &checkRA, &checkDec,
                       &l, &m);

    if (!s_association->exists(dataType))
    {
        try
        {
            switch (dataType)
            {
                case fileType::InputData:
                    if (s_association->exists(fileType::InputWeights))
                        s_association->getResolution(fileType::InputWeights, raRes, decRes);
                    break;
                case fileType::InputWeights:
                    if (s_association->exists(fileType::InputData))
                        s_association->getResolution(fileType::InputData, raRes, decRes);
                    break;
                case fileType::InputNoise:
                    if (s_association->exists(fileType::InputData))
                        s_association->getResolution(fileType::InputData, raRes, decRes);
                    else if(s_association->exists(fileType::InputWeights))
                        s_association->getResolution(fileType::InputWeights, raRes, decRes);
                    break;
                case fileType::InputFilter:
                    if (s_association->exists(fileType::InputData))
                        s_association->getResolution(fileType::InputData, raRes, decRes);
                    else if(s_association->exists(fileType::InputWeights))
                        s_association->getResolution(fileType::InputWeights, raRes, decRes);
                    break;
                case fileType::InputBeam:
                    if (s_association->exists(fileType::InputData))
                        s_association->getResolution(fileType::InputData, raRes, decRes);
                    else if(s_association->exists(fileType::InputWeights))
                        s_association->getResolution(fileType::InputWeights, raRes, decRes);
                    break;
            }
        }
        catch(ERRORCODES err)
        {
            errorMessage("An error was encountered getting the resolution");
            return;
        }

        try
        {
            s_association->createEmptyDataSet(dataType,raRes,decRes);
        }
        catch (ERRORCODES error)
        {
            errorMessage("An error was encountered creating the data set");
            return;
        }
    }

    matrixData<double>* current = 0;
    inputMatrixData* workspace = 0;

    try
    {
        if(dataSet == Uniform)
            s_association->createUniformSky(dataType, strength, op);
        else if(dataSet == Regional)
            s_association->createUniformPatch(dataType, top, bot, left, right, strength, op);
        else if(dataSet == Checker)
            s_association->createCheckerboard(dataType, checkRA, checkDec, strength, op);
        else if(dataSet == Delta)
            s_association->createDeltaFunction(dataType, peakRA, peakDec, strength, op);
        else if(dataSet == Gaussian)
            s_association->createGaussian(dataType, peakRA, peakDec, fwhm, strength, op);
        else if(dataSet == Harmonic)
            s_association->createHarmonic(dataType, (int)l, (int)m, strength, op);
        else
            errorMessage("Unknown Control Data Type.");
    }
    catch(ERRORCODES err)
    {
        errorMessage("An error was encountered creating the control data");
        return;
    }

    if(    s_association->exists(fileType::InputData)
        && s_association->exists(fileType::InputWeights))
        s_association->generateWeightedData(fileType::WeightedData);


    if( s_association->exists(fileType::InputNoise) &&
        s_association->exists(fileType::InputWeights) &&
       !s_association->exists(fileType::InputWeightedNoise))
        s_association->generateWeightedData(fileType::InputWeightedNoise);

    configureDisplay(dataType);

    if (complete)
    {
        s_association->getData(dataType)->dataType(dataType);
        s_association->getData(dataType)->current(true);
    }
    else
        setControlDlgConfigured(true);
}

int GUIManager::pixelize()
{
    int count = 0;

    // create the pixelization engine, if it doesn't already exist
    if (!s_association->exists(dataEngines::Pixelization))
        setPixelizerAttr();
    else
    {
        if (s_association->pixelizationEngine()->configured() == false)
        {
            s_association->reset(allTypes::Pixelization);
            setPixelizerAttr();
        }
    }

    // walk through all input data types
    FILETYPE inputChain = fileType::InputData;
    FILETYPE pixelChain = fileType::PixelizedData;
    int type = (int)fileType::InputData;
    int offset = (int)fileType::PixelizedData - (int)fileType::InputData;

    int value = 0;
    while (inputChain <= fileType::InputBeam)
    {
        if (s_association->exists(inputChain) && !s_association->exists(pixelChain))
        {
            if (pixelize(inputChain,pixelChain))
                count++;
        }
        // have to account for possibly starting with a file that
        // doesn't contain weighted data but we do have weights and data
        // so we can generate weighted pixel
        else if(pixelChain == fileType::WeightedPixel)
        {
            if(s_association->exists(fileType::PixelizedData) &&
                s_association->exists(fileType::PixelizedWeights))
            {
                if(pixelize(inputChain, pixelChain))
                count++;
            }
        }
        else if(pixelChain == fileType::PixelizedWeightedNoise)
        {
            if(s_association->exists(fileType::PixelizedNoise) &&
                s_association->exists(fileType::PixelizedWeights))
            {
                if(pixelize(inputChain, pixelChain))
                count++;
            }
        }

        inputChain = static_cast<FILETYPE>(++type);
        pixelChain = static_cast<FILETYPE>(offset+type);
        if (pixelChain == fileType::PixelOccupancy)
        {
            offset++;
            pixelChain = static_cast<FILETYPE>(offset+type);
        }
    }

    if(s_association->exists(fileType::PixelizedData) &&
        s_association->exists(fileType::PixelizedWeights) )
        //!s_association->exists(fileType::InputWeightedNoise))
        s_association->generateWeightedData(fileType::WeightedPixel);

    if(s_association->exists(fileType::PixelizedNoise) &&
        s_association->exists(fileType::PixelizedWeights) )
        //!s_association->exists(fileType::InputWeightedNoise))
        s_association->generateWeightedData(fileType::PixelizedWeightedNoise);

    if(count)
        configureDisplay(fileType::PixelizedData);

    return count;
}

bool GUIManager::pixelize(FILETYPE inputDataType, FILETYPE pixelDataType)
{
    switch(inputDataType)
    {
        case fileType::InputData:
        {
            if (!s_association->exists(fileType::InputData))
            {
                if(!addDataMessage("No data map has been specified.  Do you wish to create or input a data map?"))
                return false;
            }
            else {
                if (!s_association->exists(pixelDataType))
                    s_association->generatePixelData(s_association->pixelizationEngine(),inputDataType);
            }
            break;
        }
        case fileType::InputWeights:
        {
            if (!s_association->exists(fileType::InputWeights))
            {
                if(!addDataMessage("No mask map has been specified.  Do you wish to create or input a mask map?"))
                    return false;
            }
            else {
                if (!s_association->exists(pixelDataType))
                    s_association->generatePixelData(s_association->pixelizationEngine(),inputDataType);
            }
            break;
        }
        case fileType::WeightedData:
        {
            if(!s_association->exists(fileType::WeightedData))
            {
                if( s_association->exists(fileType::InputData) &&
                    s_association->exists(fileType::InputWeights))
                {
                    s_association->generateWeightedData(fileType::WeightedData);

                if(!s_association->exists(pixelDataType))
                    s_association->generatePixelData(s_association->pixelizationEngine(), inputDataType);
                }
            }

            if(!s_association->exists(fileType::WeightedPixel))
            {
                if (s_association->exists(inputDataType) && !s_association->exists(pixelDataType))
                    s_association->generatePixelData(s_association->pixelizationEngine(),inputDataType);

                if( s_association->exists(fileType::PixelizedData) &&
                    s_association->exists(fileType::PixelizedWeights) &&
                !s_association->exists(fileType::WeightedPixel))
                s_association->generateWeightedData(fileType::WeightedPixel);
            }

            break;
        }
        case fileType::InputWeightedNoise:
        {
            if(!s_association->exists(fileType::InputWeightedNoise))
            {
                if(s_association->exists(fileType::InputNoise) &&
                s_association->exists(fileType::InputWeights))
                {
                s_association->generateWeightedData(fileType::InputWeightedNoise);

                if(!s_association->exists(pixelDataType))
                    s_association->generatePixelData(s_association->pixelizationEngine(), inputDataType);
                }
            }

            if(s_association->exists(inputDataType) && !s_association->exists(pixelDataType))
                s_association->generatePixelData(s_association->pixelizationEngine(), inputDataType);
            break;
            default:
            if (s_association->exists(inputDataType) && !s_association->exists(pixelDataType))
                s_association->generatePixelData(s_association->pixelizationEngine(),inputDataType);
            break;
        }
    }

    if (s_association->exists(pixelDataType))
        return true;
    else
        return false;
}

int GUIManager::transform()
{
    int count = 0;

    // create transformer engine, if it doesn't already exist
    if (!s_association->exists(dataEngines::Transformation))
        setTransformerAttr();
    else
    {
        if (s_association->transformationEngine()->configured() == false)
        {
            s_association->reset(allTypes::Transformation);
            setTransformerAttr();
        }
    }

    // walk through all of the pixelized data types
    FILETYPE pixelChain = fileType::PixelizedData;
    FILETYPE transChain = fileType::TransformedData;
    int type = (int)fileType::PixelizedData;
    int offset = (int)fileType::TransformedData - (int)fileType::PixelizedData;

    while (pixelChain <= fileType::PixelizedBeam)
    {
        if (!s_association->exists(transChain))
        {
            if (transform(pixelChain,transChain))
                count++;
        }

        pixelChain = static_cast<FILETYPE>(++type);
        if (pixelChain == fileType::PixelOccupancy)
        {
            pixelChain = static_cast<FILETYPE>(++type);
            offset--;
        }

        transChain = static_cast<FILETYPE>(offset+type);
    }

    if(count)
        configureDisplay(fileType::TransformedData);

    return count;
}

bool GUIManager::transform(FILETYPE pixelDataType, FILETYPE transDataType)
{
    if (!s_association->exists(pixelDataType))
    {
        if (!s_association->exists(dataEngines::Pixelization))
            selectPixelizer();

        int offset = (int)fileType::PixelizedData - (int)fileType::InputData;
        FILETYPE inputDataType = fileType::Null;
        if (pixelDataType >= fileType::PixelOccupancy)
            inputDataType = static_cast<FILETYPE>((int)pixelDataType - offset - 1);
        else
            inputDataType = static_cast<FILETYPE>((int)pixelDataType - offset);

        pixelize(inputDataType,pixelDataType);
    }

    switch(pixelDataType)
    {
        case fileType::WeightedPixel:
        {
            if(!s_association->exists(fileType::WeightedPixel))
            {
                if( s_association->exists(fileType::PixelizedData) &&
                    s_association->exists(fileType::PixelizedWeights))
                {
                    s_association->generateWeightedData(fileType::WeightedPixel);

                    if(!s_association->exists(fileType::WeightedPixel))
                        s_association->generatePixelData(s_association->pixelizationEngine(), fileType::WeightedPixel);
                }
            }
            break;
        }
        case fileType::PixelizedWeightedNoise:
        {
            if(!s_association->exists(fileType::PixelizedWeightedNoise))
            {
                if( s_association->exists(fileType::PixelizedNoise) &&
                    s_association->exists(fileType::PixelizedWeights))
                {
                    s_association->generateWeightedData(fileType::PixelizedWeightedNoise);

                    if(!s_association->exists(fileType::PixelizedWeightedNoise))
                        s_association->generatePixelData(s_association->pixelizationEngine(), fileType::PixelizedWeightedNoise);
                }
            }
            break;
        }
        default:
            break;
    }

    if (s_association->exists(pixelDataType) && !s_association->exists(transDataType))
    {
        s_association->generateTransformedData(s_association->transformationEngine(),pixelDataType);
        return true;
    }
    else
        return false;
}

int GUIManager::invert()
{
    int count = 0;

    FILETYPE inverseChain = fileType::InverseData;
    FILETYPE almChain     = fileType::AlmData;

    while(almChain <= fileType::AlmBeam)
    {
        if(invert(inverseChain, almChain))
            count++;

        inverseChain = static_cast<FILETYPE>(static_cast<int>(inverseChain) + 1);
        almChain     = static_cast<FILETYPE>(static_cast<int>(almChain) + 1);
    }

    if(count)
        configureDisplay(fileType::InverseData);

    return count;
}

bool GUIManager::invert(FILETYPE inverseType, FILETYPE almType)
{
    if(!s_association->exists(inverseType) && s_association->exists(almType))
        return s_association->generateInverseData(s_association->transformationEngine(), almType);
    else
        return false;
}

void GUIManager::analyze()
{
    if (!s_association->exists(dataEngines::PseudoSpectrum))
        setAnalyzerAttr();
    else
    {
        if (s_association->powerSpectraEngine()->configured() == false)
        {
            s_association->reset(allTypes::PseudoSpectrum);
            setAnalyzerAttr();
        }
    }

    // check that all of the transformed data exists
    if (!s_association->exists(fileType::TransformedData))
    {
        if(!s_association->exists(fileType::AlmData))
        {
            if (!s_association->exists(dataEngines::Transformation))
            {
                errorMessage("No Transformation engine.");
                if(!handleMissingTransformer()) return;
            }

            if (!transform(fileType::PixelizedData,fileType::TransformedData))
            {
                errorMessage("No transformed data set is available.\nPlease check your data entries to insure that one has been entered correctly.");
                return;
            }
        }
        else
        {
            // generate transformed data from the alm's
            s_association->generateTransformedDataFromAlm(s_association->transformationEngine(), fileType::AlmData);

            // create the inverse map for use when creating the pseudo spectrum
            s_association->generateInverseData(s_association->transformationEngine(), fileType::AlmData);
        }
    }

    if (!s_association->exists(fileType::TransformedWeights))
    {
        if(!s_association->exists(fileType::AlmWeights))
        {
            if (!s_association->exists(dataEngines::Transformation))
            {
                errorMessage("No Transformation engine exists.");
                if(!handleMissingTransformer()) return;
            }

            if (!transform(fileType::PixelizedWeights,fileType::TransformedWeights))
            {
                errorMessage("No transformed mask set is available.\nPlease check your data entries to insure that one has been entered correctly.");
                return;
            }
        }
        else
        {
            s_association->generateTransformedDataFromAlm(s_association->transformationEngine(), fileType::AlmWeights);
            s_association->generateInverseData(s_association->transformationEngine(), fileType::AlmWeights);
        }
    }

    if (!s_association->exists(fileType::WeightedTransform))
    {
        if(!s_association->exists(fileType::WeightedAlm))
        {
            if( s_association->exists(fileType::PixelizedData) &&
                s_association->exists(fileType::PixelizedWeights))
                s_association->generateWeightedData(fileType::WeightedPixel);

            if (!s_association->exists(dataEngines::Transformation))
            {
                errorMessage("No Transformation engine exists.");
                if(!handleMissingTransformer()) return;
            }

            if (!transform(fileType::WeightedPixel, fileType::WeightedTransform))
            {
                errorMessage("No weighted transformed set is available.\nPlease check your data entries to insure that one has been entered correctly.");
                return;
            }
        }
        else
        {
            s_association->generateTransformedDataFromAlm(s_association->transformationEngine(), fileType::WeightedAlm);
            s_association->generateInverseData(s_association->transformationEngine(), fileType::WeightedAlm);
        }
    }

    if (!s_association->exists(fileType::TransformedNoise))
    {
        if(!s_association->exists(fileType::AlmNoise))
        {
            if (!s_association->exists(dataEngines::Transformation))
            {
                errorMessage("No Transformation engine exists.");
                if(!handleMissingTransformer()) return;
            }

            if (!transform(fileType::PixelizedNoise,fileType::TransformedNoise))
            {
                s_association->merge(fileType::TransformedNoise,s_association->transformedData(),false);
                s_association->transformedNoise()->dataType(fileType::TransformedNoise);

                // fill vector with white noise
                //s_association->createWhiteNoise(s_association->transformedNoise());
                //s_association->createShotNoise(s_association->transformedNoise());

                // this is wrong but the math says to subtract the noise which will give negatives
                int rows = s_association->transformedNoise()->rows();
                s_association->transformedNoise()->rwAccess().assign(rows, 0.0);
            }
        }
        else
        {
            s_association->generateTransformedDataFromAlm(s_association->transformationEngine(), fileType::AlmNoise);
            s_association->generateInverseData(s_association->transformationEngine(), fileType::AlmNoise);
        }
    }

    if (!s_association->exists(fileType::TransformedWeightedNoise))
    {
        if(!s_association->exists(fileType::AlmWeightedNoise))
        {
            if(s_association->exists(fileType::PixelizedNoise) &&
                s_association->exists(fileType::PixelizedWeights))
            {
                s_association->generateWeightedData(fileType::PixelizedWeightedNoise);
            }

            if (!s_association->exists(dataEngines::Transformation))
            {
                errorMessage("No Transformation engine exists.");
                if(!handleMissingTransformer()) return;
            }

            if (!transform(fileType::PixelizedWeightedNoise, fileType::TransformedWeightedNoise))
            {
                s_association->merge(fileType::TransformedWeightedNoise, s_association->transformedData(), false);
                s_association->weightedTransformedNoise()->dataType(fileType::TransformedWeightedNoise);
                int rows = s_association->weightedTransformedNoise()->rows();
                s_association->weightedTransformedNoise()->rwAccess().assign(rows, 0);
            }
        }
        else
        {
            s_association->generateTransformedDataFromAlm(s_association->transformationEngine(), fileType::AlmWeightedNoise);
            s_association->generateInverseData(s_association->transformationEngine(), fileType::AlmWeightedNoise);
        }
    }

    if (!s_association->exists(fileType::TransformedFilter))
    {
        if(!s_association->exists(fileType::AlmFilter))
        {
            if (!s_association->exists(dataEngines::Transformation))
            {
                errorMessage("No Transformation Engine exists.");
                if(!handleMissingTransformer()) return;
            }

            if (!transform(fileType::PixelizedFilter,fileType::TransformedFilter))
            {
                s_association->merge(fileType::TransformedFilter,s_association->transformedData(),false);
                s_association->transformedFilter()->dataType(fileType::TransformedFilter);
                int rows = s_association->transformedFilter()->rows();
                //s_association->transformedFilter()->rwAccess().assign(rows,1.0);
                s_association->transformedFilter()->rwAccess().assign(rows, 1.0);
            }
        }
        else
        {
            s_association->generateTransformedDataFromAlm(s_association->transformationEngine(), fileType::AlmFilter);
            s_association->generateInverseData(s_association->transformationEngine(), fileType::AlmFilter);
        }
    }

    if (!s_association->exists(fileType::TransformedBeam))
    {
        if(!s_association->exists(fileType::AlmBeam))
        {
            if (!s_association->exists(dataEngines::Transformation))
            {
                errorMessage("No Transformation Engine exists.");
                if(!handleMissingTransformer()) return;
            }

            if (!transform(fileType::PixelizedBeam,fileType::TransformedBeam))
            {
                s_association->merge(fileType::TransformedBeam,s_association->transformedData(),false);
                s_association->transformedBeam()->dataType(fileType::TransformedBeam);
                int rows = s_association->transformedData()->rows();
                s_association->transformedBeam()->rwAccess().assign(rows, 1.0);
            }
        }
        else
        {
            s_association->generateTransformedDataFromAlm(s_association->transformationEngine(), fileType::AlmBeam);
            s_association->generateInverseData(s_association->transformationEngine(), fileType::AlmBeam);
        }
    }

    // set the number of ls in the spectra
    s_association->powerSpectraEngine()->maxIndex(s_association->weightedTransform()->rows());

    // everything is here and ready to go, so carry out analysis
    // generatePowerSpectrumData will just do everything including ensembling
    s_association->generatePowerSpectrumData(s_association->powerSpectraEngine());

    configureDisplay(fileType::BinnedExtrapolatedInstrumentedSpectrum);
}
