/***************************************************************************
 *   healpixdlg.h                                                          *
 *   Copyright (C) 2014 by Daniel Suson                                    *
 *   suson@calumet.purdue.edu                                              *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU General Public License     *
 *   along with this program; if not, write to the                         *
 *   Free Software Foundation, Inc.,                                       *
 *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
 *                                                                         *
 *   In addition, as a special exception, the copyright holders give       *
 *   permission to link the code of this program with any edition of       *
 *   the Qt library by Trolltech AS, Norway (or with modified versions     *
 *   of Qt that use the same license as Qt), and distribute linked         *
 *   combinations including the two.  You must obey the GNU General        *
 *   Public License in all respects for all of the code used other than    *
 *   Qt.  If you modify this file, you may extend this exception to        *
 *   your version of the file, but you are not obligated to do so.  If     *
 *   you do not wish to do so, delete this exception statement from        *
 *   your version.                                                         *
 ***************************************************************************
 * Description:                                                            *
 *                                                                         *
 * This class defines the healpix dialog box structure associated          *
 * with the Qt4 user interface.                                            *
 * ----------------------- Change Log ------------------------------------ *
 * Date    Name         Description                                        *
 *                                                                         *
 ***************************************************************************
 * This software evolved from work that was done by Eric Hivon at the      *
 * California Institute of Technology on the MASTER algorithm (Hivon, E.,  *
 * et al., ApJ, vol 567, p 2).  It adapts or interfaces with these         *
 * packages:                                                               *
 *                                                                         *
 * HealPix         (http://www.eso.org/science/healpix/)                   *
 * FTOOLS & FITSIO (http://heasarc.gsfc.nasa.gov/docs/corp/software.html)  *
 *                                                                         *
 * Any publications or presentations that use results generated by this    *
 * program must reference the fact that it was developed by Daniel Suson   *
 ***************************************************************************/
#ifndef _HEALPIXDIALOGPARENT_H_
#define _HEALPIXDIALOGPARENT_H_

#include "../libanalyzer/atypes.h"
#include "../libanalyzer/association.h"
#include "../libanalyzer/healpix.h"

class healpixDialogParent
{
  public:
    healpixDialogParent(association* assoc);
    virtual ~healpixDialogParent() {}

	bool configured() const {return isConfigured;}
    void configured(bool config) {isConfigured = config;}
    int scale() const {return nSides;}

    bool usePixelAvg() const {return usePixAvg;}
    bool usePixelDev() const {return usePixDev;}
    bool usePixelVar() const {return usePixVar;}

    bool doAvgNormalize() const {return doAvgNorm;}
    bool doVarNormalize() const {return doVarNorm;}
    bool doMinMaxScale()  const {return doMinMax;}

    bool order() const {return nestedFlag;}
    void setAssociation(association* newAssoc) {dataAssoc = newAssoc;}

   //Q_SLOTS:
    virtual void configure() = 0;
    virtual void reset() = 0;

  //Q_SIGNALS:
    virtual void pixelizationCancelled() = 0;
    virtual void pixelizeData() = 0;
    
  protected:
    virtual void validate() = 0;

	int sides(double resolution) { return (int)(360.0 / (resolution * sqrt(12.0*M_PI)));}
    double resolution (int sides) { return 360.0 / (sides * sqrt(12.0*M_PI));}
    
    association *dataAssoc;
    FILETYPE dataType;
    bool nestedFlag;
    bool usePixAvg, usePixDev, usePixVar;
    bool doAvgNorm, doVarNorm, doMinMax;
    int nSides; // index;
    double res;
    bool dirty, isConfigured;

  //Q_SLOTS:
    virtual void syncSides() = 0;

	virtual void finalize() = 0;
    virtual void help() = 0;
    virtual void cancel() = 0;
};
#endif
