/***************************************************************************
 *   filemanager.cpp                                                       *
 *   Copyright (C) 2014 by Daniel Suson                                    *
 *   daniel.suson@purduecal.edu                                            *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU General Public License     *
 *   along with this program; if not, write to the                         *
 *   Free Software Foundation, Inc.,                                       *
 *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
 *                                                                         *
 *   In addition, as a special exception, the copyright holders give       *
 *   permission to link the code of this program with any edition of       *
 *   the Qt library by Trolltech AS, Norway (or with modified versions     *
 *   of Qt that use the same license as Qt), and distribute linked         *
 *   combinations including the two.  You must obey the GNU General        *
 *   Public License in all respects for all of the code used other than    *
 *   Qt.  If you modify this file, you may extend this exception to        *
 *   your version of the file, but you are not obligated to do so.  If     *
 *   you do not wish to do so, delete this exception statement from        *
 *   your version.                                                         *
 ***************************************************************************
 * Description:                                                            *
 *                                                                         *
 * Interface for all file manager types.                                   *
 *                                                                         *
 * Subclasses shall implement two constructors:                            *
 *                                                                         *
 *    <fileclass> (const char *load_filename);                             *
 *    <fileclass> (baseData *data, const char *save_filename);             *
 *                                                                         *
 * These will load and save data, respectively. The "save"                 *
 * constructor can assume the proper FILETYPE has been set inside the      *
 * baseData object...                                                      *
 *                                                                         *
 * In all cases the subclass shall insure that the opened file is closed   *
 * when its destructor is called.                                          *
 *                                                                         *
 * If a property does not exist for a certain file, the subclass           *
 * shall assign the empty value (for enum types), and 0 or 1 to valued     *
 * types, which ever makes sense: e.g. dimensional values cannot be less   *
 * than one if ANY file data exists.                                       *
 * ----------------------- Change Log ------------------------------------ *
 * Date    Name         Description                                        *
 *                                                                         *
 ***************************************************************************
 * This software evolved from work that was done by Eric Hivon at the      *
 * California Institute of Technology on the MASTER algorithm (Hivon, E.,  *
 * et al., ApJ, vol 567, p 2).  It adapts or interfaces with these         *
 * packages:                                                               *
 *                                                                         *
 * HealPix         (http://www.eso.org/science/healpix/)                   *
 * FTOOLS & FITSIO (http://heasarc.gsfc.nasa.gov/docs/corp/software.html)  *
 *                                                                         *
 * Any publications or presentations that use results generated by this    *
 * program must reference the fact that it was developed by Daniel Suson   *
 ***************************************************************************/
#include "filemanager.h"
#include "pixelizer.h"
#include "transformer.h"

fileManager::fileManager(association* dataMgr)
{
  m_updateFunc = 0;
  m_uiObject = 0;
  m_dimensions = 0;
  m_rows = 0;
  m_cols = 0;
  m_slices = 0;
  m_parts = 0;
      
  m_minSlice = 0;
  m_maxSlice = 0;
  for (int i = 0; i< MAX_SLICES;++i) {
    m_minE[i] = 0;
    m_maxE[i] = 0;
  }
  m_fileFormat = None;
  m_err = noErrors;
  m_filename = 0;

  m_observatory = Analyzer;
  s_association = dataMgr;

  m_commentMap = new std::map<string, string>();
}

fileManager::fileManager(fileManager* from) {
  m_showProgress = from->showProgress();
  m_updateFunc = from->updateFunction();
  m_uiObject = from->userInterface();
  m_dimensions = from->dimensions();
  m_rows = from->rows();
  m_cols = from->cols();
  m_slices = from->slices();
  m_parts = from->parts();

  m_minSlice = from->minSlice();;
  m_maxSlice = from->maxSlice();;
  for (int i = 0; i< MAX_SLICES;++i) {
    m_minE[i] = from->min_energy(i);
    m_maxE[i] = from->max_energy(i);;
  }
  m_fileFormat = from->fileFormat();
  m_err = from->error();
  fileName(from->fileName());

  m_observatory = from->m_observatory;
  s_association = from->s_association;

}

fileManager& fileManager::operator=(fileManager& other) {
  m_showProgress = other.showProgress();
  m_updateFunc = other.updateFunction();
  m_uiObject = other.userInterface();
  m_dimensions = other.dimensions();
  m_rows = other.rows();
  m_cols = other.cols();
  m_slices = other.slices();
  m_parts = other.parts();

  m_minSlice = other.minSlice();;
  m_maxSlice = other.maxSlice();;
  for (int i = 0; i< MAX_SLICES;++i) {
    m_minE[i] = other.min_energy(i);
    m_maxE[i] = other.max_energy(i);;
  }
  m_fileFormat = other.fileFormat();
  m_err = other.error();
  fileName(other.fileName());

  m_observatory = other.m_observatory;
  return *this;
}

void fileManager::fileName(const char* name)
{
  m_filename = new char[strlen(name) + 1];
  for(int i = 0; i < strlen(name) + 1; i += 1)
    m_filename[i] = name[i];
}

const char** fileManager::createInfoArray(FILETYPE ft, int* size)
{
    baseData* genData = s_association->getData(ft);

    switch(ft)
    {
      case fileType::InputData:
      case fileType::InputWeights:
      case fileType::InputFilter:
      case fileType::InputBeam:
      case fileType::InputNoise:
      case fileType::WeightedData:
      case fileType::InputWeightedNoise:
      case fileType::ModeModeMatrix:
      case fileType::InverseModeModeMatrix:
      case fileType::InstrumentEffectsMatrix:
      case fileType::InverseInstrumentEffectsMatrix:
      case fileType::BinningMatrix:
      case fileType::UnbinningMatrix:
      case fileType::BinnedInstrumentEffectsMatrix:
      case fileType::InverseBinnedInstrumentMatrix:
      case fileType::EnsembleIterationSpectrum:
      case fileType::EnsembleIterationNoise:
      {
        matrixData<double>* data = (matrixData<double>*)genData;

        *size = 2 * 2;
        const char** infoData = new const char*[*size];

        string *ra  = new string(std::to_string(data->RARes()));
        string *dec = new string(std::to_string(data->DecRes()));

        infoData[0] = "CDELT1";
        infoData[1] = "CDELT2";

        infoData[2] = ra->c_str();
        infoData[3] = dec->c_str();

        return infoData;
      }
      case fileType::PixelizedData:
      case fileType::PixelizedWeights:
      case fileType::WeightedPixel:
      case fileType::PixelizedNoise:
      case fileType::PixelizedWeightedNoise:
      case fileType::PixelizedFilter:
      case fileType::PixelizedBeam:
      case fileType::InverseData:
      case fileType::InverseWeights:
      case fileType::WeightedInverse:
      case fileType::InverseNoise:
      case fileType::InverseWeightedNoise:
      case fileType::InverseFilter:
      case fileType::InverseBeam:
      {
        vectorData<double>* data = (vectorData<double>*)genData;

        *size = 2 * 3;
        const char** infoData = new const char*[*size];

        string *nsides = new string(std::to_string(data->sides()));
        string *layout, *scheme;

        if (data->layout() == Ring)
          layout = new string("Ring");
        else if (data->layout() == Nest)
          layout = new string("Nest");
        else
          layout = new string("Unordered");

        if (data->pixelScheme() == HealPIX)
          scheme = new string("HealPIX");
        else
          scheme = new string("NotPixelized");

        infoData[0] = "NSIDES";
        infoData[1] = "PIXLAYOUT";
        infoData[2] = "PIXSCHEME";

        infoData[3] = nsides->c_str();
        infoData[4] = layout->c_str();
        infoData[5] = scheme->c_str();

        return infoData;
      }
      case fileType::TransformedData:
      case fileType::TransformedWeights:
      case fileType::WeightedTransform:
      case fileType::TransformedNoise:
      case fileType::TransformedWeightedNoise:
      case fileType::TransformedFilter:
      case fileType::TransformedBeam:
      {
        vectorData<double>* data = (vectorData<double>*)genData;

        *size = 2 * 6;
        const char** infoData = new const char*[*size];

        string *nsides = new string(std::to_string(data->sides()));
        string *min    = new string(std::to_string(data->minYIndex()));
        string *max    = new string(std::to_string(data->maxYIndex()));

        string *layout, *scheme, *trans;

        if (data->layout() == Ring)
          layout = new string("Ring");
        else if (data->layout() == Nest)
          layout = new string("Nest");
        else
          layout = new string("Unordered");

        if (data->pixelScheme() == HealPIX)
          scheme = new string("HealPIX");
        else
          scheme = new string("NotPixelized");

        if (data->transformerScheme() == Rsht)
          trans = new string("Rsht");
        else
          trans = new string("NotTransformed");

        infoData[0] = "NSIDES";
        infoData[1] = "PIXLAYOUT";
        infoData[2] = "PIXSCHEME";
        infoData[3] = "TRANSFORMERSCHEME";
        infoData[5] = "MININDEX";
        infoData[4] = "MAXINDEX";

        infoData[6]  = nsides->c_str();
        infoData[7]  = layout->c_str();
        infoData[8]  = scheme->c_str();
        infoData[9]  = trans->c_str();
        infoData[11] = min->c_str();
        infoData[10] = max->c_str();

        return infoData;
      }
      case fileType::EnsembleAveragedNoise:
      case fileType::EnsembleAveragedSpectrum:
      case fileType::ExtrapolatedSpectrum:
      case fileType::ExtrapolatedInstrumentSpectrum:
      case fileType::BinnedSpectrum:
      case fileType::BinnedExtrapolatedSpectrum:
      case fileType::BinnedExtrapolatedInstrumentedSpectrum:
      {
        vectorData<double>* data = (vectorData<double>*)genData;

        *size = 2 * 9;
        const char** infoData = new const char*[*size];

        string *nsides = new string(std::to_string(data->sides()));
        string *minInd = new string(std::to_string(data->minYIndex()));
        string *maxInd = new string(std::to_string(data->maxYIndex()));
        string *minVal = new string(std::to_string(data->minValue()));
        string *maxVal = new string(std::to_string(data->maxValue()));
        string *mask   = new string(std::to_string(data->mask()));

        string *layout, *scheme, *trans;

        if (data->layout() == Ring)
          layout = new string("Ring");
        else if (data->layout() == Nest)
          layout = new string("Nest");
        else
          layout = new string("Unordered");

        if (data->pixelScheme() == HealPIX)
          scheme = new string("HealPIX");
        else
          scheme = new string("NotPixelized");

        if (data->transformerScheme() == Rsht)
          trans = new string("Rsht");
        else
          trans = new string("NotTransformed");

        infoData[0] = "NSIDES";
        infoData[1] = "PIXLAYOUT";
        infoData[2] = "PIXSCHEME";
        infoData[3] = "TRANSFORMERSCHEME";
        infoData[5] = "MININDEX";
        infoData[4] = "MAXINDEX";
        infoData[7] = "MINVALUE";
        infoData[6] = "MAXVALUE";
        infoData[8] = "MASKINDEX";

        infoData[9]  = nsides->c_str();
        infoData[10] = layout->c_str();
        infoData[11] = scheme->c_str();
        infoData[12] = trans->c_str();
        infoData[14] = minInd->c_str();
        infoData[13] = maxInd->c_str();
        infoData[16] = minVal->c_str();
        infoData[15] = maxVal->c_str();
        infoData[17] = mask->c_str();

        return infoData;
      }
      case fileType::AlmData:
      case fileType::AlmWeights:
      case fileType::AlmFilter:
      case fileType::AlmNoise:
      case fileType::AlmBeam:
      case fileType::WeightedAlm:
      case fileType::AlmWeightedNoise:
      {
        cubeData<complex<double>>* data = (cubeData<complex<double>>*)genData;

        *size = 2 * 11;
        const char** infoData = new const char*[*size];

        string *nsides = new string(std::to_string(data->sides()));
        string *minInd = new string(std::to_string(data->transMinIndex()));
        string *maxInd = new string(std::to_string(data->transMaxIndex()));
        string *minVal = new string(std::to_string(data->transMinValue()));
        string *maxVal = new string(std::to_string(data->transMaxValue()));
        string *mask   = new string(std::to_string(data->transMask()));
        string *polar  = new string(std::to_string(data->polarization()));
        string *index  = new string(std::to_string(data->index()));

        string *layout, *scheme, *trans;

        if (data->layout() == Ring)
          layout = new string("Ring");
        else if (data->layout() == Nest)
          layout = new string("Nest");
        else
          layout = new string("Unordered");

        if (data->pixelScheme() == HealPIX)
          scheme = new string("HealPIX");
        else
          scheme = new string("NotPixelized");

        if (data->transformerScheme() == Rsht)
          trans = new string("Rsht");
        else
          trans = new string("NotTransformed");

        infoData[0]  = "POLARIZATION";
        infoData[1]  = "INDEX";
        infoData[2]  = "NSIDES";
        infoData[3]  = "PIXLAYOUT";
        infoData[4]  = "PIXSCHEME";
        infoData[5]  = "TRANSFORMERSCHEME";
        infoData[6]  = "TRANSMININDEX";
        infoData[7]  = "TRANSMAXINDEX";
        infoData[8]  = "TRANSMINVALUE";
        infoData[9]  = "TRANSMAXVALUE";
        infoData[10] = "TRANSMASKINDEX";

        infoData[11] = polar->c_str();
        infoData[12] = index->c_str();
        infoData[13] = nsides->c_str();
        infoData[14] = layout->c_str();
        infoData[15] = scheme->c_str();
        infoData[16] = trans->c_str();
        infoData[17] = minInd->c_str();
        infoData[18] = maxInd->c_str();
        infoData[19] = minVal->c_str();
        infoData[20] = maxVal->c_str();
        infoData[21] = mask->c_str();

        return infoData;
      }
      default:
        return 0;
    }

    return 0;
}

bool fileManager::setAttributes(FILETYPE ft, baseData* genData)
{
    switch(ft)
    {
      case fileType::InputData:
      case fileType::InputWeights:
      case fileType::InputFilter:
      case fileType::InputBeam:
      case fileType::InputNoise:
      case fileType::WeightedData:
      case fileType::InputWeightedNoise:
      case fileType::ModeModeMatrix:
      case fileType::InverseModeModeMatrix:
      case fileType::InstrumentEffectsMatrix:
      case fileType::InverseInstrumentEffectsMatrix:
      case fileType::BinningMatrix:
      case fileType::UnbinningMatrix:
      case fileType::BinnedInstrumentEffectsMatrix:
      case fileType::InverseBinnedInstrumentMatrix:
      case fileType::EnsembleIterationSpectrum:
      case fileType::EnsembleIterationNoise:
      {
        matrixData<double>* data = (matrixData<double>*)genData;

        double ra  = std::stod((*m_commentMap)["CDELT1"]);
        double dec = std::stod((*m_commentMap)["CDELT2"]);

        data->RARes(ra);
        data->DecRes(dec);

        return true;
      }
      case fileType::PixelizedData:
      case fileType::PixelizedWeights:
      case fileType::WeightedPixel:
      case fileType::PixelizedNoise:
      case fileType::PixelizedWeightedNoise:
      case fileType::PixelizedFilter:
      case fileType::PixelizedBeam:
      case fileType::InverseData:
      case fileType::InverseWeights:
      case fileType::WeightedInverse:
      case fileType::InverseNoise:
      case fileType::InverseWeightedNoise:
      case fileType::InverseFilter:
      case fileType::InverseBeam:
      {
        vectorData<double>* data = (vectorData<double>*)genData;

        int nsides = std::stoi((*m_commentMap)["NSIDES"]);

        PIXELSCHEME scheme = (*m_commentMap)["PIXSCHEME"] == "HealPIX" ? HealPIX : NotPixelized;

        LAYOUT layout = Unordered;
        if((*m_commentMap)["PIXLAYOUT"] == "Ring")
          layout = Ring;
        else if((*m_commentMap)["PIXLAYOUT"] == "Nest")
          layout = Nest;
        else
          layout = Unordered;

        data->sides(nsides);
        data->layout(layout);
        data->pixelScheme(scheme);

        data->transformerScheme(NotTransformed);

        if (scheme == HealPIX)
        {
          data->numberOfPixels(12 * nsides * nsides);

          if(!s_association->exists(dataEngines::Pixelization))
          {
            s_association->addEngine(dataEngines::Pixelization, PIXELSCHEME::HealPIX);
            s_association->pixelizationEngine()->pixelLayout(data->layout());
            s_association->pixelizationEngine()->pixelizerScheme(data->pixelScheme());
            s_association->pixelizationEngine()->scale(nsides);
          }
        }
        else
        {
          data->pixelScheme(NotPixelized);
          data->numberOfPixels(0);
        }


        return true;
      }
      case fileType::TransformedData:
      case fileType::TransformedWeights:
      case fileType::WeightedTransform:
      case fileType::TransformedNoise:
      case fileType::TransformedWeightedNoise:
      case fileType::TransformedFilter:
      case fileType::TransformedBeam:
      {
        vectorData<double>* data = (vectorData<double>*)genData;

        int nsides = std::stoi((*m_commentMap)["NSIDES"]);
        int min    = std::stoi((*m_commentMap)["MININDEX"]);
        int max    = std::stoi((*m_commentMap)["MAXINDEX"]);

        PIXELSCHEME scheme = (*m_commentMap)["PIXSCHEME"] == "HealPIX" ? HealPIX : NotPixelized;

        LAYOUT layout = Unordered;
        if((*m_commentMap)["PIXLAYOUT"] == "Ring")
          layout = Ring;
        else if((*m_commentMap)["PIXLAYOUT"] == "Nest")
          layout = Nest;
        else
          layout = Unordered;

        TRANSFORMERSCHEME trans = (*m_commentMap)["TRANSFORMERSCHEME"] == "Rsht" ? Rsht : NotTransformed;

        data->sides(nsides);
        data->layout(layout);
        data->pixelScheme(scheme);

        data->transformerScheme(trans);
        data->minYIndex(min);
        data->maxYIndex(max);

        if (scheme == HealPIX)
        {
          data->numberOfPixels(12 * nsides * nsides);

          if(!s_association->exists(dataEngines::Pixelization))
          {
            s_association->addEngine(dataEngines::Pixelization, PIXELSCHEME::HealPIX);
            s_association->pixelizationEngine()->pixelLayout(data->layout());
            s_association->pixelizationEngine()->pixelizerScheme(data->pixelScheme());
            s_association->pixelizationEngine()->scale(nsides);
          }
        }
        else
          data->numberOfPixels(0);

        if (trans == Rsht)
        {
          if(!s_association->exists(dataEngines::Transformation))
          {
            s_association->addEngine(dataEngines::Transformation, TRANSFORMERSCHEME::Rsht);
            s_association->transformationEngine()->transformerScheme(data->transformerScheme());
            s_association->transformationEngine()->minIndex(data->minYIndex());
            s_association->transformationEngine()->maxIndex(data->maxYIndex());
          }
        }

        return true;

      }
      case fileType::EnsembleAveragedNoise:
      case fileType::EnsembleAveragedSpectrum:
      case fileType::ExtrapolatedSpectrum:
      case fileType::ExtrapolatedInstrumentSpectrum:
      case fileType::BinnedSpectrum:
      case fileType::BinnedExtrapolatedSpectrum:
      case fileType::BinnedExtrapolatedInstrumentedSpectrum:
      {
        vectorData<double>* data = (vectorData<double>*)genData;

        int nsides  = std::stoi((*m_commentMap)["NSIDES"]);
        int minInd  = std::stoi((*m_commentMap)["MININDEX"]);
        int maxInd  = std::stoi((*m_commentMap)["MAXINDEX"]);
        int maskInd = std::stoi((*m_commentMap)["MASKINDEX"]);

        double minVal = std::stod((*m_commentMap)["MINVALUE"]);
        double maxVal = std::stod((*m_commentMap)["MAXVALUE"]);

        PIXELSCHEME scheme = (*m_commentMap)["PIXSCHEME"] == "HealPIX" ? HealPIX : NotPixelized;

        LAYOUT layout = Unordered;
        if((*m_commentMap)["PIXLAYOUT"] == "Ring")
          layout = Ring;
        else if((*m_commentMap)["PIXLAYOUT"] == "Nest")
          layout = Nest;
        else
          layout = Unordered;

        TRANSFORMERSCHEME trans = (*m_commentMap)["TRANSFORMERSCHEME"] == "Rsht" ? Rsht : NotTransformed;

        data->sides(nsides);
        data->layout(layout);
        data->pixelScheme(scheme);

        data->transformerScheme(trans);
        data->minYIndex(minInd);
        data->maxYIndex(maxInd);
        data->minValue(minVal);
        data->maxValue(maxVal);
        data->mask(maskInd);

        if (scheme == HealPIX)
        {
          data->numberOfPixels(12 * nsides * nsides);

          if(!s_association->exists(dataEngines::Pixelization))
          {
            s_association->addEngine(dataEngines::Pixelization, PIXELSCHEME::HealPIX);
            s_association->pixelizationEngine()->pixelLayout(data->layout());
            s_association->pixelizationEngine()->pixelizerScheme(data->pixelScheme());
            s_association->pixelizationEngine()->scale(nsides);
          }
        }
        else
          data->numberOfPixels(0);

        if (trans == Rsht)
        {
          if(!s_association->exists(dataEngines::Transformation))
          {
            s_association->addEngine(dataEngines::Transformation, TRANSFORMERSCHEME::Rsht);
            s_association->transformationEngine()->transformerScheme(data->transformerScheme());
            s_association->transformationEngine()->minIndex(data->minYIndex());
            s_association->transformationEngine()->maxIndex(data->maxYIndex());
          }
        }

        return true;
      }
      case fileType::AlmData:
      case fileType::AlmWeights:
      case fileType::AlmFilter:
      case fileType::AlmNoise:
      case fileType::AlmBeam:
      case fileType::WeightedAlm:
      case fileType::AlmWeightedNoise:
      {
        cubeData<complex<double>>* data = (cubeData<complex<double>>*)genData;

        int nsides  = std::stoi((*m_commentMap)["NSIDES"]);
        int minInd  = std::stoi((*m_commentMap)["TRANSMININDEX"]);
        int maxInd  = std::stoi((*m_commentMap)["TRANSMAXINDEX"]);
        int maskInd = std::stoi((*m_commentMap)["TRANSMASKINDEX"]);
        int polar   = std::stoi((*m_commentMap)["POLARIZATION"]);
        int index   = std::stoi((*m_commentMap)["INDEX"]);

        double minVal = std::stod((*m_commentMap)["TRANSMINVALUE"]);
        double maxVal = std::stod((*m_commentMap)["TRANSMAXVALUE"]);

        PIXELSCHEME scheme = (*m_commentMap)["PIXSCHEME"] == "HealPIX" ? HealPIX : NotPixelized;

        LAYOUT layout = Unordered;
        if((*m_commentMap)["PIXLAYOUT"] == "Ring")
          layout = Ring;
        else if((*m_commentMap)["PIXLAYOUT"] == "Nest")
          layout = Nest;
        else
          layout = Unordered;

        TRANSFORMERSCHEME trans = (*m_commentMap)["TRANSFORMERSCHEME"] == "Rsht" ? Rsht : NotTransformed;

        data->sides(nsides);
        data->layout(layout);
        data->pixelScheme(scheme);

        data->transformerScheme(trans);
        data->minYIndex(minInd);
        data->maxYIndex(maxInd);
        data->transMinValue(minVal);
        data->transMaxValue(maxVal);
        data->transMask(maskInd);

        data->polarization(polar);
        data->index(index);

        if (scheme == HealPIX)
        {
          if(!s_association->exists(dataEngines::Pixelization))
          {
            s_association->addEngine(dataEngines::Pixelization, PIXELSCHEME::HealPIX);
            s_association->pixelizationEngine()->pixelLayout(data->layout());
            s_association->pixelizationEngine()->pixelizerScheme(data->pixelScheme());
            s_association->pixelizationEngine()->scale(nsides);
          }
        }

        if (trans == Rsht)
        {
          if(!s_association->exists(dataEngines::Transformation))
          {
            s_association->addEngine(dataEngines::Transformation, TRANSFORMERSCHEME::Rsht);
            s_association->transformationEngine()->transformerScheme(data->transformerScheme());
            s_association->transformationEngine()->minIndex(data->minYIndex());
            s_association->transformationEngine()->maxIndex(data->maxYIndex());
          }
        }

        return true;
      }
      default:
        return false;
    }

    return false;
}

float fileManager::min_energy(int i) {
  if (i > MAX_SLICES || i < 0) {
    m_err = fileEnergyArrayError;
    return -1.0;
  }

  return m_minE[i];
}

float fileManager::max_energy(int i) {
  if (i > MAX_SLICES || i < 0) {
    m_err = fileEnergyArrayError;
    return -1.0;
  }

  return m_maxE[i];
}

void fileManager::min_energy(int i, float E) {
  if (i > MAX_SLICES || i < 0) {
    m_err = fileEnergyArrayError;
  }

  m_minE[i] = E;
}

void fileManager::max_energy(int i, float E)
{
  if (i > MAX_SLICES || i < 0) {
    m_err = fileEnergyArrayError;
  }
  m_maxE[i] = E;
}

int fileManager::min_energy(float E, int garbage)
{
  for(int i = m_minSlice; i < m_maxSlice; i += 1)
    if(m_minE[i] == E)
      return i;

  m_err = fileEnergyError;

  return -1;
}

int fileManager::max_energy(float E, int garbage)
{
  for(int i = 0; i < m_maxSlice; i += 1)
    if(m_maxE[i] == E)
      return i;

  m_err = fileEnergyError;

  return -1;
}

void fileManager::save(int* numTypes, FILETYPE* dataTypes)
{
  baseData *data = 0;
  m_err     = noErrors;
  m_observatory = Analyzer;

  for(int i = 0; i < *numTypes; i += 1)
  {
    data = s_association->getData(dataTypes[i]);
    string dataName = dataSetName(dataTypes[i]);

    m_fileDataType = dataTypes[i];

    m_cols         = data->cols();
    m_rows         = data->rows();
    m_slices       = data->slices();

    switch (m_fileDataType) {
        case fileType::Null:
        m_err = fileInvalidError;
        s_association->errorValue(m_err);
        throw m_err;
      case fileType::InputData:
      case fileType::InputWeights:
      case fileType::WeightedData:
      case fileType::InputNoise:
      case fileType::InputWeightedNoise:
      case fileType::InputFilter:
      case fileType::InputBeam:
      case fileType::EnsembleIterationNoise:
      case fileType::EnsembleIterationSpectrum:
      //case fileType::EnsembleIterationBinnedSpectrum:
      case fileType::ModeModeMatrix:
      case fileType::InverseModeModeMatrix:
      case fileType::InstrumentEffectsMatrix:
      case fileType::InverseInstrumentEffectsMatrix:
      case fileType::BinningMatrix:
      case fileType::UnbinningMatrix:
      case fileType::BinnedInstrumentEffectsMatrix:
      case fileType::InverseBinnedInstrumentMatrix:
      /*
      case fileType::BinCouplingMatrix:
      case fileType::ModeCouplingMatrix:
      case fileType::InverseBinMatrix:
      case fileType::InverseModeMatrix:
      */
        m_dimensions = 2;
        m_parts = 1;
        if (!saveMatrixD((matrixData<double>*)data))
        {
          m_errDetail += "File Manager Error: Unable to save dataset: " + dataName;
          s_association->displayErrorMessage(m_errDetail.c_str());
          throw m_err;
        }
        break;
      case fileType::AlmData:
      case fileType::AlmWeights:
      case fileType::WeightedAlm:
      case fileType::AlmNoise:
      case fileType::AlmWeightedNoise:
      case fileType::AlmFilter:
      case fileType::AlmBeam:
        m_dimensions = 4;
        m_parts = 2;
        if (!saveCubeCD((cubeData<complex<double> >*)data))
        {
          m_errDetail += "File Manager Error: Unable to save dataset: " + dataName;
          s_association->displayErrorMessage(m_errDetail.c_str());
          throw m_err;
        }
        break;
      case fileType::PixelOccupancy:
        m_dimensions = 1;
        m_parts = 1;
        if (!saveVectorI((vectorData<int>*)data))
        {
          m_errDetail += "File Manager Error: Unable to save dataset: " + dataName;
          s_association->displayErrorMessage(m_errDetail.c_str());
          throw m_err;
        }
        break;
      default:
        m_dimensions = 1;
        m_parts = 1;
        if (!saveVectorD((vectorData<double>*)data))
        {
          m_errDetail += "File Manager Error: Unable to save dataset: " + dataName;
          s_association->displayErrorMessage(m_errDetail.c_str());
          throw m_err;
        }
        break;
    }
  }

}

void fileManager::open(int* numTypes, FILETYPE* dataTypes)
{
  for(int i = 0; i < *numTypes; i += 1)
  {
      m_fileDataType = dataTypes[i];

      std::string dataName = dataTypeNames[static_cast<int>(dataTypes[i])];

      s_association->updateProgressText(dataName.c_str());
      baseData* dataValue = data();

      if(dataValue == 0)
      {
        m_errDetail += "File Manager Error: Unable to open dataset: " + dataName;
        s_association->displayErrorMessage(m_errDetail.c_str());
        return;
      }

      dataValue->fileName(this->fileName());
      s_association->addData(dataValue);
  }
}

std::string fileManager::errorDescription(ERRORCODES value) {
  m_err = value;
  if (value > noFileError || value < fileResError)
    m_err = valueOutOfRange;
  m_errDetail = errorText[m_err];

  return m_errDetail;
}

/*
void fileManager::setProgressFunc(void* uiObject,void (*func)(void*,int, const char*)) {
  m_uiObject = uiObject;
  m_updateFunc = func;
  if(m_uiObject && m_updateFunc)
    m_showProgress = true;
}
*/

void fileManager::updateProgress(int value) {
  m_showProgress.emit(value);
}

sigc::signal<void(int)> fileManager::signalProgress() {
  return m_showProgress;
}
