/***************************************************************************
 *   hdf5manager.cpp                                                       *
 *   Copyright (C) 2014 by Daniel Suson                                    *
 *   daniel.suson@purduecal.edu                                            *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU General Public License     *
 *   along with this program; if not, write to the                         *
 *   Free Software Foundation, Inc.,                                       *
 *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
 *                                                                         *
 *   In addition, as a special exception, the copyright holders give       *
 *   permission to link the code of this program with any edition of       *
 *   the Qt library by Trolltech AS, Norway (or with modified versions     *
 *   of Qt that use the same license as Qt), and distribute linked         *
 *   combinations including the two.  You must obey the GNU General        *
 *   Public License in all respects for all of the code used other than    *
 *   Qt.  If you modify this file, you may extend this exception to        *
 *   your version of the file, but you are not obligated to do so.  If     *
 *   you do not wish to do so, delete this exception statement from        *
 *   your version.                                                         *
 ***************************************************************************
 * Description:                                                            *
 *                                                                         *
 * This header provides the definitions for various enumerated lists used  *
 * by the data classes.                                                    *
 * ----------------------- Change Log ------------------------------------ *
 * Date    Name         Description                                        *
 *                                                                         *
 ***************************************************************************
 * This software evolved from work that was done by Eric Hivon at the      *
 * California Institute of Technology on the MASTER algorithm (Hivon, E.,  *
 * et al., ApJ, vol 567, p 2).  It adapts or interfaces with these         *
 * packages:                                                               *
 *                                                                         *
 * HealPix         (http://www.eso.org/science/healpix/)                   *
 * FTOOLS & FITSIO (http://heasarc.gsfc.nasa.gov/docs/corp/software.html)  *
 *                                                                         *
 * Any publications or presentations that use results generated by this    *
 * program must reference the fact that it was developed by Daniel Suson   *
 ***************************************************************************/
#include <string.h>
#include <H5Cpp.h>

#include "hdf5manager.h"
#include "basedata.h"
#include "association.h"
#include <math.h>
#include "pixelizer.h"
#include "transformer.h"

HDF5Manager::HDF5Manager(association* dataMgr, const char *filename, FILETYPE dataType, H5RWMode mode)
           : fileManager(dataMgr) {
  *hdf5_err = 0;
  s_association = dataMgr;

  if (!filename) {
    m_err = fileInvalidError;
    s_association->errorValue(m_err);
    throw m_err;
  }

  H5::Exception::dontPrint();
  try
  {
    m_ptr = new H5::H5File(filename, H5RWMode::RDWR);
  }
  catch(H5::Exception& err)
  {
    try
    {
      m_ptr = new H5::H5File(filename, H5RWMode::TRUNCATE);
    }
    catch (H5::Exception& err)
    {
      m_err = fileFitsError;
      snprintf(hdf5_err,HDF5_ERR_LEN,"%s",err.getCDetailMsg());
      m_errDetail = errorText[abs(m_err)] + ": " + std::string(hdf5_err);
      s_association->errorValue(m_err);
      s_association->errorDetails(m_errDetail);
      throw m_err;
    }
  }

  try
  {
    H5Complex->insertMember("real", 0, *H5Double);
    H5Complex->insertMember("imag", sizeof(H5Double), *H5Double);
  }
  catch(H5::Exception& err)
  {
    m_err = fileFitsError;
    snprintf(hdf5_err, HDF5_ERR_LEN, "%s", err.getCDetailMsg());
    m_errDetail = errorText[abs(m_err)];
    s_association->errorValue(m_err);
    s_association->errorDetails(m_errDetail);

    throw m_err;
  }

  m_fileDataType = dataType;
  fileName(filename);
  m_fileFormat = HDF5;
}

HDF5Manager::HDF5Manager(association* dataMgr, const char *filename, baseData *data)
           : fileManager(dataMgr) {
  *hdf5_err = 0;
  s_association = dataMgr;

  if (!data || !filename) {
    m_err = fileInvalidError;
    s_association->errorValue(m_err);
    throw m_err;
  }

  H5::Exception::dontPrint();
  try
  {
    m_ptr = new H5::H5File(filename, H5RWMode::RDWR);
  }
  catch(H5::Exception& err)
  {
    try
    {
      m_ptr = new H5::H5File(filename, H5RWMode::TRUNCATE);
    }
    catch (H5::Exception& err)
    {
      m_err = fileFitsError;
      snprintf(hdf5_err,HDF5_ERR_LEN,"%s",err.getCDetailMsg());
      m_errDetail = errorText[abs(m_err)] + ": " + std::string(hdf5_err);
      s_association->errorValue(m_err);
      s_association->errorDetails(m_errDetail);
      throw m_err;
    }
  }

  try
  {
    H5Complex->insertMember("real", 0, *H5Double);
    H5Complex->insertMember("imag", sizeof(H5Double), *H5Double);
  }
  catch(H5::Exception& err)
  {
    m_err = fileFitsError;
    snprintf(hdf5_err, HDF5_ERR_LEN, "%s", err.getCDetailMsg());
    m_errDetail = errorText[abs(m_err)];
    s_association->errorValue(m_err);
    s_association->errorDetails(m_errDetail);

    throw m_err;
  }

  fileName(filename);
  m_fileDataType = data->dataType();
  m_fileFormat   = HDF5;
  m_observatory  = Analyzer;
  m_cols         = data->cols();
  m_rows         = data->rows();
  m_slices       = data->slices();
  /*
  switch (m_fileDataType) {
      case fileType::Null:
      m_err = fileInvalidError;
      s_association->errorValue(m_err);
      throw m_err;
    case fileType::InputData:
    case fileType::InputWeights:
    case fileType::WeightedData:
    case fileType::InputNoise:
    case fileType::InputFilter:
    case fileType::InputBeam:
    case fileType::BinCouplingMatrix:
    case fileType::ModeCouplingMatrix:
    case fileType::InverseBinMatrix:
    case fileType::InverseModeMatrix:
      m_dimensions = 2;
      m_parts = 1;
      //m_fitsType = fitsDouble;
      if (!saveBase(filename)) {
        m_err = fileFitsError;
        m_errDetail = errorText[abs(m_err)] + ": " +  std::string(hdf5_err);
        s_association->errorValue(m_err);
        s_association->errorDetails(m_errDetail);
        throw m_err;
      }
      if (!saveMatrixD((matrixData<double>*)data)) {
//      if (!saveMatrixD(m_fileDataType)) {
        m_err = fileFitsError;
        m_errDetail = errorText[abs(m_err)] + ": " + std::string(hdf5_err);
        s_association->errorValue(m_err);
        s_association->errorDetails(m_errDetail);
        throw m_err;
      }
      break;
    case fileType::AlmData:
    case fileType::AlmWeights:
    case fileType::AlmNoise:
    case fileType::AlmFilter:
    case fileType::AlmBeam:
      m_dimensions = 4;
      m_parts = 2;
      //m_fitsType = fitsDouble;
      if (!saveBase(filename)) {
        m_err = fileFitsError;
        m_errDetail = errorText[abs(m_err)] + ": " + std::string(hdf5_err);
        s_association->errorValue(m_err);
        s_association->errorDetails(m_errDetail);
        throw m_err;
      }
      if (!saveCubeCD((cubeData<complex<double> >*)data)) {
//      if (!saveCubeCD(m_fileDataType)) {
        m_err = fileFitsError;
        m_errDetail = errorText[abs(m_err)] + ": " + std::string(hdf5_err);
        s_association->errorValue(m_err);
        s_association->errorDetails(m_errDetail);
        throw m_err;
      }
      break;
    case fileType::PixelOccupancy:
      m_dimensions = 1;
      m_parts = 1;
      //m_fitsType = fitsInt32;
      if (!saveBase(filename)) {
        m_err = fileFitsError;
        m_errDetail = errorText[abs(m_err)] + ": " + std::string(hdf5_err);
        s_association->errorValue(m_err);
        s_association->errorDetails(m_errDetail);
        throw m_err;
      }
      if (!saveVectorI((vectorData<int>*)data)) {
//      if (!saveVectorI(m_fileDataType)) {
        m_err = fileFitsError;
        m_errDetail = errorText[abs(m_err)] + ": " + std::string(hdf5_err);
        s_association->errorValue(m_err);
        s_association->errorDetails(m_errDetail);
        throw m_err;
      }
      break;
    default:
      m_dimensions = 1;
      m_parts = 1;
      //m_fitsType = fitsDouble;
      if (!saveBase(filename)) {
        m_err = fileFitsError;
        m_errDetail = errorText[abs(m_err)] + ": " + std::string(hdf5_err);
        s_association->errorValue(m_err);
        s_association->errorDetails(m_errDetail);
        throw m_err;
      }
      if (!saveVectorD((vectorData<double>*)data)) {
//      if (!saveVectorD(m_fileDataType)) {
        m_err = fileFitsError;
        m_errDetail = errorText[abs(m_err)] + ": " + std::string(hdf5_err);
        s_association->errorValue(m_err);
        s_association->errorDetails(m_errDetail);
        throw m_err;
      }
      break;
  }
  */
}

HDF5Manager::HDF5Manager(HDF5Manager* from)
           : fileManager(from) {
  m_ptr =      from->filePtr();
  //m_fitsType = from->fitsType();
}

HDF5Manager::~HDF5Manager() {
  if (m_ptr) {
    delete m_ptr;
    m_ptr = 0;
  }
}

bool HDF5Manager::saveBase(const char* filename, int* numTypes, FILETYPE* dataTypes)
{
  std::string text, comment = "Analyzer";

  if(!m_ptr)
  {
    try
    {
      m_ptr = new H5::H5File(filename, H5RWMode::RDWR);
    }
    catch(H5::Exception& err)
    {
      try
      {
        m_ptr = new H5::H5File(filename, H5RWMode::TRUNCATE);
      }
      catch (H5::Exception& err)
      {
        m_err = fileFitsError;
        snprintf(hdf5_err,HDF5_ERR_LEN,"%s",err.getCDetailMsg());
        m_errDetail = errorText[abs(m_err)] + ": " + std::string(hdf5_err);
        s_association->errorValue(m_err);
        s_association->errorDetails(m_errDetail);
        return false;
      }
    }
  }

  /* All data saved will be tagged as "Analyzer" data. In memory
     data generated from other observatories will be noted as such in
     the FITS comment section... */
  if(m_observatory >= OBSERVATORY_LIMIT)
    m_observatory = Analyzer;

  if (m_observatory != Analyzer) {
    text = observatoryNames[(int)m_observatory];
    comment += "\tCompiled from ";
    comment += text;
    comment += " data file.";
    m_observatory = Analyzer;
  }

  FILETYPE dataType = fileType::Null;

  int numDims = 2;
  hsize_t dims[numDims];
  dims[0] = 2;
  dims[1] = (*numTypes) + 1;

  //const char* infoData[dims[0]][dims[1]];
  //infoData[0][0] = "TELESCOPE";
  //infoData[1][0] = comment.c_str();

  int offset = dims[1];
  const char** infoData = new const char*[dims[0]*dims[1]];
  infoData[0] = "TELESCOPE";
  infoData[offset] = comment.c_str();
  for(int i = 0; i < *numTypes; i += 1)
  {
    infoData[i+1] = "DATA STEP";
    infoData[offset + i + 1] = (dataTypeNames[static_cast<int>(dataTypes[i])]).c_str();
    //infoData[0][i+1] = "Data Step";
    //infoData[1][i+1] = (dataTypeNames[static_cast<int>(dataTypes[i])]).c_str();
  }

  // save the info first
  try
  {
    if(!m_ptr->exists(infoGroupName))
      infoGroup = new H5::Group(m_ptr->createGroup(infoGroupName));
    else
      infoGroup = new H5::Group(m_ptr->openGroup(infoGroupName));

    if(infoGroup->exists("PRIMARY"))
      infoGroup->unlink("PRIMARY"); // essentially deletes PRIMARY dataset

    currInfoDataSpace = new H5::DataSpace(numDims, dims);
    currInfoDataSet   = new H5::DataSet(infoGroup->createDataSet("PRIMARY", *H5String, *currInfoDataSpace));
    currInfoDataSet->write(infoData, *H5String, *currInfoDataSpace);

    currInfoDataSpace->close();
    currInfoDataSet->close();
  }
  catch (H5::Exception& err) {
    snprintf(hdf5_err,HDF5_ERR_LEN,"%s",err.getCDetailMsg());
    m_err = fileFitsError;
    m_errDetail = errorText[abs(m_err)] + ": " + std::string(hdf5_err);
    return false;
  }

  // build the info tree structure
 try
 {
    if(!infoGroup->exists("DATA"))
      infoGroup->createGroup("DATA");

    if(!infoGroup->exists("WEIGHTS"))
      infoGroup->createGroup("WEIGHTS");

    if(!infoGroup->exists("WEIGHTED"))
      infoGroup->createGroup("WEIGHTED");

    if(!infoGroup->exists("NOISE"))
      infoGroup->createGroup("NOISE");

    if(!infoGroup->exists("FILTER"))
      infoGroup->createGroup("FILTER");

    if(!infoGroup->exists("BEAM"))
      infoGroup->createGroup("BEAM");

    if(!infoGroup->exists("OCCUPANCY"))
      infoGroup->createGroup("OCCUPANCY");

    if(!infoGroup->exists("SPECTRUM"))
      infoGroup->createGroup("SPECTRUM");
  }
  catch (H5::Exception& err) {
    snprintf(hdf5_err,HDF5_ERR_LEN,"%s",err.getCDetailMsg());
    m_err = fileFitsError;
    m_errDetail = errorText[abs(m_err)] + ": " + std::string(hdf5_err);
    return false;
  }

  // build the data tree structure
  try
  {
    if(!m_ptr->exists(dataGroupName))
      dataGroup = new H5::Group(m_ptr->createGroup(dataGroupName));
    else
      dataGroup = new H5::Group(m_ptr->openGroup(dataGroupName));

    if(!dataGroup->exists("DATA"))
      dataGroup->createGroup("DATA");

    if(!dataGroup->exists("WEIGHTS"))
      dataGroup->createGroup("WEIGHTS");

    if(!dataGroup->exists("WEIGHTED"))
      dataGroup->createGroup("WEIGHTED");

    if(!dataGroup->exists("NOISE"))
      dataGroup->createGroup("NOISE");

    if(!dataGroup->exists("FILTER"))
      dataGroup->createGroup("FILTER");

    if(!dataGroup->exists("BEAM"))
      dataGroup->createGroup("BEAM");

    if(!dataGroup->exists("OCCUPANCY"))
      dataGroup->createGroup("OCCUPANCY");

    if(!dataGroup->exists("SPECTRUM"))
      dataGroup->createGroup("SPECTRUM");
  }
  catch (H5::Exception& err) {
    snprintf(hdf5_err,HDF5_ERR_LEN,"%s",err.getCDetailMsg());
    m_err = fileFitsError;
    m_errDetail = errorText[abs(m_err)] + ": " + std::string(hdf5_err);
    return false;
  }

  return true;
}

void HDF5Manager::save(int* numTypes, FILETYPE* dataTypes)
{
  m_fileFormat = HDF5;

  fileManager::save(numTypes, dataTypes);

  currInfoGroup->close();
  currDataGroup->close();
  infoGroup->close();
  dataGroup->close();

  m_ptr->close();
  return;
}

void HDF5Manager::save(ASSOCIATEDMAP map)
{
}

void HDF5Manager::save(ASSOCIATEDSPECTRUM spect)
{
}

bool HDF5Manager::writeComments(const char ** comments, int size, void* dest)
{
  H5::Group* infoGroup = (H5::Group*) dest;
  string dataName = dataSetName(m_fileDataType);

  try
  {
    if(infoGroup->exists(dataName))
      infoGroup->unlink(dataName);

    int numInfoDims = 2;
    hsize_t infoDims[numInfoDims];
    infoDims[0] = 2;
    infoDims[1] = size/2;

    H5::DataSpace* currInfoDataSpace = new H5::DataSpace(numInfoDims, infoDims);
    H5::DataSet*   currInfoDataSet   = new H5::DataSet(currInfoGroup->createDataSet(dataName, *H5String, *currInfoDataSpace));

    currInfoDataSet->write(comments, *H5String, *currInfoDataSpace);

    currInfoDataSpace->close();
    currInfoDataSet->close();

    return true;
  }
  catch (H5::Exception& err) {
    snprintf(hdf5_err,HDF5_ERR_LEN,"%s",err.getCDetailMsg());
    m_err = fileFitsError;
    m_errDetail = errorText[abs(m_err)] + ": " + std::string(hdf5_err);
    return false;
  }
}

bool HDF5Manager::readComments(void* src)
{
  string dataName = dataSetName(m_fileDataType);

  char** infoData;
  hsize_t* infoDims;
  try
  {
    currInfoDataSet = new H5::DataSet(currInfoGroup->openDataSet(dataName));
    currInfoDataSpace = new H5::DataSpace(currInfoDataSet->getSpace());

    int numInfoDims = currInfoDataSpace->getSimpleExtentNdims();
    infoDims = new hsize_t[numInfoDims];

    currInfoDataSpace->getSimpleExtentDims(infoDims, NULL);

    infoData = new char*[infoDims[0] * infoDims[1]];
    currInfoDataSet->read(infoData, *H5String, *currInfoDataSpace);

    for(int keyIndex = 0; keyIndex < infoDims[1]; keyIndex += 1)
      (*m_commentMap)[infoData[keyIndex]] = infoData[keyIndex+infoDims[1]];

    return true;
  }
  catch (H5::Exception& err) {
    snprintf(hdf5_err,HDF5_ERR_LEN,"%s",err.getCDetailMsg());
    m_err = fileFitsError;
    m_errDetail = errorText[abs(m_err)] + ": " + std::string(hdf5_err);
    return 0;
  }

}

bool HDF5Manager::getGroups()
{
  try
  {
    if(infoGroup == 0)
      infoGroup = new H5::Group(m_ptr->openGroup(infoGroupName));

    if(dataGroup == 0)
      dataGroup = new H5::Group(m_ptr->openGroup(dataGroupName));

    switch(m_fileDataType)
    {
      case fileType::InputData:
      case fileType::PixelizedData:
      case fileType::InverseData:
      case fileType::TransformedData:
      case fileType::AlmData:
      {
        currInfoGroup = new H5::Group(infoGroup->openGroup("DATA"));
        currDataGroup = new H5::Group(dataGroup->openGroup("DATA"));
        return true;
      }
      case fileType::InputWeights:
      case fileType::PixelizedWeights:
      case fileType::InverseWeights:
      case fileType::TransformedWeights:
      case fileType::AlmWeights:
      {
        currInfoGroup = new H5::Group(infoGroup->openGroup("WEIGHTS"));
        currDataGroup = new H5::Group(dataGroup->openGroup("WEIGHTS"));
        return true;
      }
      case fileType::InputNoise:
      case fileType::PixelizedNoise:
      case fileType::InverseNoise:
      case fileType::TransformedNoise:
      case fileType::AlmNoise:
      {
        currInfoGroup = new H5::Group(infoGroup->openGroup("NOISE"));
        currDataGroup = new H5::Group(dataGroup->openGroup("NOISE"));
        return true;
      }
      case fileType::InputFilter:
      case fileType::PixelizedFilter:
      case fileType::InverseFilter:
      case fileType::TransformedFilter:
      case fileType::AlmFilter:
      {
        currInfoGroup = new H5::Group(infoGroup->openGroup("FILTER"));
        currDataGroup = new H5::Group(dataGroup->openGroup("FILTER"));
        return true;
      }
      case fileType::InputBeam:
      case fileType::PixelizedBeam:
      case fileType::InverseBeam:
      case fileType::TransformedBeam:
      case fileType::AlmBeam:
      {
        currInfoGroup = new H5::Group(infoGroup->openGroup("BEAM"));
        currDataGroup = new H5::Group(dataGroup->openGroup("BEAM"));
        return true;
      }
      case fileType::WeightedData:
      case fileType::InputWeightedNoise:
      case fileType::WeightedPixel:
      case fileType::PixelizedWeightedNoise:
      case fileType::WeightedInverse:
      case fileType::InverseWeightedNoise:
      case fileType::WeightedTransform:
      case fileType::TransformedWeightedNoise:
      case fileType::WeightedAlm:
      case fileType::AlmWeightedNoise:

      {
        currInfoGroup = new H5::Group(infoGroup->openGroup("WEIGHTED"));
        currDataGroup = new H5::Group(dataGroup->openGroup("WEIGHTED"));
        return true;
      }
      case fileType::EnsembleIterationSpectrum:
      case fileType::EnsembleIterationNoise:
      case fileType::ModeModeMatrix:
      case fileType::InverseModeModeMatrix:
      case fileType::InstrumentEffectsMatrix:
      case fileType::InverseInstrumentEffectsMatrix:
      case fileType::BinningMatrix:
      case fileType::UnbinningMatrix:
      case fileType::BinnedInstrumentEffectsMatrix:
      case fileType::InverseBinnedInstrumentMatrix:
      case fileType::EnsembleAveragedSpectrum:
      case fileType::EnsembleAveragedNoise:
      case fileType::ExtrapolatedSpectrum:
      case fileType::ExtrapolatedInstrumentSpectrum:
      case fileType::BinnedSpectrum:
      case fileType::BinnedExtrapolatedSpectrum:
      case fileType::BinnedExtrapolatedInstrumentedSpectrum:
      {
        currInfoGroup = new H5::Group(infoGroup->openGroup("SPECTRUM"));
        currDataGroup = new H5::Group(dataGroup->openGroup("SPECTRUM"));
      }
      default:
        return false;
    }
  }
  catch(H5::Exception& err)
  {
    snprintf(hdf5_err,HDF5_ERR_LEN,"%s",err.getCDetailMsg());
    m_err = fileFitsError;
    m_errDetail = errorText[abs(m_err)] + ": " + std::string(hdf5_err);
    return false;
  }
}


bool HDF5Manager::saveVectorI(vectorData<int> *v)
{
  unsigned long long int numOps, updateUnit, currOp;

  string nsides = std::to_string(v->sides());
  string layout = std::to_string(static_cast<int>(v->layout()));
  string scheme = std::to_string(static_cast<int>(v->pixelScheme()));
  string minVal = std::to_string(v->minValue());
  string maxVal = std::to_string(v->maxValue());

  int numInfoDims = 2;
  hsize_t infoDims[numInfoDims];
  infoDims[0] = 2;
  infoDims[1] = 5;

  const char* infoData[2][5] = {{"NSIDES",       "PIXLAYOUT",    "PIXSCHEME",    "PIXMINVALUE",     "PIXMAXVALUE"},
                                {nsides.c_str(), layout.c_str(), scheme.c_str(), minVal.c_str(), maxVal.c_str()}};

  try
  {
    currInfoGroup     = new H5::Group(infoGroup->openGroup("OCCUPANCY"));

    if(currInfoGroup->exists("OCCUPANCY"))
      currInfoGroup->unlink("OCCUPANCY");

    currInfoDataSpace = new H5::DataSpace(numInfoDims, infoDims);
    currInfoDataSet   = new H5::DataSet(currInfoGroup->createDataSet("OCCUPANCY", *H5String, *currInfoDataSpace));

    currInfoDataSet->write(infoData, *H5String, *currInfoDataSpace);

    currInfoDataSpace->close();
    currInfoDataSet->close();
  }
  catch (H5::Exception& err) {
    snprintf(hdf5_err,HDF5_ERR_LEN,"%s",err.getCDetailMsg());
    m_err = fileFitsError;
    m_errDetail = errorText[abs(m_err)] + ": " + std::string(hdf5_err);
    return false;
  }

 numOps = m_rows;
  updateUnit = numOps / 100;
  if(updateUnit < 1)
    updateUnit = 1;
  currOp = 0;

  int numDataDims = 1;
  hsize_t dataDims[numDataDims];
  dataDims[0] = m_rows;

  int* data = new int[m_rows];
  for (int row = 0; row < m_rows; row++) {
    data[row] = (*v)[row];
    currOp++;
//    if(m_showProgress && !(currOp % updateUnit))
//      informProgress(currOp / updateUnit);
  }

  try
  {
    currDataGroup = new H5::Group(dataGroup->openGroup("OCCUPANCY"));

    if(currDataGroup->exists("OCCUPANCY"))
      currDataGroup->unlink("OCCUPANCY");

    currDataDataSpace = new H5::DataSpace(numDataDims, dataDims);
    currDataDataSet   = new H5::DataSet(currDataGroup->createDataSet("OCCUPANCY", *H5Int32, *currDataDataSpace));

    currDataDataSet->write(data, *H5Int32, *currDataDataSpace);

    currDataDataSpace->close();
    currDataDataSet->close();
  }
  catch (H5::Exception& err) {
    snprintf(hdf5_err,HDF5_ERR_LEN,"%s",err.getCDetailMsg());
    m_err = fileFitsError;
    m_errDetail = errorText[abs(m_err)] + ": " + std::string(hdf5_err);
    return false;
  }


  if (m_err != noErrors) {
    m_err = incompleteTableWrittenError;
    s_association->errorValue(m_err);
    return false;
  }

  return true;
}

bool HDF5Manager::saveVectorD(vectorData<double> *v)
{
  unsigned long long int numOps, updateUnit, currOp;
  std::string dataName = dataSetName(m_fileDataType);
  getGroups();

  int infoSize = 0;
  const char** infoData = createInfoArray(m_fileDataType, &infoSize);
  writeComments(infoData, infoSize, currInfoGroup);

  numOps = m_rows;
  updateUnit = numOps / 100;
  if(updateUnit < 1)
    updateUnit = 1;
  currOp = 0;

  int numDataDims = 1;
  hsize_t dataDims[numDataDims];
  dataDims[0] = m_rows;

  double* data = new double[m_rows];
  for (int row = 0; row < m_rows; row++) {
    data[row] = (*v)[row];
    currOp++;
//    if(m_showProgress && !(currOp % updateUnit))
//      informProgress(currOp / updateUnit);
  }

  try
  {
    if(currDataGroup->exists(dataName))
      currDataGroup->unlink(dataName);

    currDataDataSpace = new H5::DataSpace(numDataDims, dataDims);
    currDataDataSet   = new H5::DataSet(currDataGroup->createDataSet(dataName, *H5Double, *currDataDataSpace));

    currDataDataSet->write(data, *H5Double, *currDataDataSpace);

    currDataDataSpace->close();
    currDataDataSet->close();
  }
  catch (H5::Exception& err) {
    snprintf(hdf5_err,HDF5_ERR_LEN,"%s",err.getCDetailMsg());
    m_err = fileFitsError;
    m_errDetail = errorText[abs(m_err)] + ": " + std::string(hdf5_err);
    return false;
  }

  if (m_err != noErrors) {
    m_err = incompleteTableWrittenError;
    s_association->errorValue(m_err);
    return false;
  }

  return true;
}

bool HDF5Manager::saveMatrixD(matrixData<double> *m)
{
  unsigned long long int numOps, updateUnit, currOp;
  std::string dataName = dataSetName(m_fileDataType);
  getGroups();

  int infoSize = 0;
  const char** infoData = createInfoArray(m_fileDataType, &infoSize);
  writeComments(infoData, infoSize, currInfoGroup);

  numOps = m_cols * m_rows;
  updateUnit = numOps / 100;
  if(updateUnit < 1)
    updateUnit = 1;
  currOp = 0;

  int numDataDims = 2;
  hsize_t dataDims[2];

  dataDims[0] = m_rows;
  dataDims[1] = m_cols;

  double* data = new double[m_rows * m_cols];
  for(int r = 0; r < m_rows; r += 1)
    for(int c = 0; c < m_cols; c += 1)
      data[r * m_cols + c] = (*m)[c][r];

  try
  {
    if(currDataGroup->exists(dataName))
      currDataGroup->unlink(dataName);

    currDataDataSpace = new H5::DataSpace(numDataDims, dataDims);
    currDataDataSet   = new H5::DataSet(currDataGroup->createDataSet(dataName, *H5Double, *currDataDataSpace));

    currDataDataSet->write(data, *H5Double, *currDataDataSpace);

    currDataDataSpace->close();
    currDataDataSet->close();
  }
  catch (H5::Exception& err) {
    snprintf(hdf5_err,HDF5_ERR_LEN,"%s",err.getCDetailMsg());
    m_err = fileFitsError;
    m_errDetail = errorText[abs(m_err)] + ": " + std::string(hdf5_err);
    s_association->errorValue(m_err);
    s_association->errorDetails(m_errDetail);
    return false;
  }

  if (m_err != noErrors) {
    m_err = incompleteTableWrittenError;
    s_association->errorValue(m_err);
    return false;
  }

  return true;
}

bool HDF5Manager::saveCubeCD(cubeData<complex<double> > *c)
{
  unsigned long long int numOps, updateUnit, currOp;
  std::string dataName = dataSetName(m_fileDataType);
  getGroups();

  int infoSize = 0;
  const char** infoData = createInfoArray(m_fileDataType, &infoSize);
  writeComments(infoData, infoSize, currInfoGroup);

  std::vector<std::vector<std::vector<complex<double> > > > dataAccess = c->roAccess();

  numOps = m_slices * m_rows * m_cols;
  updateUnit = numOps / 100;
  if(updateUnit < 1)
    updateUnit = 1;
  currOp = 0;

  int numDataDims = 3;
  hsize_t dataDims[3];
  dataDims[0] = m_slices;
  dataDims[1] = m_rows;
  dataDims[2] = m_cols;

  complex<double>* data = new complex<double>[m_slices * m_rows * m_cols];
  /*
  for(int slice = 0; slice < m_slices; slice += 1)
  {
    data[slice] = new complex<double>*[m_rows];
    for(int row = 0; row < m_rows; row += 1)
      data[slice][row] = new complex<double>[m_cols];
  }
  */

  for(int slice = 0; slice < m_slices; slice += 1)
  {
    for(int row = 0; row < m_rows; row += 1)
    {
      for(int col = 0; col < m_cols; col += 1)
        data[slice * m_rows * m_cols + row * m_cols + col] = complex<double>( (*c)[slice][col][row].real(),
                                                                              (*c)[slice][col][row].imag());
        //data[slice][row][col].real(dataAccess[slice][col][row].real());

    }
  }

  try
  {
    if(currDataGroup->exists(dataName))
      currDataGroup->unlink(dataName);

    currDataDataSpace = new H5::DataSpace(numDataDims, dataDims);
    currDataDataSet   = new H5::DataSet(currDataGroup->createDataSet(dataName, *H5Complex, *currDataDataSpace));

    currDataDataSet->write(data, *H5Complex, *currDataDataSpace);

    currDataDataSpace->close();
    currDataDataSet->close();
  }
  catch (H5::Exception& err)
  {
    snprintf(hdf5_err,HDF5_ERR_LEN,"%s",err.getCDetailMsg());
    m_err = fileFitsError;
    m_errDetail = errorText[abs(m_err)] + ": " + std::string(hdf5_err);
    s_association->errorValue(m_err);
    s_association->errorDetails(m_errDetail);
    return false;
  }

  if (m_err != noErrors) {
    m_err = incompleteTableWrittenError;
    s_association->errorValue(m_err);
    return false;
  }

  return true;
}

bool HDF5Manager::getHeaders(int hdrNum)
{
  return false;
}

FILETYPE* HDF5Manager::getHeaders(int* numTypes)
{
  char** data;
  hsize_t* dims;

  *numTypes = 0;
  FILETYPE* dataTypes;

  if(m_observatory == Analyzer)
  {
    try
    {
        dataGroup = new H5::Group(m_ptr->openGroup(dataGroupName));

        infoGroup = new H5::Group(m_ptr->openGroup(infoGroupName));
        currInfoDataSet = new H5::DataSet(infoGroup->openDataSet("PRIMARY"));
        currInfoDataSpace = new H5::DataSpace(currInfoDataSet->getSpace());

        int numDims = currInfoDataSpace->getSimpleExtentNdims();
        dims = new hsize_t[numDims];

        currInfoDataSpace->getSimpleExtentDims(dims, NULL);

        data = new char*[ dims[0] * dims[1]];
        currInfoDataSet->read(data, *H5String, *currInfoDataSpace);
    }
    catch (H5::Exception& err) {
      snprintf(hdf5_err,HDF5_ERR_LEN,"%s",err.getCDetailMsg());
      m_err = fileFitsError;
      m_errDetail = errorText[abs(m_err)] + ": " + std::string(hdf5_err);
      return 0;//false;
    }
    catch(...)
    {
      currInfoDataSpace->close();
      currInfoDataSet->close();
      currInfoGroup->close();
      infoGroup->close();
      m_ptr->close();
    }

    string telescope(data[dims[1]]);

    if(telescope.find("\t") < telescope.size())
      telescope = telescope.substr(0, telescope.find("\t"));

    OBSERVATORY obsType = Unknown;
    int obsValue = (int)Unknown;
    while (obsType < OBSERVATORY_LIMIT) {
      obsType = static_cast<OBSERVATORY>(obsValue);
      if (telescope == observatoryNames[obsValue])
        break;
      obsValue++;
    }
    m_observatory = obsType;
    m_fileDataType = fileType::InputData;

    *numTypes = dims[1]-1;
    dataTypes = new FILETYPE[*numTypes];

    for(int dataIndex = 0; dataIndex < dims[1]-1; dataIndex += 1)
    {
      for(int nameIndex = 0; nameIndex < static_cast<int>(fileType::FILETYPE_LIMIT); nameIndex += 1)
      {
        int offset = dims[1];
        if(data[offset + dataIndex + 1] == dataTypeNames[nameIndex])
          dataTypes[dataIndex] = static_cast<FILETYPE>(nameIndex);
      }
    }

    delete[] data;
  }
  else if(m_observatory == Gadget)
  {
    dataTypes = new FILETYPE[1];
    dataTypes[0] = fileType::InputData;
    *numTypes = 1;
  }

  if (m_observatory == OBSERVATORY_LIMIT) {
    m_err = fileNoKeyError;
    m_errDetail = errorText[abs(m_err)] + ": Observatory not recognized";
    s_association->errorValue(m_err);
    s_association->errorDetails(m_errDetail);
    return 0;//false;
  }

  return dataTypes;
}

void HDF5Manager::open()
{
  return;
}

bool HDF5Manager::getDataType()
{
  return false;
}

bool HDF5Manager::getDimensions()
{
  return false;
}

bool HDF5Manager::getEnergy()
{
  return false;
}


baseData *HDF5Manager::data()
{
  if (!m_ptr)
    return 0;

  if(m_observatory == Gadget)
    return gadgetData();
  else
  {
    switch (m_fileDataType) {
      case fileType::Null:
        return 0;
      case fileType::InputData:
      case fileType::InputWeights:
      case fileType::WeightedData:
      case fileType::InputNoise:
      case fileType::InputWeightedNoise:
      case fileType::InputFilter:
      case fileType::InputBeam:
        if (m_observatory != Analyzer)
          return data(m_minSlice,m_maxSlice);
      /*
      case fileType::WeightedData:
      case fileType::BinCouplingMatrix:
      case fileType::ModeCouplingMatrix:
      case fileType::InverseBinMatrix:
      case fileType::InverseModeMatrix:
      */
      case fileType::EnsembleIterationNoise:
      case fileType::EnsembleIterationSpectrum:
      //case fileType::EnsembleIterationBinnedSpectrum:
      case fileType::ModeModeMatrix:
      case fileType::InverseModeModeMatrix:
      case fileType::InstrumentEffectsMatrix:
      case fileType::InverseInstrumentEffectsMatrix:
      case fileType::BinningMatrix:
      case fileType::UnbinningMatrix:
      case fileType::BinnedInstrumentEffectsMatrix:
      case fileType::InverseBinnedInstrumentMatrix:
        return getMatrixD();
      case fileType::AlmData:
      case fileType::AlmWeights:
      case fileType::WeightedAlm:
      case fileType::AlmNoise:
      case fileType::AlmWeightedNoise:
      case fileType::AlmFilter:
      case fileType::AlmBeam:
        return getCubeCD();
      case fileType::PixelOccupancy:
        return getVectorI();
      default:
        return getVectorD();
    }
  }

  return 0;
}

inputMatrixData *HDF5Manager::data(int slice_min, int slice_max)
{
  /*
  std::valarray<double> fitsData;
  inputMatrixData* in_mat;
  long span, n, begin;
  std::string hduName = "";
  std::vector<string> colName(m_cols,"");
  const std::string cols = "COLUMN-";
  double ra_res = 0, dec_res = 0;
  unsigned long long int numOps, updateUnit, currOp;

  if (!m_ptr) {
    m_err = fileFitsError;
    m_errDetail = errorText[abs(m_err)] + ": No CCfits pointer";
    s_association->errorValue(m_err);
    s_association->errorDetails(m_errDetail);
    return 0;
  }
  if (!(m_observatory == Egret || m_observatory == Fermi)) {
    m_err = fileSliceError;
    m_errDetail = errorText[abs(m_err)] + ": No slices in file";
    s_association->errorValue(m_err);
    s_association->errorDetails(m_errDetail);
    return 0;
  }
  if (slice_min < 0 || slice_max < 0) {
    m_err = fileSliceError;
    m_errDetail = errorText[abs(m_err)] + ": Minimum slice number or maximum slice number less than 0";
    s_association->errorValue(m_err);
    s_association->errorDetails(m_errDetail);
    return 0;
  }
  if (slice_min > m_slices || slice_max > m_slices) {
    m_err = fileSliceError;
    m_errDetail = errorText[abs(m_err)] + ": Slice number is greater than the available slices";
    s_association->errorValue(m_err);
    s_association->errorDetails(m_errDetail);
    return 0;
  }
  if (slice_min > slice_max) {
    m_err = fileFitsError;
    m_errDetail = errorText[abs(m_err)] + ": Minimum slice number greater than maximum slice number";
    s_association->errorValue(m_err);
    s_association->errorDetails(m_errDetail);
    return 0;
  }

  span  = slice_max - slice_min + 1;
  n     = span * m_cols * m_rows;
  begin = slice_min * m_cols * m_rows + 1;

  // set appropriate hdu name to identify extension
  switch (m_fileDataType) {
    case fileType::InputData:
      hduName = "RAW_DATA";
      break;
    case fileType::InputWeights:
      hduName = "RAW_MASK";
      break;
    case fileType::WeightedData:
      hduName = "WEIGHTED_DATA";
      break;
    case fileType::InputNoise:
      hduName = "RAW_NOISE";
      break;
    case fileType::InputFilter:
      hduName = "RAW_FILTER";
      break;
    case fileType::InputBeam:
      hduName = "RAW_BEAM";
      break;
    case fileType::BinCouplingMatrix:
      hduName = "BIN_COUPLING_MATRIX";
      break;
    case fileType::ModeCouplingMatrix:
      hduName = "MODE_COUPLING_MATRIX";
      break;
    case fileType::InverseBinMatrix:
      hduName = "INVERSE_BIN_COUPLING_MATRIX";
      break;
    case fileType::InverseModeMatrix:
      hduName = "INVERSE_MODE_COUPLING_MATRIX";
      break;
  }

  // set column names
  for (int col = 0; col < m_cols; col++)
    colName[col] = cols + std::to_string(col);

  // create data structure for storage
  in_mat = new inputMatrixData(m_cols,m_rows,m_fileDataType);
  in_mat->initialize();

  numOps = m_rows * m_cols;
  updateUnit = numOps / 100;
  if(updateUnit < 1) updateUnit = 1;
  currOp = 0;

  // load data
  try {
    LOAD("CDELT1",ra_res);
    LOAD("CDELT2",dec_res);
    in_mat->RARes(ra_res);
    in_mat->DecRes(dec_res);

    H5::ExtHDU& binTable = m_ptr->extension(hduName);
    for (int col = 0; col < m_cols; ++col) {
      binTable.column(colName[col]).read(fitsData,1,m_rows);
      for (int row = 0; row < m_rows; ++row) {
        (*in_mat)[col][row] = fitsData[row];
        currOp++;
//        if(m_showProgress && !(currOp % updateUnit))
//          informProgress(currOp / updateUnit);
      }
    }
  }
  catch (H5::Exception& err) {
    snprintf(hdf5_err,HDF5_ERR_LEN,"%s",err.getCDetailMsg());
    m_err = fileFitsError;
    m_errDetail = errorText[abs(m_err)] + ": " + std::string(hdf5_err);
    s_association->errorValue(m_err);
    s_association->errorDetails(m_errDetail);
    delete in_mat;
    return 0;
  }

  return in_mat;
  */
  return NULL;
}

inputMatrixData *HDF5Manager::data(float e_min,float e_max)
{
  return NULL;
}

baseData* HDF5Manager::gadgetData()
{
  try
  {
    currDataGroup = new H5::Group(m_ptr->openGroup("PartType1"));
    currDataDataSet = new H5::DataSet(currDataGroup->openDataSet("Coordinates"));
    currDataDataSpace = new H5::DataSpace(currDataDataSet->getSpace());

    int numDims = currDataDataSpace->getSimpleExtentNdims();
    hsize_t* dims1 = new hsize_t[numDims];
    currDataDataSpace->getSimpleExtentDims(dims1, NULL);

    double* coorData = new double[dims1[0] * dims1[1]];
    currDataDataSet->read(coorData, currDataDataSet->getDataType(), *currDataDataSpace);

    // get the box size
    currDataGroup = new H5::Group(m_ptr->openGroup("Header"));
    H5::Attribute* boxSizeAttr = new H5::Attribute(currDataGroup->openAttribute("BoxSize"));
    double* boxSize = new double(0);
    boxSizeAttr->read(boxSizeAttr->getDataType(), boxSize);

    //currDataDataSet = new H5::DataSet(currDataGroup->openDataSet("Velocities"));
    //currDataDataSpace = new H5::DataSpace(currDataDataSet->getSpace());

    //numDims = currDataDataSpace->getSimpleExtentNdims();
    //hsize_t* dims2 = new hsize_t[numDims];
    //currDataDataSpace->getSimpleExtentDims(dims2, NULL);

    //double* velData = new double[dims2[0] * dims2[1]];
    //currDataDataSet->read(velData, currDataDataSet->getDataType(), *currDataDataSpace);


    double minX = INT_MAX, maxX = 0;
    double minY = INT_MAX, maxY = 0;
    double minZ = INT_MAX, maxZ = 0;

    for(int i = 0; i < dims1[0] * dims1[1]; i += 3)
    {
      if(coorData[i+0] < minX)
        minX = coorData[i+0];
      else if(coorData[i+0] > maxX)
        maxX = coorData[i+0];

      if(coorData[i+1] < minY)
        minY = coorData[i+1];
      else if(coorData[i+1] > maxY)
        maxY = coorData[i+1];

      if(coorData[i+2] < minZ)
        minZ = coorData[i+2];
      else if(coorData[i+2] > maxZ)
        maxZ = coorData[i+2];
    }

    double xCenter = (maxX - minX)/2;
    double yCenter = (maxY - minY)/2;
    double zCenter = (maxZ - minZ)/2;


    //double xCenter = *boxSize/2;
    //double yCenter = *boxSize/2;
    //double zCenter = *boxSize/2;

    std::cout << *boxSize << "\n";
    std::cout << xCenter << ", " << yCenter << ", " << zCenter << "\n";

    double minTheta = INT_MAX;
    double minPhi = INT_MAX;
    double minRA = INT_MAX;
    double minDec = INT_MAX;

    double* wrappedData = new double[dims1[0] * dims1[1]];
    double* shiftedData = new double[dims1[0] * dims1[1]];
    double* spherData = new double[dims1[0] * dims1[1]];

    for(int i = 0; i < dims1[0] * dims1[1]; i += 3)
    {
        double origX = coorData[i+0];
        double origY = coorData[i+1];
        double origZ = coorData[i+2];

        double xNumTimesInto = origX > *boxSize ? ((int)(origX / *boxSize)) : 0;
        double yNumTimesInto = origY > *boxSize ? ((int)(origY / *boxSize)) : 0;
        double zNumTimesInto = origZ > *boxSize ? ((int)(origZ / *boxSize)) : 0;

        double origXRem = origX - (xNumTimesInto * *boxSize); // = origX; // = modf(origX, &origXInt);
        double origYRem = origY - (yNumTimesInto * *boxSize); // = origY; // = modf(origY, &origYInt);
        double origZRem = origZ - (zNumTimesInto * *boxSize); // = origZ; // = modf(origZ, &origZInt);

        /*
        while(origXRem > *boxSize)
          origXRem -= *boxSize;

        while(origYRem > *boxSize)
          origYRem -= *boxSize;

        while(origZRem > *boxSize)
          origZRem -= *boxSize;
        */

        wrappedData[i+0] = origX;
                           //origXRem;
        wrappedData[i+1] = origY;
                           //origYRem;
        wrappedData[i+2] = origZ;
                           //origZRem;

        shiftedData[i+0] = wrappedData[i+0] - xCenter;
        shiftedData[i+1] = wrappedData[i+1] - yCenter;
        shiftedData[i+2] = wrappedData[i+2] - zCenter;

        shiftedData[i+0] = coorData[i+0] - xCenter;
        shiftedData[i+1] = coorData[i+1] - yCenter;
        shiftedData[i+2] = coorData[i+2] - zCenter;

        double x = shiftedData[i+0];
        double y = shiftedData[i+1];
        double z = shiftedData[i+2];

        /*
        //double theta, phi, rho;
        //rho = sqrt(x*x + y*y + z*z);
        //theta = atan(y/x);
        //phi = atan(sqrt(x*x + y*y)/z);

        //rho = sqrt(x*x + y*y + z*z);
        //phi = acos(z/rho);
        //theta = acos(x / (rho * sin(phi)));

        // based on
        // where theta = rotation around z
        // and phi = rotation off of z
        // x = r sin(phi) cos(theta);
        // y = r sin(phi) sin(theta);
        // z = r cos(phi)

        // so we get
        // r2 = x2 + y2 + z2
        // cos(phi) = z/r --> phi = cos-1(z/r)
        // cos(theta) = x/(rsin(phi)) --> theta = cos-1(x/rsin(phi))

        // acos returns in radians
        //rho = sqrt(x*x + y*y + z*z);
        //double rotOffZ = acos(z/rho);

        //double rotAbtZ;

        // acos(-1) returns nan even though documentation says it shouldn't
        // so we need to account for that
        //if(x/(rho*sin(rotOffZ)) <= -.99999)
        //  rotAbtZ = acos(-.99999);
        //else
        // rotAbtZ = acos(x/(rho * sin(rotOffZ)));

        //theta = rotOffZ * 180 / M_PI; // theta is our rows so it equals rotation off of z
        // since acos returns a number between 0 and pi but our data is from 0 to 2pi we need to fix this!
        // one simple way is to just double the angle, but I don't know if that is correct, the picture looks wonky
        //phi   = 2 * (rotAbtZ * 180 / M_PI); // phi is our cols so it equals the rotation around the z axis

        //theta = 90 - theta;
        //phi = phi + 180;

        //coorData[i+0] = theta;
        //coorData[i+1] = phi;
        //coorData[i+2] = rho;

        //double thetaDecim;
        //double thetaInt;
        //double phiDecim;
        //double phiInt;

        //thetaDecim = modf(theta, &thetaInt);

        //if(std::abs(thetaDecim) < minTheta)
        //if(thetaDecim < minTheta)
        //  minTheta = std::abs(thetaDecim);

        //phiDecim = modf(phi, &phiInt);

        //if(std::abs(phiDecim) < minPhi)
        //  if(phiDecim < minPhi)
        //    minPhi = std::abs(phiDecim);
        */

        double ra, dec, r;
        r = sqrt(x*x + y*y + z*z);
        if(r == 0)
          dec = 0;
        else
          dec = asin(z/r);

        // shift from 90 to -90 latitude to 0 to 180 style
        dec = (M_PI/2) - dec;

        // make dec wrap around
        //if(dec >= (M_PI))
        //  dec = dec - M_PI;

        if(r == 0)
          ra = 0;
        else
          ra = atan2(y, x);

        // shift from -180 to 180 to 0 to 360 style
        ra = ra + M_PI;

        //if(ra < 0)
        //  ra = ra + 2 * M_PI;
        // make ra wrap around
        //if(ra >= (2*M_PI))
        //  ra = ra - (2*M_PI);

        // convert to degrees
        spherData[i+0] = ra * 180 / M_PI;
        spherData[i+1] = dec * 180 / M_PI;
        spherData[i+2] = r;

        double raInt;
        double raDecim = modf(spherData[i+0], &raInt);
        if(raDecim < minRA)
          minRA = raDecim;

        double decInt;
        double decDecim = modf(spherData[i+1], &decInt);
        if(decDecim < minDec)
          minDec = decDecim;
    }

    double resDec;
    double resRA;
    //string minThetaStr = std::to_string(minTheta);
    string minDecStr = std::to_string(minDec);
    for(int i = 0; i < strlen(minDecStr.c_str()); i += 1)
    {
      char c = minDecStr[i];
      if(isdigit(c))
        minDecStr[i] = '0';
    }
    minDecStr[strlen(minDecStr.c_str())-1] = '1';
    resDec = std::stod(minDecStr);

    //string minPhiStr = std::to_string(minPhi);
    string minRaStr = std::to_string(minRA);
    for(int i = 0; i < strlen(minRaStr.c_str()); i += 1)
    {
      char c = minRaStr[i];
      if(isdigit(c))
        minRaStr[i] = '0';
    }
    minRaStr[strlen(minRaStr.c_str())-1] = '1';
    resRA = std::stod(minRaStr);

    std::cout << minDecStr << " = " << resDec << "\n";
    std::cout << minRaStr << " = " << resRA << "\n";

    if(resRA < .01)
      resRA = .01;

    if(resDec < .01)
      resDec = .01;

    inputMatrixData* mat = new inputMatrixData(resRA, resDec, m_fileDataType);
    m_cols = 360/resRA;
    m_rows = 180/resDec;

    mat->initialize();
    mat->RARes(resRA);
    mat->DecRes(resDec);

    const int numPoints = dims1[0]*dims1[1];
    int dataPoint = 0;
    for(int i = 0; i < dims1[0] * dims1[1]; i += 3)
    {
      double ra  = spherData[i+0];
      double dec = spherData[i+1];

      long c = ra / resRA;
      long r = dec/resDec;

      //std::cout << "Orig X: " << coorData[i+0] << " Orig Y: " << coorData[i+1]
      //          << "Shift X: " << shiftedData[i+0] << "Shifted Y: " << shiftedData[i+1]
      //          << "COL DEG: " << ra << " COL IND: " << c
      //          << " ROW DEG: " << dec << " ROW IND: " << r << "\n";

      //printf("%s: %010.5f\t%s: %010.5f\t\n", "Orig  X", coorData[i+0],    "Orig  Y", coorData[i+1]);
      //printf("%s: %010.5f\t%s: %010.5f\t\n", "Wrap  X", wrappedData[i+0], "Wrap  Y", wrappedData[i+1]);
      //printf("%s: %010.5f\t%s: %010.5f\t\n", "Shift X", shiftedData[i+0], "Shift Y", shiftedData[i+1]);
      //printf("%s: %010.5f\t%s: %010.5f\t\n", "Col Deg", spherData[i+0],   "Row Deg", spherData[i+1]);
      //printf("\n");

      // this maps to the same point a lot of times causing the rest of the graph to get shifted to all blue
      //(*mat)[c][r] += 1;
      (*mat)[c][r] = 1;
      dataPoint += 1;
      s_association->updateProgressValue((100.0 * dataPoint)/numPoints);
    }

    return mat;
  }
  catch (H5::Exception& err)
  {
    snprintf(hdf5_err,HDF5_ERR_LEN,"%s",err.getCDetailMsg());
    m_err = fileFitsError;
    m_errDetail = errorText[abs(m_err)] + ": " + std::string(hdf5_err);
    return 0;
  }

  return 0;
}

vectorData<int> *HDF5Manager::getVectorI()
{
  vectorData<int> *i_vec;
  std::string dataSetName = "OCCUPANCY";
  int sides = 0, layout = 0, scheme = 0;
  double minValue = 0, maxValue = 0;
  unsigned long long int numOps, updateUnit, currOp;

  char** infoData;
  hsize_t* infoDims;
  try
  {
    currInfoGroup = new H5::Group(m_ptr->openGroup("Occupancy"));
    currInfoDataSet = new H5::DataSet(currInfoGroup->openDataSet("OCCUPANCY"));
    currInfoDataSpace = new H5::DataSpace(currInfoDataSet->getSpace());

    int numInfoDims = currInfoDataSpace->getSimpleExtentNdims();
    infoDims = new hsize_t[numInfoDims];

    currInfoDataSpace->getSimpleExtentDims(infoDims, NULL);

    infoData = new char*[infoDims[0] * infoDims[1]];
    currDataDataSet->read(infoData, *H5String, *currInfoDataSpace);
  }
  catch (H5::Exception& err) {
    snprintf(hdf5_err,HDF5_ERR_LEN,"%s",err.getCDetailMsg());
    m_err = fileFitsError;
    m_errDetail = errorText[abs(m_err)] + ": " + std::string(hdf5_err);
    return 0;
  }

  sides    = atoi(infoData[infoDims[1] + 0]);
  layout   = atoi(infoData[infoDims[1] + 1]);
  scheme   = atoi(infoData[infoDims[1] + 2]);
  minValue = atof(infoData[infoDims[1] + 3]);
  maxValue = atof(infoData[infoDims[1] + 4]);
  //sides = atoi(infoData[1][0]);
  //layout = atoi(infoData[1][1]);
  //scheme = atoi(infoData[1][2]);
  //minValue = atoi(infoData[1][3]);
  //maxValue = atoi(infoData[1][4]);

  int* data;
  hsize_t* dataDims;
  try
  {
    currDataGroup = new H5::Group(m_ptr->openGroup("Occupancy"));
    currDataDataSet = new H5::DataSet(currDataGroup->openDataSet("OCCUPANCY"));
    currDataDataSpace = new H5::DataSpace(currDataDataSet->getSpace());

    int numDataDims = currDataDataSpace->getSimpleExtentNdims();
    dataDims = new hsize_t[numDataDims];

    currDataDataSpace->getSimpleExtentDims(dataDims, NULL);
    data = new int[dataDims[0]];
    m_rows = dataDims[0];

    currDataDataSet->read(data, *H5Int32, *currDataDataSpace);
  }
  catch (H5::Exception& err) {
    snprintf(hdf5_err,HDF5_ERR_LEN,"%s",err.getCDetailMsg());
    m_err = fileFitsError;
    m_errDetail = errorText[abs(m_err)] + ": " + std::string(hdf5_err);
    s_association->errorValue(m_err);
    s_association->errorDetails(m_errDetail);
    return 0;
  }

  i_vec = new vectorData<int>(m_rows, m_fileDataType);
  i_vec->initialize();
  i_vec->sides(sides);
  i_vec->maxYIndex(maxValue);
  i_vec->minYIndex(minValue);
  i_vec->layout(static_cast<LAYOUT>(layout));
  i_vec->pixelScheme(static_cast<PIXELSCHEME>(scheme));

  numOps = m_rows;
  updateUnit = numOps / 100;
  if(updateUnit < 1) updateUnit = 1;
  currOp = 0;
  for (int row = 0; row < m_rows; ++row) {
    (*i_vec)[row] = data[row];
    currOp++;
//    if(m_showProgress && !(currOp % updateUnit))
//      informProgress(currOp / updateUnit);
  }

  return i_vec;
}

vectorData<double> *HDF5Manager::getVectorD()
{
  vectorData<double> *d_vec;
  string dataName = dataSetName(m_fileDataType);
  unsigned long long int numOps, updateUnit, currOp;

  getGroups();
  readComments(infoGroup);

  double* data;
  hsize_t* dataDims;
  try
  {
    currDataDataSet = new H5::DataSet(currDataGroup->openDataSet(dataName));
    currDataDataSpace = new H5::DataSpace(currDataDataSet->getSpace());

    int numDataDims = currDataDataSpace->getSimpleExtentNdims();
    dataDims = new hsize_t[numDataDims];

    currDataDataSpace->getSimpleExtentDims(dataDims, NULL);

    data = new double[dataDims[0]];
    m_rows = dataDims[0];

    currDataDataSet->read(data, *H5Double, *currDataDataSpace);
  }
  catch (H5::Exception& err) {
    snprintf(hdf5_err,HDF5_ERR_LEN,"%s",err.getCDetailMsg());
    m_err = fileFitsError;
    m_errDetail = errorText[abs(m_err)] + ": " + std::string(hdf5_err);
    s_association->errorValue(m_err);
    s_association->errorDetails(m_errDetail);

    std::cerr << "ERROR " << err.getCDetailMsg() << "\n";
    return 0;
  }

  d_vec = new vectorData<double>(m_rows,m_fileDataType);
  d_vec->initialize();

  setAttributes(m_fileDataType, d_vec);

  numOps = m_rows;
  updateUnit = numOps / 100;
  if(updateUnit < 1) updateUnit = 1;
  currOp = 0;
  const int numPoints = m_rows;
  int dataPoint = 0;
  for (int row = 0; row < m_rows; ++row)
  {
    (*d_vec)[row] = data[row];
    currOp++;
    dataPoint += 1;
    s_association->updateProgressValue((100.0 * dataPoint)/numPoints);
  }

  delete[] data;

  return d_vec;
}

matrixData<double> *HDF5Manager::getMatrixD()
{
  matrixData<double> *d_mat;
  unsigned long long int numOps, updateUnit, currOp;
  string dataName = dataSetName(m_fileDataType);

  getGroups();
  readComments(infoGroup);

  double* data;
  hsize_t* dataDims;
  try
  {
    currDataDataSet = new H5::DataSet(currDataGroup->openDataSet(dataName));
    currDataDataSpace = new H5::DataSpace(currDataDataSet->getSpace());

    int numDataDims = currDataDataSpace->getSimpleExtentNdims();
    dataDims = new hsize_t[numDataDims];
    currDataDataSpace->getSimpleExtentDims(dataDims, NULL);

    m_rows = dataDims[0];
    m_cols = dataDims[1];

    data = new double[dataDims[0] * dataDims[1]];
    for(int i = 0; i < dataDims[0] * dataDims[1]; i += 1)
      data[i] = 0;

    currDataDataSet->read(data, *H5Double, *currDataDataSpace);
  }
  catch (H5::Exception& err) {
    snprintf(hdf5_err,HDF5_ERR_LEN,"%s",err.getCDetailMsg());
    m_err = fileFitsError;
    m_errDetail = errorText[abs(m_err)] + ": " + std::string(hdf5_err);
    s_association->errorValue(m_err);
    s_association->errorDetails(m_errDetail);
    delete d_mat;
    return 0;
  }

  // create data structure for storage
  d_mat = new matrixData<double>(m_cols,m_rows,m_fileDataType);
  d_mat->initialize();

  setAttributes(m_fileDataType, d_mat);

  const int numPoints = dataDims[0] * dataDims[1];
  int dataPoint = 0;
  for(int r = 0; r < dataDims[0]; r += 1)
  {
    for(int c = 0; c < dataDims[1]; c += 1)
    {
      (*d_mat)[c][r] = data[r * m_cols + c];

      dataPoint += 1;
      s_association->updateProgressValue((100.0 * dataPoint)/numPoints);
    }
  }

  delete[] data;

  return d_mat;
}

cubeData<std::complex<double> > *HDF5Manager::getCubeCD()
{
  cubeData<std::complex<double> > *dc_cube;
  std::vector<std::vector<std::vector<complex<double>>>> cubeDataAccess;
  int polarization, index; //, offset;
  unsigned long long int numOps, updateUnit, currOp;
  string dataName = dataSetName(m_fileDataType);

  getGroups();
  readComments(infoGroup);

  complex<double>* data;
  hsize_t* dataDims;
  try
  {
    currDataDataSet = new H5::DataSet(currDataGroup->openDataSet(dataName));
    currDataDataSpace = new H5::DataSpace(currDataDataSet->getSpace());

    int numDataDims = currDataDataSpace->getSimpleExtentNdims();
    dataDims = new hsize_t[numDataDims];
    currDataDataSpace->getSimpleExtentDims(dataDims, NULL);

    m_slices = dataDims[0];
    m_rows = dataDims[1];
    m_cols = dataDims[2];

    data = new complex<double>[m_slices * m_rows * m_cols];
    currDataDataSet->read(data, *H5Complex, *currDataDataSpace);
  }
  catch (H5::Exception& err) {
    snprintf(hdf5_err,HDF5_ERR_LEN,"%s",err.getCDetailMsg());
    m_err = fileFitsError;
    m_errDetail = errorText[abs(m_err)] + ": " + std::string(hdf5_err);
    s_association->errorValue(m_err);
    s_association->errorDetails(m_errDetail);
    return 0;
  }

  dc_cube = new cubeData<std::complex<double> >(m_cols,m_rows,m_slices,m_fileDataType);
  dc_cube->initialize();
  cubeDataAccess = dc_cube->rwAccess();

  setAttributes(m_fileDataType, dc_cube);

  numOps = m_slices;
  updateUnit = numOps / 100;
  if(updateUnit < 1)
    updateUnit = 1;
  currOp = 0;

  const int numPoints = m_slices * m_cols * m_rows;
  int dataPoint = 0;
  for (int slice = 0; slice < m_slices; ++slice)
  {
    for (int col = 0; col < m_cols; ++col)
    {
      for (int row = 0; row < m_rows; ++row)
      {
        (*dc_cube)[slice][col][row] = data[slice * m_rows * m_cols + row * m_cols + col];
        dataPoint += 1;
        s_association->updateProgressValue((100.0 * dataPoint)/numPoints);
      }
    }
  }

  delete[] data;

  return dc_cube;
}

dataMap* HDF5Manager::getMap() {
  return 0;
}

dataSpectrum* HDF5Manager::getSpectrum() {
  return 0;
}

bool HDF5Manager::saveMap(dataMap* map) {
  return true;
}

bool HDF5Manager::saveSpectrum(dataSpectrum* spect) {
  return true;
}
