/***************************************************************************
 *   hdf5manager.h                                                         *
 *   Copyright (C) 2014 by Daniel Suson                                    *
 *   daniel.suson@purduecal.edu                                            *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU General Public License     *
 *   along with this program; if not, write to the                         *
 *   Free Software Foundation, Inc.,                                       *
 *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
 *                                                                         *
 *   In addition, as a special exception, the copyright holders give       *
 *   permission to link the code of this program with any edition of       *
 *   the Qt library by Trolltech AS, Norway (or with modified versions     *
 *   of Qt that use the same license as Qt), and distribute linked         *
 *   combinations including the two.  You must obey the GNU General        *
 *   Public License in all respects for all of the code used other than    *
 *   Qt.  If you modify this file, you may extend this exception to        *
 *   your version of the file, but you are not obligated to do so.  If     *
 *   you do not wish to do so, delete this exception statement from        *
 *   your version.                                                         *
 ***************************************************************************
 * Description:                                                            *
 *                                                                         *
 * This header provides the definitions for various enumerated lists used  *
 * by the data classes.                                                    *
 * ----------------------- Change Log ------------------------------------ *
 * Date    Name         Description                                        *
 *                                                                         *
 ***************************************************************************
 * This software evolved from work that was done by Eric Hivon at the      *
 * California Institute of Technology on the MASTER algorithm (Hivon, E.,  *
 * et al., ApJ, vol 567, p 2).  It adapts or interfaces with these         *
 * packages:                                                               *
 *                                                                         *
 * HealPix         (http://www.eso.org/science/healpix/)                   *
 * FTOOLS & FITSIO (http://heasarc.gsfc.nasa.gov/docs/corp/software.html)  *
 *                                                                         *
 * Any publications or presentations that use results generated by this    *
 * program must reference the fact that it was developed by Daniel Suson   *
 ***************************************************************************/
#ifndef __HDF5MANAGER_H__
#define __HDF5MANAGER_H__

#include <H5Cpp.h>
#include "atypes.h"
#include "filemanager.h"
#include "vectordata.h"
#include "matrixdata.h"
#include "cubedata.h"
#include "../libgraphics/datamap.h"
#include "../libgraphics/dataspectrum.h"

#define HDF5_ERR_LEN	160

class HDF5Manager : public fileManager {
  public:
    HDF5Manager(association* dataMgr, const char *fileName, FILETYPE dataType=fileType::InputData, H5RWMode mode = H5RWMode::RDWR);
    HDF5Manager(association* dataMgr, const char *filename, baseData *data);
    HDF5Manager(HDF5Manager* from);
    ~HDF5Manager();

    void      open();
    void      open(int* numTypes, FILETYPE* dataTypes);

    bool      getHeaders(int hdrNum);
    FILETYPE* getHeaders(int* numTypes);
    bool      getDataType();
    bool      getDimensions();
    bool      getEnergy();

    baseData        *data();
    inputMatrixData *data(int s_min,int s_max);
    inputMatrixData *data(float e_min,float e_max);
    baseData        *gadgetData();

    vectorData<int>                  *getVectorI();
    vectorData<double>               *getVectorD();
    matrixData<double>               *getMatrixD();
    cubeData<std::complex<double>>   *getCubeCD();

    dataMap            *getMap();
    dataSpectrum       *getSpectrum();

    bool            saveBase(const char* filename, int* numTypes, FILETYPE* dataTypes);

    void            save(int* numTypes, FILETYPE* dataTypes);
    void            save(ASSOCIATEDMAP  map);
    void            save(ASSOCIATEDSPECTRUM spect);

    bool            saveVectorI(vectorData<int> *vd);
    bool            saveVectorD(vectorData<double> *vd);
    bool            saveMatrixD(matrixData<double> *md);
    bool            saveCubeCD(cubeData<complex<double> > *cd);
    bool            saveMap(dataMap *map);
    bool            saveSpectrum(dataSpectrum *spect);

    H5::H5File* filePtr() {return m_ptr;}
  private:
    association  *s_association;
    H5::H5File   *m_ptr;

    //FITSTYPE     m_fitsType;
    char         hdf5_err[HDF5_ERR_LEN];
    const char*  dataGroupName = "RootDataGroup";
    const char*  infoGroupName = "RootInfoGroup";

    H5::Group*    dataGroup;
    H5::Group*    infoGroup;

    H5::Group*     currInfoGroup;
    H5::DataSet*   currInfoDataSet;
    H5::DataSpace* currInfoDataSpace;

    H5::Group*     currDataGroup;
    H5::DataSet*   currDataDataSet;
    H5::DataSpace* currDataDataSpace;

    H5::StrType*  H5String  = new H5::StrType(H5::PredType::C_S1, H5T_VARIABLE);
    H5::DataType* H5Int32   = new H5::DataType(H5::PredType::NATIVE_INT32);
    H5::DataType* H5Float   = new H5::DataType(H5::PredType::NATIVE_FLOAT);
    H5::DataType* H5Double  = new H5::DataType(H5::PredType::NATIVE_DOUBLE);
    H5::CompType* H5Complex = new H5::CompType(sizeof(complex<double>));
};

#endif /* __HDF5MANAGER_H__ */
