/****************************************************************************
                              \pixelizer.h
Description:\brief (put short description here)

Begin    : Mon Jun 6 2005
Copyright: (C) 2005 by Daniel Suson
email    : daniel.suson@tamuk.edu

-----------------------------------------------------------------------------
                                Change Log
Date       Name                Description

-----------------------------------------------------------------------------

This program was developed at Texas A&M University-Kingsville by Daniel Suson.
It is free software; you may redistribute and/or modify it under the terms
of the GNU General License as published by the Free Software Foundation;
either version 2 of the License. or (at your option) any later version.

This software evolved from work that was done by Eric Hivon at the
California Institute of Technology on the MASTER algorithm (Hivon, E.,
et al., ApJ, vol 567, p 2).  It adapts or interfaces with these packages:

HealPix         (http://www.eso.org/science/healpix/)
FTOOLS & FITSIO (http://heasarc.gsfc.nasa.gov/docs/corp/software.html)

Any publications or presentations that use results generated by this program
must reference the fact that it was developed at Texas A&M 
University-Kingsville by Daniel Suson
***************************************************************************/

#ifndef _PIXELIZER_H_
#define _PIXELIZER_H_

#include <string>
#include <vector>

#include "atypes.h"
#include "basedata.h"
#include "vectordata.h"
//#include "pixelweights.h"

class association;

class Pixelizer {

  public:
    Pixelizer();
    Pixelizer(Pixelizer* from);
    virtual ~Pixelizer();

    /**
     * Virtual functions that must be defined by inherited classes
     **/
    virtual std::string name() const = 0;
    virtual int pixelize(association* dataClasses, long x = 0, long y = 0, int range = 0, FILETYPE type = fileType::Null) = 0;
    virtual int optimize(int points, association* dataClasses) = 0;
    virtual double calculateAverage(FILETYPE dataType, association* assoc) = 0;
    virtual double calculateVariance(FILETYPE dataType, association* assoc) = 0;
    virtual vectorData<double>* meanNormalize(FILETYPE dataType, association* assoc, bool useMean  = false) = 0;
    virtual vectorData<double>* minmaxNormalize(FILETYPE dataType, association* assoc, double newMin = 0, double newMax = 1) = 0;
    virtual baseData* calculateAverageVector(FILETYPE dataType, association* assoc) = 0;
    virtual baseData* calculateDevianceVector(FILETYPE dataType, association* assoc) = 0;
    virtual baseData* calculateVarianceVector(FILETYPE dataType, association* assoc) = 0;
    virtual int scale() const = 0;
    virtual void scale(int number) = 0;
    virtual void pixelLayout(LAYOUT type) = 0;
    virtual LAYOUT pixelLayout() const = 0;

    /**
     * clear pixelizer variables
     */
    void clear();

    /**
     * pixelizer scheme used
     */
    void pixelizerScheme(PIXELSCHEME type) {m_scheme = type;}
    PIXELSCHEME pixelizerScheme() {return m_scheme;}

    /**
     * flag to indicate if the Pixelizer has been configured or not
     */
    bool configured() {return m_configured;}
    void configured(bool flag) {m_configured = flag;}

    /**
     * flag to indicate if the data is to be summed or averaged in a pixelize
     */
    bool usePixelAvg()          {return m_usePixAvg;}
    void usePixelAvg(bool flag) {m_usePixAvg = flag;}

    bool usePixelDev()          {return m_usePixDev;}
    void usePixelDev(bool flag) {m_usePixDev = flag;}

    bool usePixelVar()          {return m_usePixVar;}
    void usePixelVar(bool flag) {m_usePixVar = flag;}

    bool doAvgNormalize()          {return m_doAvgNorm;}
    void doAvgNormalize(bool flag) {m_doAvgNorm = flag;}

    bool doVarNormalize()          {return m_doVarNorm;}
    void doVarNormalize(bool flag) {m_doVarNorm = flag;}

    bool doMinMaxScale()          {return m_doMinMax;}
    void doMinMaxScale(bool flag) {m_doMinMax = flag;}

    /**
     * flag to indicate that the data has been pixelized
     */
    bool active() {return m_active;}
    void active(bool flag) {m_active = flag;}

  protected:
    bool               m_configured;  // flag indicating if Pixelizer is configured
    bool               m_active;      // flag indicating if Pixelizer is active
    bool               m_usePixAvg;     // flag to trigger averaging of data in pixel
    bool               m_usePixDev;     // flag to trigger showing deviance data in pixel
    bool               m_usePixVar;     // flag to trigger showing variance data in pixel
    bool               m_doAvgNorm;     // flag to trigger using average normalization
    bool               m_doVarNorm;     // flag to trigger using variance normalization
    bool               m_doMinMax;      // falg to trigger using min max scaling
    PIXELSCHEME        m_scheme;      // pixelization scheme used
};

#endif
