/***************************************************************************
 *   controldatadlg.cpp                                                    *
 *   Copyright (C) 2014 by Daniel Suson                                    *
 *   suson@calumet.purdue.edu                                              *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU General Public License     *
 *   along with this program; if not, write to the                         *
 *   Free Software Foundation, Inc.,                                       *
 *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
 *                                                                         *
 *   In addition, as a special exception, the copyright holders give       *
 *   permission to link the code of this program with any edition of       *
 *   the Qt library by Trolltech AS, Norway (or with modified versions     *
 *   of Qt that use the same license as Qt), and distribute linked         *
 *   combinations including the two.  You must obey the GNU General        *
 *   Public License in all respects for all of the code used other than    *
 *   Qt.  If you modify this file, you may extend this exception to        *
 *   your version of the file, but you are not obligated to do so.  If     *
 *   you do not wish to do so, delete this exception statement from        *
 *   your version.                                                         *
 ***************************************************************************
 * Description:                                                            *
 *                                                                         *
 * This class defines the control data dialog structure associated with    *
 * the Qt4 user interface.                                                 *
 * ----------------------- Change Log ------------------------------------ *
 * Date    Name         Description                                        *
 *                                                                         *
 ***************************************************************************
 * This software evolved from work that was done by Eric Hivon at the      *
 * California Institute of Technology on the MASTER algorithm (Hivon, E.,  *
 * et al., ApJ, vol 567, p 2).  It adapts or interfaces with these         *
 * packages:                                                               *
 *                                                                         *
 * HealPix         (http://www.eso.org/science/healpix/)                   *
 * FTOOLS & FITSIO (http://heasarc.gsfc.nasa.gov/docs/corp/software.html)  *
 *                                                                         *
 * Any publications or presentations that use results generated by this    *
 * program must reference the fact that it was developed by Daniel Suson   *
 ***************************************************************************/
#include "controldatadlg.h"
#include "../libanalyzer/matrixdata.h"

#include <limits>

#include <ftxui/dom/elements.hpp>
#include <ftxui/screen/screen.hpp>
#include <ftxui/component/screen_interactive.hpp>
#include <ftxui/component/component.hpp>

controlDataDialog::controlDataDialog(association *assoc, std::function<void(FILETYPE, bool)> s, std::function<void()> c)
                   : controlDataDialogParent(assoc), screen(ftxui::ScreenInteractive::TerminalOutput())
{
	successFunc = s;
	cancelFunc = c;
}

controlDataDialog::~controlDataDialog()
{
}

void controlDataDialog::clearInput()
{
}

void controlDataDialog::clearScreen()
{
}


void controlDataDialog::execute()
{
	std::function<ftxui::Component(std::string)> labelMaker = [&](std::string str)
																{
																	ftxui::Component labelComp =
																				ftxui::Renderer([str](bool focused)
																				{
																					ftxui::Element label = ftxui::text(str) | ftxui::focus;
																					if(focused)
																						return label | ftxui::color(ftxui::Color::Black) | ftxui::bgcolor(ftxui::Color::GrayLight);

																					return label;
																				});
																	return labelComp;
																};

	int dataID = 0;
	std::vector<std::string> dataNames = {"Data", "Weights", "Noise", "Filter", "Beam"};
	ftxui::Component dataTypeButtons = ftxui::Radiobox(&dataNames, &dataID);
	ftxui::Component dataTypeTitle = labelMaker("Data Type") | ftxui::hcenter;
	ftxui::Component dataTypeCont = ftxui::Container::Vertical({dataTypeTitle, dataTypeButtons}) | ftxui::border;

	std::string raDef = "1";
	std::string raData = "1";
	ftxui::Component raInput = ftxui::Input(&raData, raDef);
	ftxui::Component raLabel = labelMaker("RA Resolution:");
	ftxui::Component raCont = ftxui::Container::Horizontal({raLabel, ftxui::Renderer([](){return ftxui::text(" ");}), raInput}) | ftxui::border;

	std::string decDef = "1";
	std::string decData = "1";
	ftxui::Component decInput = ftxui::Input(&decData, decDef);
	ftxui::Component decLabel = labelMaker("Dec Resolution:");
	ftxui::Component decCont = ftxui::Container::Horizontal({decLabel, ftxui::Renderer([](){return ftxui::text(" ");}), decInput}) | ftxui::border;

	std::string strengthDef = "1";
	std::string strengthData = "1";
	ftxui::Component strengthInput = ftxui::Input(&strengthData, strengthDef);
	ftxui::Component strengthLabel = labelMaker("Signal Strength");
	ftxui::Component strengthCont = ftxui::Container::Horizontal({strengthLabel, ftxui::Renderer([](){return ftxui::text(" ");}), strengthInput}) | ftxui::border;

	int coordID = 0;
	std::vector<std::string> coordNames = {"RA/Dec", "Galactic", "Terrestrial"};
	ftxui::Component coordButtons = ftxui::Radiobox(&coordNames, &coordID);
	ftxui::Component coordTitle = labelMaker("Coordinate System") | ftxui::hcenter;
	ftxui::Component coordCont = ftxui::Container::Vertical({coordTitle, coordButtons}) | ftxui::border;

	ftxui::Component resStrengthCont = ftxui::Container::Vertical({raCont, decCont, strengthCont}) | ftxui::border;
	ftxui::Component dataResStrengthCoordCont = ftxui::Container::Horizontal({	dataTypeCont    | ftxui::flex,
																				resStrengthCont | ftxui::flex,
																				coordCont       | ftxui::flex
																			 }) | ftxui::border;

	int opID = 0;
	std::vector<std::string> opNames = {"Add", "Sub", "Scale", "Replace", "Invert", "Mirror"};
	ftxui::Component opButtons = ftxui::Radiobox(&opNames, &opID);
	ftxui::Component opTitle = ftxui::Renderer([](){return ftxui::text("Operation");});
	ftxui::Component opCont = ftxui::Container::Vertical({opTitle, opButtons}) | ftxui::border;

	int controlID = 0;
	std::vector<std::string> controlNames = {"Uniform Sky", "Uniform Region", "Checkerboard", "Delta", "Gaussian", "Spherical Harmonic"};
	ftxui::Component controlButtons = ftxui::Radiobox(&controlNames, &controlID);
	ftxui::Component controlTitle = ftxui::Renderer([](){return ftxui::text("Control Type");});
	ftxui::Component controlCont = ftxui::Container::Vertical({controlTitle, controlButtons}) | ftxui::border;

	ftxui::Component uniformCont = ftxui::Container::Vertical({}) | ftxui::border;

	std::string topDef = "90";
	std::string topData = "90";
	ftxui::Component topInput = ftxui::Input(&topData, topDef);
	ftxui::Component topLabel = labelMaker("Top Bounds:");
	ftxui::Component topCont = ftxui::Container::Horizontal({topLabel, ftxui::Renderer([](){return ftxui::text(" ");}), topInput});

	std::string botDef = "-90";
	std::string botData = "-90";
	ftxui::Component botInput = ftxui::Input(&botData, botDef);
	ftxui::Component botLabel = labelMaker("Bottom Bounds:");
	ftxui::Component botCont = ftxui::Container::Horizontal({botLabel, ftxui::Renderer([](){return ftxui::text(" ");}), botInput});

	std::string leftDef = "-180";
	std::string leftData = "-180";
	ftxui::Component leftInput = ftxui::Input(&leftData, leftDef);
	ftxui::Component leftLabel = labelMaker("Left Bounds:");
	ftxui::Component leftCont = ftxui::Container::Horizontal({leftLabel, ftxui::Renderer([](){return ftxui::text(" ");}), leftInput});

	std::string rightDef = "180";
	std::string rightData = "180";
	ftxui::Component rightInput = ftxui::Input(&rightData, rightDef);
	ftxui::Component rightLabel = labelMaker("Right Bounds:");
	ftxui::Component rightCont = ftxui::Container::Horizontal({rightLabel, ftxui::Renderer([](){return ftxui::text(" ");}), rightInput});

	ftxui::Component heightCont = ftxui::Container::Vertical({topCont, botCont}) | ftxui::vcenter;
	ftxui::Component widthCont = ftxui::Container::Vertical({leftCont, rightCont}) | ftxui::vcenter;
	ftxui::Component regionCont = ftxui::Container::Horizontal({heightCont | ftxui::flex, widthCont | ftxui::flex});

	std::string checkWidthDef = "10";
	std::string checkWidthData = "10";
	ftxui::Component checkWidthInput = ftxui::Input(&checkWidthData, checkWidthDef);
	ftxui::Component checkWidthLabel = labelMaker("Checkerboard Width:");
	ftxui::Component checkWidthCont = ftxui::Container::Horizontal({checkWidthLabel, ftxui::Renderer([](){return ftxui::text(" ");}), checkWidthInput});

	std::string checkHeightDef = "10";
	std::string checkHeightData = "10";
	ftxui::Component checkHeightInput = ftxui::Input(&checkHeightData, checkHeightDef);
	ftxui::Component checkHeightLabel = labelMaker("Checkerboard Height:");
	ftxui::Component checkHeightCont = ftxui::Container::Horizontal({checkHeightLabel, ftxui::Renderer([](){return ftxui::text(" ");}), checkHeightInput});

	ftxui::Component checkerCont = ftxui::Container::Vertical({checkWidthCont | ftxui::hcenter, checkHeightCont | ftxui::hcenter}) | ftxui::vcenter;

	std::string deltaRADef = "0";
	std::string deltaRAData = "0";
	ftxui::Component deltaRAInput = ftxui::Input(&deltaRAData, deltaRADef);
	ftxui::Component deltaRALabel = labelMaker("RA:");
	ftxui::Component deltaRACont = ftxui::Container::Horizontal({deltaRALabel, ftxui::Renderer([](){return ftxui::text(" ");}), deltaRAInput});

	std::string deltaDecDef = "0";
	std::string deltaDecData = "0";
	ftxui::Component deltaDecInput = ftxui::Input(&deltaDecData, deltaDecDef);
	ftxui::Component deltaDecLabel = labelMaker("Dec:");
	ftxui::Component deltaDecCont = ftxui::Container::Horizontal({deltaDecLabel, ftxui::Renderer([](){return ftxui::text(" ");}), deltaDecInput});

	ftxui::Component deltaCont = ftxui::Container::Vertical({deltaRACont | ftxui::hcenter, deltaDecCont | ftxui::hcenter}) | ftxui::vcenter;

	std::string gausRADef = "0";
	std::string gausRAData = "0";
	ftxui::Component gausRAInput = ftxui::Input(&gausRAData, gausRADef);
	ftxui::Component gausRALabel = labelMaker("RA:");
	ftxui::Component gausRACont = ftxui::Container::Horizontal({gausRALabel, ftxui::Renderer([](){return ftxui::text(" ");}), gausRAInput});

	std::string gausDecDef = "0";
	std::string gausDecData = "0";
	ftxui::Component gausDecInput = ftxui::Input(&gausDecData, gausDecDef);
	ftxui::Component gausDecLabel = labelMaker("Dec:");
	ftxui::Component gausDecCont = ftxui::Container::Horizontal({gausDecLabel, ftxui::Renderer([](){return ftxui::text(" ");}), gausDecInput});

	std::string gausWidthDef = "0";
	std::string gausWidthData = "0";
	ftxui::Component gausWidthInput = ftxui::Input(&gausWidthData, gausWidthDef);
	ftxui::Component gausWidthLabel = labelMaker("Width/Sigma:");
	ftxui::Component gausWidthCont = ftxui::Container::Horizontal({gausWidthLabel, ftxui::Renderer([](){return ftxui::text(" ");}), gausWidthInput});

	ftxui::Component gaussianCont = ftxui::Container::Vertical({gausRACont | ftxui::hcenter, gausDecCont | ftxui::hcenter, gausWidthCont | ftxui::hcenter}) | ftxui::vcenter;

	std::string harmLDef = "0";
	std::string harmLData = "0";
	ftxui::Component harmLInput = ftxui::Input(&harmLData, harmLDef);
	ftxui::Component harmLLabel = labelMaker("L:");
	ftxui::Component harmLCont = ftxui::Container::Horizontal({harmLLabel, ftxui::Renderer([](){return ftxui::text(" ");}), harmLInput});

	std::string harmMDef = "0";
	std::string harmMData = "0";
	ftxui::Component harmMInput = ftxui::Input(&harmMData, harmMDef);
	ftxui::Component harmMLabel = labelMaker("M:");
	ftxui::Component harmMCont = ftxui::Container::Horizontal({harmMLabel, ftxui::Renderer([](){return ftxui::text(" ");}), harmMInput});

	ftxui::Component harmonicCont = ftxui::Container::Vertical({harmLCont | ftxui::hcenter, harmMCont | ftxui::hcenter}) | ftxui::vcenter;

	ftxui::Component paramTabs = ftxui::Container::Tab({uniformCont, regionCont, checkerCont, deltaCont, gaussianCont, harmonicCont}, &controlID) | ftxui::border;
	ftxui::Component controlParams = ftxui::Container::Horizontal({controlCont | ftxui::flex, paramTabs | ftxui::flex});

	ftxui::Component cancelButton = ftxui::Button("Cancel", [&](){screen.Exit(); this->cancelFunc();})  | ftxui::flex;
	ftxui::Component submitButton = ftxui::Button("Submit", [&](){screen.Exit(); this->successFunc(dataType, false);}) | ftxui::flex;
	ftxui::Component buttonCont   = ftxui::Container::Horizontal({cancelButton, submitButton}) | ftxui::border;

	ftxui::Component title = ftxui::Renderer([](){return ftxui::text("Control Data Configuration") | ftxui::border | ftxui::bold | ftxui::hcenter;});
	ftxui::Component controlContainer = ftxui::Container::Vertical({title, dataResStrengthCoordCont, controlParams, opCont, buttonCont}) | ftxui::border;

	screen.Loop(controlContainer);

	/*
	setDataType();
	setResolution();
	setStrength();
	setControlType();
	setOperation();

	if(confirm())
		buildControlData(dataType, true);
	else
		dataCreationCancelled();
	*/
}

void controlDataDialog::setDataType()
{
}

void controlDataDialog::setResolution()
{
}

void controlDataDialog::setStrength()
{
}

void controlDataDialog::setControlType()
{
}

void controlDataDialog::setOperation()
{
}

bool controlDataDialog::confirm()
{
	return true;
}

void controlDataDialog::buildControlData(FILETYPE f, bool b)
{
	successFunc(f, b);
}

void controlDataDialog::dataCreationCancelled()
{
	cancelFunc();
}

bool controlDataDialog::validate()
{
	return true;
}

void controlDataDialog::help()
{

}
