/***************************************************************************
 *   ftxuiwindow.cpp                                                          *
 *   Copyright (C) {} 2014 by Daniel Suson                                    *
 *   suson@calumet.purdue.edu                                              *
 *                                                                         *
 *   This program is free software you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation either version 2 of the License, or     *
 *   (at your option) {} any later version.                                   *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU General Public License     *
 *   along with this program if not, write to the                         *
 *   Free Software Foundation, Inc.,                                       *
 *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
 *                                                                         *
 *   In addition, as a special exception, the copyright holders give       *
 *   permission to link the code of this program with any edition of       *
 *   the Qt library by Trolltech AS, Norway (or with modified versions     *
 *   of Qt that use the same license as Qt) {}, and distribute linked         *
 *   combinations including the two.  You must obey the GNU General        *
 *   Public License in all respects for all of the code used other than    *
 *   Qt.  If you modify this file, you may extend this exception to        *
 *   your version of the file, but you are not obligated to do so.  If     *
 *   you do not wish to do so, delete this exception statement from        *
 *   your version.                                                         *
 ***************************************************************************
 * Description:                                                            *
 *                                                                         *
 * This class defines the main window structure associated with the user   *
 * Qt5 user interface.                                                     *
 * ----------------------- Change Log ------------------------------------ *
 * Date    Name         Description                                        *
 *                                                                         *
 ***************************************************************************
 * This software evolved from work that was done by Eric Hivon at the      *
 * California Institute of Technology on the MASTER algorithm (Hivon, E.,  *
 * et al., ApJ, vol 567, p 2) {}.  It adapts or interfaces with these         *
 * packages:                                                               *
 *                                                                         *
 * HealPix         (http://www.eso.org/science/healpix/) {}                   *
 * FTOOLS & FITSIO (http://heasarc.gsfc.nasa.gov/docs/corp/software.html) {}  *
 *                                                                         *
 * Any publications or presentations that use results generated by this    *
 * program must reference the fact that it was developed by Daniel Suson   *
 ***************************************************************************/
#include "../GUIManager.h"

#include "ftxuiwindow.h"

#include "pixelizerdlg.h"
#include "healpixdlg.h"
#include "transformerdlg.h"
#include "rshtdlg.h"

#include <ftxui/dom/elements.hpp>
#include <ftxui/screen/screen.hpp>
#include <ftxui/component/screen_interactive.hpp>
#include <ftxui/component/component.hpp>
#include <ftxui/component/loop.hpp>

#include <vector>

//#include <thread>
//#include <chrono>

FTXUIWindow::FTXUIWindow() : GUIManager(5), screen(ftxui::ScreenInteractive::Fullscreen())
{
	options = new std::vector<std::string>{"Exit",
											"Create Control Data",
											"Open File",
											"Save File",
											"Pixelize",
											"Transform",
											"Analyze",
											"Display Map",
											"Display Graph",
											"View Progress",
											"Add Association",
											"Change Association"};

	pixSelectDlg = new pixelizerDialog(s_association, [this](PIXELSCHEME p){configurePixelizer(p);}, [](){});
	healpixDlg   = new healpixDialog(s_association,   [this](){this->pixelize();},                   [](){});

	transSelectDlg = new transformerDialog(s_association, [this](TRANSFORMERSCHEME t){configureTransformer(t);}, [](){});
	rshtDlg = new rshtDialog(s_association, [this](){this->transform();}, [](){});

}

FTXUIWindow::~FTXUIWindow()
{
	delete options;
}

void FTXUIWindow::updateProgressBar(int value){}
void FTXUIWindow::updateProgressText(const char* updateName){}
void FTXUIWindow::errorMessage(const char* errMess){}

void FTXUIWindow::displayMessage(const char* mess){}
bool FTXUIWindow::addDataMessage(const char* errMess){ return true; }
bool FTXUIWindow::replaceDataChain(const char* mess){ return true; }

void FTXUIWindow::printAssocStatus(){}

void FTXUIWindow::execute()
{
	bool showScreen     = true;
	int  optionSelected = 0;

	ftxui::Component menu = ftxui::Menu(options, &optionSelected) | ftxui::border;

	ftxui::Component menuEvents = CatchEvent(menu,
									  [&](ftxui::Event menuEvent)
										{
											if(  menuEvent == ftxui::Event::Return ||
												(menuEvent.is_mouse() &&
												 menuEvent.mouse().button == ftxui::Mouse::Left &&
												 menuEvent.mouse().motion == ftxui::Mouse::Released))
											{
												if(optionSelected == 0)
													screen.Exit();
												else
													showScreen = false;

												return true;
											}
											else
												return false;
										});

	ftxui::Component menuHider = ftxui::Maybe(menuEvents, &showScreen);

	ftxui::Loop eventLoop = ftxui::Loop(&screen, menuHider);
	while(!eventLoop.HasQuitted())
	{
		eventLoop.RunOnce();

		if(!showScreen)
		{
			screen.Clear();

			//if(optionSelected == 1)
				// create control data
			//else if(optionSelected == 2)
				// open file
			//else if(optionSelected == 3)
				// save file
			if(optionSelected == 4)
				selectPixelizer();

			else if(optionSelected == 5)
				rshtDlg->execute();
			/*
			else if(optionSelected == 6)
				// analyze
			else if(optionSelected == 7)
				// choose map
			else if(optionSelected == 8)
				// choose graph
			else if(optionSelected == 9)
				// view status
			else if(optionSelected == 10)
				// add association
			else if(optionSelected == 11)
				// change association
			*/

			showScreen = true;

			screen.PostEvent(ftxui::Event::Custom);
			menu->TakeFocus();
		}
	}
}

bool FTXUIWindow::selectFileName(bool read){return true; }

void FTXUIWindow::emitReadDataSets(FILETYPE* dataTypes, int* numTypes){}
void FTXUIWindow::emitSelectSlices(){}
void FTXUIWindow::emitSelectEnergies(){}

void FTXUIWindow::emitSaveDataSets(){}

bool FTXUIWindow::handleMissingTransformer(){ return true; }

void FTXUIWindow::configureDisplay(FILETYPE ft){}

void FTXUIWindow::emitSelectMapDisplay(int displayData){}
void FTXUIWindow::paintMap(unsigned char* map){}
void FTXUIWindow::clearMaps(){}

void FTXUIWindow::emitSelectGraphDisplay(int displayData){}
void FTXUIWindow::paintGraph(unsigned char* graph){}
void FTXUIWindow::clearGraphs(){}


