/***************************************************************************
 *   ftxuiwindow.cpp                                                          *
 *   Copyright (C) {} 2014 by Daniel Suson                                    *
 *   suson@calumet.purdue.edu                                              *
 *                                                                         *
 *   This program is free software you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation either version 2 of the License, or     *
 *   (at your option) {} any later version.                                   *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU General Public License     *
 *   along with this program if not, write to the                         *
 *   Free Software Foundation, Inc.,                                       *
 *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
 *                                                                         *
 *   In addition, as a special exception, the copyright holders give       *
 *   permission to link the code of this program with any edition of       *
 *   the Qt library by Trolltech AS, Norway (or with modified versions     *
 *   of Qt that use the same license as Qt) {}, and distribute linked         *
 *   combinations including the two.  You must obey the GNU General        *
 *   Public License in all respects for all of the code used other than    *
 *   Qt.  If you modify this file, you may extend this exception to        *
 *   your version of the file, but you are not obligated to do so.  If     *
 *   you do not wish to do so, delete this exception statement from        *
 *   your version.                                                         *
 ***************************************************************************
 * Description:                                                            *
 *                                                                         *
 * This class defines the main window structure associated with the user   *
 * Qt5 user interface.                                                     *
 * ----------------------- Change Log ------------------------------------ *
 * Date    Name         Description                                        *
 *                                                                         *
 ***************************************************************************
 * This software evolved from work that was done by Eric Hivon at the      *
 * California Institute of Technology on the MASTER algorithm (Hivon, E.,  *
 * et al., ApJ, vol 567, p 2) {}.  It adapts or interfaces with these         *
 * packages:                                                               *
 *                                                                         *
 * HealPix         (http://www.eso.org/science/healpix/) {}                   *
 * FTOOLS & FITSIO (http://heasarc.gsfc.nasa.gov/docs/corp/software.html) {}  *
 *                                                                         *
 * Any publications or presentations that use results generated by this    *
 * program must reference the fact that it was developed by Daniel Suson   *
 ***************************************************************************/
#include "../GUIManager.h"

#include "ftxuiwindow.h"

#include "controldatadlg.h"
#include "pixelizerdlg.h"
#include "healpixdlg.h"
#include "transformerdlg.h"
#include "rshtdlg.h"
#include "analyzerdlg.h"
#include "spectrumdlg.h"

#include <ftxui/dom/elements.hpp>
#include <ftxui/screen/screen.hpp>
#include <ftxui/component/screen_interactive.hpp>
#include <ftxui/component/component.hpp>
#include <ftxui/component/loop.hpp>

#include <vector>

//#include <thread>
//#include <chrono>

FTXUIWindow::FTXUIWindow() : GUIManager(5), screen(ftxui::ScreenInteractive::Fullscreen())
{
	options = new std::vector<std::string>{"Exit",
											"Create Control Data",
											"Open File",
											"Save File",
											"Pixelize",
											"Transform",
											"Analyze",
											"Display Map",
											"Display Graph",
											"View Progress",
											"Add Association",
											"Change Association"};

	ctrlDlg = new controlDataDialog(s_association, [this](FILETYPE f, bool b){createControlData(f, b);}, [](){});

	pixSelectDlg = new pixelizerDialog(s_association, [this](PIXELSCHEME p){configurePixelizer(p);}, [](){});
	healpixDlg   = new healpixDialog(s_association,   [this](){this->pixelize();},                   [](){});

	transSelectDlg = new transformerDialog(s_association, [this](TRANSFORMERSCHEME t){configureTransformer(t);}, [](){});
	rshtDlg = new rshtDialog(s_association, [this](){this->transform();}, [](){});

	analSelectDlg = new analyzerDialog(s_association, [this](){configureAnalyzer();}, [](){});
	specDlg = new spectrumDialog([this](){analyze();}, [](){});
}

FTXUIWindow::~FTXUIWindow()
{
	delete options;
}

void FTXUIWindow::updateProgressBar(int value){}
void FTXUIWindow::updateProgressText(const char* updateName){}
void FTXUIWindow::errorMessage(const char* errMess){}

void FTXUIWindow::displayMessage(const char* mess){}
bool FTXUIWindow::addDataMessage(const char* errMess){ return true; }
bool FTXUIWindow::replaceDataChain(const char* mess){ return true; }

void FTXUIWindow::printAssocStatus()
{
	ftxui::ScreenInteractive assocScreen = ftxui::ScreenInteractive::Fullscreen();
	/*
	std::vector<ftxui::Element> assocStatus;

	for(fileType ft = FILETYPE::InputData; ft != FILETYPE::FILETYPE_LIMIT; ft = static_cast<FILETYPE>(static_cast<int>(ft)+1))
	{
		std::string ftName = dataTypeNames[static_cast<int>(ft)];
		if(s_association->exists(ft))
			assocStatus.push_back(ftxui::text(ftName) | ftxui::border | ftxui::color(ftxui::Color::Green));
		else
			assocStatus.push_back(ftxui::text(ftName) | ftxui::border | ftxui::color(ftxui::Color::Red));
	}

	ftxui::Component title = ftxui::Renderer([](){return ftxui::text("Association Status") | ftxui::bold | ftxui::border | ftxui::hcenter;});
	ftxui::Component assocBox = ftxui::Renderer([&](){return ftxui::vbox(assocStatus) | ftxui::border;});
	ftxui::Component contButt = ftxui::Button("Continue", [&](){assocScreen.Exit();});

	ftxui::Component container = ftxui::Container::Vertical({title,
															//ftxui::Renderer([&](){return ftxui::vbox(assocStatus) | ftxui::border;}),
															//assocBox,
															contButt}) | ftxui::border;
	*/

	// there needs to be a way to make this scrollable
	// we also should be able to fill a vector with true/false and loop the vector
	// supposedly we can make a vbox(Elements) where Elements is alias for vector<element>
	// but nothing apppears when I do that so IDK
	ftxui::Component title = ftxui::Renderer([](){return ftxui::text("Association Status") | ftxui::bold | ftxui::border | ftxui::hcenter;});
	ftxui::Component contButt = ftxui::Button("Continue", [&](){assocScreen.Exit();});

	ftxui::Element assocStatus = ftxui::vbox({
												ftxui::text(dataTypeNames[static_cast<int>(fileType::InputData)])          | ftxui::color(s_association->exists(fileType::InputData)          ? ftxui::Color::Green : ftxui::Color::Red),
												ftxui::text(dataTypeNames[static_cast<int>(fileType::InputWeights)])       | ftxui::color(s_association->exists(fileType::InputWeights)       ? ftxui::Color::Green : ftxui::Color::Red),
												ftxui::text(dataTypeNames[static_cast<int>(fileType::WeightedData)])       | ftxui::color(s_association->exists(fileType::WeightedData)       ? ftxui::Color::Green : ftxui::Color::Red),
												ftxui::text(dataTypeNames[static_cast<int>(fileType::InputNoise)])         | ftxui::color(s_association->exists(fileType::InputNoise)         ? ftxui::Color::Green : ftxui::Color::Red),
												ftxui::text(dataTypeNames[static_cast<int>(fileType::InputWeightedNoise)]) | ftxui::color(s_association->exists(fileType::InputWeightedNoise) ? ftxui::Color::Green : ftxui::Color::Red),
												ftxui::text(dataTypeNames[static_cast<int>(fileType::InputBeam)])          | ftxui::color(s_association->exists(fileType::InputBeam)          ? ftxui::Color::Green : ftxui::Color::Red),
												ftxui::text(dataTypeNames[static_cast<int>(fileType::InputFilter)])        | ftxui::color(s_association->exists(fileType::InputFilter)        ? ftxui::Color::Green : ftxui::Color::Red),

												ftxui::text(dataTypeNames[static_cast<int>(fileType::PixelizedData)])          | ftxui::color(s_association->exists(fileType::PixelizedData)          ? ftxui::Color::Green : ftxui::Color::Red),
												ftxui::text(dataTypeNames[static_cast<int>(fileType::PixelizedWeights)])       | ftxui::color(s_association->exists(fileType::PixelizedWeights)       ? ftxui::Color::Green : ftxui::Color::Red),
												ftxui::text(dataTypeNames[static_cast<int>(fileType::WeightedPixel)])          | ftxui::color(s_association->exists(fileType::WeightedPixel)          ? ftxui::Color::Green : ftxui::Color::Red),
												ftxui::text(dataTypeNames[static_cast<int>(fileType::PixelizedNoise)])         | ftxui::color(s_association->exists(fileType::PixelizedNoise)         ? ftxui::Color::Green : ftxui::Color::Red),
												ftxui::text(dataTypeNames[static_cast<int>(fileType::PixelizedWeightedNoise)]) | ftxui::color(s_association->exists(fileType::PixelizedWeightedNoise) ? ftxui::Color::Green : ftxui::Color::Red),
												ftxui::text(dataTypeNames[static_cast<int>(fileType::PixelizedBeam)])          | ftxui::color(s_association->exists(fileType::PixelizedBeam)          ? ftxui::Color::Green : ftxui::Color::Red),
												ftxui::text(dataTypeNames[static_cast<int>(fileType::PixelizedFilter)])        | ftxui::color(s_association->exists(fileType::PixelizedFilter)        ? ftxui::Color::Green : ftxui::Color::Red),

												// ftxui::text(dataTypeNames[static_cast<int>(fileType::InverseData)])          | ftxui::color(s_association->exists(fileType::InverseData)          ? ftxui::Color::Green : ftxui::Color::Red),
												// ftxui::text(dataTypeNames[static_cast<int>(fileType::InverseWeights)])       | ftxui::color(s_association->exists(fileType::InverseWeights)       ? ftxui::Color::Green : ftxui::Color::Red),
												// ftxui::text(dataTypeNames[static_cast<int>(fileType::WeightedInverse)])      | ftxui::color(s_association->exists(fileType::WeightedInverse)      ? ftxui::Color::Green : ftxui::Color::Red),
												// ftxui::text(dataTypeNames[static_cast<int>(fileType::InverseNoise)])         | ftxui::color(s_association->exists(fileType::InverseNoise)         ? ftxui::Color::Green : ftxui::Color::Red),
												// ftxui::text(dataTypeNames[static_cast<int>(fileType::InverseWeightedNoise)]) | ftxui::color(s_association->exists(fileType::InverseWeightedNoise) ? ftxui::Color::Green : ftxui::Color::Red),
												// ftxui::text(dataTypeNames[static_cast<int>(fileType::InverseBeam)])          | ftxui::color(s_association->exists(fileType::InverseBeam)          ? ftxui::Color::Green : ftxui::Color::Red),
												// ftxui::text(dataTypeNames[static_cast<int>(fileType::InverseFilter)])        | ftxui::color(s_association->exists(fileType::InverseFilter)        ? ftxui::Color::Green : ftxui::Color::Red),

												ftxui::text(dataTypeNames[static_cast<int>(fileType::TransformedData)])          | ftxui::color(s_association->exists(fileType::TransformedData)          ? ftxui::Color::Green : ftxui::Color::Red),
												ftxui::text(dataTypeNames[static_cast<int>(fileType::TransformedWeights)])       | ftxui::color(s_association->exists(fileType::TransformedWeights)       ? ftxui::Color::Green : ftxui::Color::Red),
												ftxui::text(dataTypeNames[static_cast<int>(fileType::WeightedTransform)])        | ftxui::color(s_association->exists(fileType::WeightedTransform)        ? ftxui::Color::Green : ftxui::Color::Red),
												ftxui::text(dataTypeNames[static_cast<int>(fileType::TransformedNoise)])         | ftxui::color(s_association->exists(fileType::TransformedNoise)         ? ftxui::Color::Green : ftxui::Color::Red),
												ftxui::text(dataTypeNames[static_cast<int>(fileType::TransformedWeightedNoise)]) | ftxui::color(s_association->exists(fileType::TransformedWeightedNoise) ? ftxui::Color::Green : ftxui::Color::Red),
												ftxui::text(dataTypeNames[static_cast<int>(fileType::TransformedBeam)])          | ftxui::color(s_association->exists(fileType::TransformedBeam)          ? ftxui::Color::Green : ftxui::Color::Red),
												ftxui::text(dataTypeNames[static_cast<int>(fileType::TransformedFilter)])        | ftxui::color(s_association->exists(fileType::TransformedFilter)        ? ftxui::Color::Green : ftxui::Color::Red),

												ftxui::text(dataTypeNames[static_cast<int>(fileType::AlmData)])          | ftxui::color(s_association->exists(fileType::AlmData)          ? ftxui::Color::Green : ftxui::Color::Red),
												ftxui::text(dataTypeNames[static_cast<int>(fileType::AlmWeights)])       | ftxui::color(s_association->exists(fileType::AlmWeights)       ? ftxui::Color::Green : ftxui::Color::Red),
												ftxui::text(dataTypeNames[static_cast<int>(fileType::WeightedAlm)])      | ftxui::color(s_association->exists(fileType::WeightedAlm)      ? ftxui::Color::Green : ftxui::Color::Red),
												ftxui::text(dataTypeNames[static_cast<int>(fileType::AlmNoise)])         | ftxui::color(s_association->exists(fileType::AlmNoise)         ? ftxui::Color::Green : ftxui::Color::Red),
												ftxui::text(dataTypeNames[static_cast<int>(fileType::AlmWeightedNoise)]) | ftxui::color(s_association->exists(fileType::AlmWeightedNoise) ? ftxui::Color::Green : ftxui::Color::Red),
												ftxui::text(dataTypeNames[static_cast<int>(fileType::AlmBeam)])          | ftxui::color(s_association->exists(fileType::AlmBeam)          ? ftxui::Color::Green : ftxui::Color::Red),
												ftxui::text(dataTypeNames[static_cast<int>(fileType::AlmFilter)])        | ftxui::color(s_association->exists(fileType::AlmFilter)        ? ftxui::Color::Green : ftxui::Color::Red),

												ftxui::text(dataTypeNames[static_cast<int>(fileType::EnsembleAveragedSpectrum)])               | ftxui::color(s_association->exists(fileType::EnsembleAveragedSpectrum)               ? ftxui::Color::Green : ftxui::Color::Red),
												ftxui::text(dataTypeNames[static_cast<int>(fileType::EnsembleAveragedNoise)])                  | ftxui::color(s_association->exists(fileType::EnsembleAveragedNoise)                  ? ftxui::Color::Green : ftxui::Color::Red),
												ftxui::text(dataTypeNames[static_cast<int>(fileType::ExtrapolatedSpectrum)])                   | ftxui::color(s_association->exists(fileType::ExtrapolatedSpectrum)                   ? ftxui::Color::Green : ftxui::Color::Red),
												ftxui::text(dataTypeNames[static_cast<int>(fileType::ExtrapolatedInstrumentSpectrum)])         | ftxui::color(s_association->exists(fileType::ExtrapolatedInstrumentSpectrum)         ? ftxui::Color::Green : ftxui::Color::Red),
												ftxui::text(dataTypeNames[static_cast<int>(fileType::BinnedSpectrum)])                         | ftxui::color(s_association->exists(fileType::BinnedSpectrum)                         ? ftxui::Color::Green : ftxui::Color::Red),
												ftxui::text(dataTypeNames[static_cast<int>(fileType::BinnedExtrapolatedSpectrum)])             | ftxui::color(s_association->exists(fileType::BinnedExtrapolatedSpectrum)             ? ftxui::Color::Green : ftxui::Color::Red),
												ftxui::text(dataTypeNames[static_cast<int>(fileType::BinnedExtrapolatedInstrumentedSpectrum)]) | ftxui::color(s_association->exists(fileType::BinnedExtrapolatedInstrumentedSpectrum) ? ftxui::Color::Green : ftxui::Color::Red),

												ftxui::text(dataTypeNames[static_cast<int>(fileType::EnsembleIterationSpectrum)])      | ftxui::color(s_association->exists(fileType::EnsembleIterationSpectrum)      ? ftxui::Color::Green : ftxui::Color::Red),
												ftxui::text(dataTypeNames[static_cast<int>(fileType::EnsembleIterationNoise)])         | ftxui::color(s_association->exists(fileType::EnsembleIterationNoise)         ? ftxui::Color::Green : ftxui::Color::Red),
												ftxui::text(dataTypeNames[static_cast<int>(fileType::ModeModeMatrix)])                 | ftxui::color(s_association->exists(fileType::ModeModeMatrix)                 ? ftxui::Color::Green : ftxui::Color::Red),
												ftxui::text(dataTypeNames[static_cast<int>(fileType::InverseModeModeMatrix)])          | ftxui::color(s_association->exists(fileType::InverseModeModeMatrix)          ? ftxui::Color::Green : ftxui::Color::Red),
												ftxui::text(dataTypeNames[static_cast<int>(fileType::InstrumentEffectsMatrix)])        | ftxui::color(s_association->exists(fileType::InstrumentEffectsMatrix)        ? ftxui::Color::Green : ftxui::Color::Red),
												ftxui::text(dataTypeNames[static_cast<int>(fileType::InverseInstrumentEffectsMatrix)]) | ftxui::color(s_association->exists(fileType::InverseInstrumentEffectsMatrix) ? ftxui::Color::Green : ftxui::Color::Red),
												ftxui::text(dataTypeNames[static_cast<int>(fileType::BinningMatrix)])                  | ftxui::color(s_association->exists(fileType::BinningMatrix)                  ? ftxui::Color::Green : ftxui::Color::Red),
												ftxui::text(dataTypeNames[static_cast<int>(fileType::UnbinningMatrix)])                | ftxui::color(s_association->exists(fileType::UnbinningMatrix)                ? ftxui::Color::Green : ftxui::Color::Red),
												ftxui::text(dataTypeNames[static_cast<int>(fileType::BinnedInstrumentEffectsMatrix)])  | ftxui::color(s_association->exists(fileType::BinnedInstrumentEffectsMatrix)  ? ftxui::Color::Green : ftxui::Color::Red),
												ftxui::text(dataTypeNames[static_cast<int>(fileType::InverseBinnedInstrumentMatrix)])  | ftxui::color(s_association->exists(fileType::InverseBinnedInstrumentMatrix)  ? ftxui::Color::Green : ftxui::Color::Red)
											}) | ftxui::border;
	ftxui::Component assocBox = ftxui::Renderer([&](){return assocStatus;});
	ftxui::Component container = ftxui::Container::Vertical({assocBox, contButt}) | ftxui::border;


	assocScreen.Loop(container);
}

void FTXUIWindow::execute()
{
	bool showScreen     = true;
	int  optionSelected = 0;

	ftxui::Component menu = ftxui::Menu(options, &optionSelected) | ftxui::border;

	ftxui::Component menuEvents = CatchEvent(menu,
									  [&](ftxui::Event menuEvent)
										{
											if(  menuEvent == ftxui::Event::Return ||
												(menuEvent.is_mouse() &&
												 menuEvent.mouse().button == ftxui::Mouse::Left &&
												 menuEvent.mouse().motion == ftxui::Mouse::Released))
											{
												if(optionSelected == 0)
													screen.Exit();
												else
													showScreen = false;

												return true;
											}
											else
												return false;
										});

	ftxui::Component menuHider = ftxui::Maybe(menuEvents, &showScreen);

	ftxui::Loop eventLoop = ftxui::Loop(&screen, menuHider);
	while(!eventLoop.HasQuitted())
	{
		eventLoop.RunOnce();

		if(!showScreen)
		{
			screen.Clear();

			if(optionSelected == 1)
				 ctrlDlg->execute();
			//else if(optionSelected == 2)
				// open file
			//else if(optionSelected == 3)
				// save file
			if(optionSelected == 4)
				selectPixelizer();
			else if(optionSelected == 5)
				selectTransformer();
			else if(optionSelected == 6)
				selectAnalyzer();
			/*
			else if(optionSelected == 7)
				// choose map
			else if(optionSelected == 8)
				// choose graph
			*/
			else if(optionSelected == 9)
				printAssocStatus();
			/*
			else if(optionSelected == 10)
				// add association
			else if(optionSelected == 11)
				// change association
			*/

			showScreen = true;

			screen.PostEvent(ftxui::Event::Custom);
			menu->TakeFocus();
		}
	}
}

bool FTXUIWindow::selectFileName(bool read){return true; }

void FTXUIWindow::emitReadDataSets(FILETYPE* dataTypes, int* numTypes){}
void FTXUIWindow::emitSelectSlices(){}
void FTXUIWindow::emitSelectEnergies(){}

void FTXUIWindow::emitSaveDataSets(){}

bool FTXUIWindow::handleMissingTransformer(){ return true; }

void FTXUIWindow::configureDisplay(FILETYPE ft){}

void FTXUIWindow::emitSelectMapDisplay(int displayData){}
void FTXUIWindow::paintMap(unsigned char* map){}
void FTXUIWindow::clearMaps(){}

void FTXUIWindow::emitSelectGraphDisplay(int displayData){}
void FTXUIWindow::paintGraph(unsigned char* graph){}
void FTXUIWindow::clearGraphs(){}


