/***************************************************************************
 *   healpixdlg.cpp                                                        *
 *   Copyright (C) 2014 by Daniel Suson                                    *
 *   suson@calumet.purdue.edu                                              *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU General Public License     *
 *   along with this program; if not, write to the                         *
 *   Free Software Foundation, Inc.,                                       *
 *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
 *                                                                         *
 *   In addition, as a special exception, the copyright holders give       *
 *   permission to link the code of this program with any edition of       *
 *   the Qt library by Trolltech AS, Norway (or with modified versions     *
 *   of Qt that use the same license as Qt), and distribute linked         *
 *   combinations including the two.  You must obey the GNU General        *
 *   Public License in all respects for all of the code used other than    *
 *   Qt.  If you modify this file, you may extend this exception to        *
 *   your version of the file, but you are not obligated to do so.  If     *
 *   you do not wish to do so, delete this exception statement from        *
 *   your version.                                                         *
 ***************************************************************************
 * Description:                                                            *
 *                                                                         *
 * This class defines the healpix dialog structure associated with         *
 * the Qt4 user interface.                                                 *
 * ----------------------- Change Log ------------------------------------ *
 * Date    Name         Description                                        *
 *                                                                         *
 ***************************************************************************
 * This software evolved from work that was done by Eric Hivon at the      *
 * California Institute of Technology on the MASTER algorithm (Hivon, E.,  *
 * et al., ApJ, vol 567, p 2).  It adapts or interfaces with these         *
 * packages:                                                               *
 *                                                                         *
 * HealPix         (http://www.eso.org/science/healpix/)                   *
 * FTOOLS & FITSIO (http://heasarc.gsfc.nasa.gov/docs/corp/software.html)  *
 *                                                                         *
 * Any publications or presentations that use results generated by this    *
 * program must reference the fact that it was developed by Daniel Suson   *
 ***************************************************************************/
#include <math.h>
#include <limits>

#include "healpixdlg.h"

#include "../libanalyzer/matrixdata.h"
#include "../libanalyzer/healpix.h"

#include "../healpixdlgpar.h"

#include <ftxui/dom/elements.hpp>
#include <ftxui/screen/screen.hpp>
#include <ftxui/component/screen_interactive.hpp>
#include <ftxui/component/component.hpp>

#define SIDERES 0.00001

healpixDialog::healpixDialog(association* assoc, std::function<void()> s, std::function<void()> c)
              : healpixDialogParent(assoc),
                screen(ftxui::ScreenInteractive::TerminalOutput())
{
	successFunc = s;
	cancelFunc = c;
}

healpixDialog::~healpixDialog()
{
}

void healpixDialog::execute()
{
	double raRes = 0.0, decRes = 0.0;
    if (dataAssoc->exists(fileType::InputWeights))
	{
      raRes = dataAssoc->inputWeights()->RARes();
      decRes = dataAssoc->inputWeights()->DecRes();
    }

    if (dataAssoc->exists(fileType::InputData))
	{
      raRes = dataAssoc->inputData()->RARes();
      decRes = dataAssoc->inputData()->DecRes();
    }

    double skyRes = (decRes >= raRes) ? decRes : raRes;

    int skySides = sides(skyRes);
    double logSides = log(skySides)/log(2); // log base 2 of skySides

	// if log2(skySides) has a decimal
    if (abs(logSides - (int)logSides) > SIDERES)
	{
      skySides = std::pow(2,(int)logSides);
      skyRes = resolution(skySides);
    }


    nSides = skySides;
    res = skyRes;

	std::string nSidesInput = "";
	std::string resInput    = "";

	ftxui::InputOption nSidesOptions;
	nSidesOptions.multiline = false;
	nSidesOptions.on_change = [&] () {
										if(nSidesInput.length() > 0)
										{
											resInput = std::to_string(resolution(std::stoi(nSidesInput)));

											if(power2(std::stoi(nSidesInput)))
												skySides = std::stoi(nSidesInput);

											nSides = skySides;
										}
										else
											resInput = std::to_string(resolution(nSides));

										res = std::stod(resInput);
									};
	nSidesOptions.transform = [&](ftxui::InputState nSidesState)
								{
									ftxui::Element e = nSidesState.element;

									e = e | ftxui::bgcolor(ftxui::Color::GrayDark);

									if(nSidesState.focused)
										e = e | ftxui::bgcolor(ftxui::Color::White);

									if(nSidesInput.length() > 0 &&  !power2(std::stoi(nSidesInput)))
										e = e | ftxui::color(ftxui::Color::Red);
									else
										e = e | ftxui::color(ftxui::Color::Green);

									return e;
								};
	ftxui::Component nSidesInputBox = ftxui::Input(&nSidesInput, std::to_string(nSides), nSidesOptions);
	ftxui::Component nSidesDescr    = ftxui::Renderer([](){return ftxui::text("NSides (Power of 2): ");});

	ftxui::InputOption resOptions = ftxui::InputOption::Default();
	resOptions.transform = [&](ftxui::InputState resState)
							{
								ftxui::Element e = resState.element;
								e = e | ftxui::bgcolor(ftxui::Color::GrayDark);

								if(resState.focused)
									e = e | ftxui::bgcolor(ftxui::Color::White);

								return e;
							};
	ftxui::Component resInputBox = ftxui::Input(&resInput, std::to_string(res), resOptions);
	ftxui::Component resDescr    = ftxui::Renderer([](){return ftxui::text("Resoulution: ");});

	ftxui::Component nSidesResCont = ftxui::Container::Vertical({nSidesDescr, nSidesInputBox,
																resDescr,    resInputBox});
	ftxui::Component nSidesResGrided =
			ftxui::Renderer(nSidesResCont,
			[&](){
					ftxui::Element box = ftxui::gridbox
											({
												{ nSidesDescr->Render() , nSidesInputBox->Render()},
												{ resDescr->Render(),    resInputBox->Render()}
											});
					return ftxui::vbox
							({
								ftxui::text("Set the NSides/Resolution") | ftxui::bold | ftxui::hcenter,
								box
							});
				}) | ftxui::border;

	bool ringSelected = true;
	bool nestSelected = false;

	ftxui::CheckboxOption ringOption;
	ringOption.on_change = [&]()
							{
								if(ringSelected)
								{
									nestSelected = false;
									nestedFlag = false;
								}
								else
								{
									nestSelected = true;
									nestedFlag = true;
								}
							};
	ftxui::Component ringCheckBox = ftxui::Checkbox("Ring", &ringSelected, ringOption);

	ftxui::CheckboxOption nestOption;
	nestOption.on_change = [&]()
							{
								if(nestSelected)
								{
									ringSelected = false;
									nestedFlag = true;
								}
								else
								{
									ringSelected = true;
									nestedFlag = false;
								}
							};
	ftxui::Component nestCheckBox = ftxui::Checkbox("Nested", &nestSelected, nestOption);

	ftxui::Component indexComponent = ftxui::Renderer([](){return ftxui::text("Choose the Indexing Scheme") | ftxui::bold;});
	ftxui::Component indexContainer = ftxui::Container::Vertical({
																	indexComponent | ftxui::hcenter,
																	ringCheckBox,
																	nestCheckBox
																}) | ftxui::border;

	ftxui::Component resIndContainer = ftxui::Container::Horizontal({nSidesResGrided | ftxui::flex, indexContainer | ftxui::flex});

	ftxui::CheckboxOption pixAvgOption;
	pixAvgOption.on_change = [&]()
								{
									if(usePixAvg)
									{
										usePixDev = false;
										usePixVar = false;
										doAvgNorm = false;
										doVarNorm = false;
										doMinMax  = false;
									}
									else
										usePixAvg = false;
								};
	ftxui::Component pixAvgCheckbox = ftxui::Checkbox("Use Pixel Average", &usePixAvg, pixAvgOption);

	ftxui::CheckboxOption pixDevOption;
	pixDevOption.on_change = [&]()
								{
									if(usePixDev)
									{
										usePixAvg = false;
										usePixVar = false;
										doAvgNorm = false;
										doVarNorm = false;
										doMinMax  = false;
									}
									else
										usePixDev = false;
								};
	ftxui::Component pixDevCheckbox = ftxui::Checkbox("Use Pixel Deviance", &usePixDev, pixDevOption);

	ftxui::CheckboxOption pixVarOption;
	pixVarOption.on_change = [&]()
								{
									if(usePixVar)
									{
										usePixAvg = false;
										usePixDev = false;
										doAvgNorm = false;
										doVarNorm = false;
										doMinMax  = false;
									}
								};
	ftxui::Component pixVarCheckbox = ftxui::Checkbox("Use Pixel Variance", &usePixVar, pixVarOption);

	ftxui::CheckboxOption avgNormOption;
	avgNormOption.on_change = [&]()
								{
									if(doAvgNorm)
									{
										usePixAvg = false;
										usePixDev = false;
										usePixVar = false;
										doVarNorm = false;
										doMinMax  = false;
									}
									else
										doAvgNorm = false;
								};
	ftxui::Component avgNormCheckbox = ftxui::Checkbox("Do Average Normalization", &doAvgNorm, avgNormOption);

	ftxui::CheckboxOption varNormOption;
	varNormOption.on_change = [&]()
								{
									if(doVarNorm)
									{
										usePixAvg = false;
										usePixDev = false;
										usePixVar = false;
										doAvgNorm = false;
										doMinMax  = false;
									}
									else
										doVarNorm = false;
								};
	ftxui::Component varNormCheckbox = ftxui::Checkbox("Do Variance Normalization", &doVarNorm, varNormOption);

	ftxui::CheckboxOption minMaxOption;
	minMaxOption.on_change = [&]()
								{
									if(doMinMax)
									{
										usePixAvg = false;
										usePixDev = false;
										usePixVar = false;
										doAvgNorm = false;
										doVarNorm = false;
									}
									else
										doMinMax = false;
								};
	ftxui::Component minMaxCheckbox = ftxui::Checkbox("Do Min Max Scaling", &doMinMax, minMaxOption);

	ftxui::Component overPixContainer = ftxui::Container::Vertical({pixAvgCheckbox,  pixDevCheckbox,  pixVarCheckbox,
																	avgNormCheckbox, varNormCheckbox, minMaxCheckbox});

	ftxui::Component overPixGrided =
			ftxui::Renderer(overPixContainer,
				[&](){
						ftxui::Element box =  ftxui::gridbox({
												{pixAvgCheckbox->Render()  | ftxui::flex,  pixDevCheckbox->Render() | ftxui::flex,  pixVarCheckbox->Render()},
												{avgNormCheckbox->Render() | ftxui::flex, varNormCheckbox->Render() | ftxui::flex,  minMaxCheckbox->Render()}
															});

						return ftxui::vbox
										({
											ftxui::text("Overpixelization Methods") | ftxui::bold | ftxui::hcenter,
											box
										});
					 }) | ftxui::border;


	ftxui::Component cancelButton = ftxui::Button("Cancel", [&](){screen.Exit(); this->cancelFunc();})  | ftxui::flex;
	ftxui::Component submitButton = ftxui::Button("Submit", [&](){screen.Exit(); this->successFunc();}) | ftxui::flex;
	ftxui::Component buttonCont   = ftxui::Container::Horizontal({cancelButton, submitButton}) | ftxui::border;

	ftxui::Component healpixTextComp = ftxui::Renderer([](){return ftxui::text("HealPIX Configuration.") | ftxui::border | ftxui::bold;});
	ftxui::Component healpixContainer = ftxui::Container::Vertical({
																		healpixTextComp | ftxui::hcenter,
																		resIndContainer,
																		overPixGrided, //overPixContainer,
																		buttonCont
																}) | ftxui::border;

	screen.Loop(healpixContainer);
}

void healpixDialog::setNSides()
{

}

void healpixDialog::setIndexing()
{

}

void healpixDialog::setOverpixelization()
{

}

bool healpixDialog::confirm()
{
return false;
}

bool healpixDialog::power2(int s)
{
	double log2S = log(s)/log(2); // log base 2 of s

	// if log2(s) has a decimal
    if (abs(log2S - (int)log2S) > SIDERES)
		return false;
    else
		return true;
}

void healpixDialog::clearInput()
{
}

void healpixDialog::clearScreen()
{}

void healpixDialog::configure()
{
}

void healpixDialog::reset()
{
  usePixAvg = false;
  usePixDev = false;
  usePixVar = false;
  doAvgNorm = false;
  doVarNorm = false;
  doMinMax  = false;

  nestedFlag = true;
  dirty = false;
  isConfigured = false;
}

void healpixDialog::validate()
{
}

void healpixDialog::syncSides()
{
	/*
  QString title, message;

  int userSides = ui->sideEdit->text().toInt();
  double logSides = log(userSides)/log(2);
  if (abs(logSides - (int)logSides) > SIDERES) {
    int modSides = std::pow(2,(int)logSides);
    title = QString(tr("Invalid number of sides entered"));
    message = QString(tr("Number of sides must be a multiple of two\nWould you like to use %1 instead?")).arg(modSides);
    int result = QMessageBox::question(this,title,message,QMessageBox::Yes | QMessageBox::No,QMessageBox::Yes);
    if (result == QMessageBox::Yes)
      userSides = modSides;
    else {
      message = QString(tr("Please enter a valid number of sides"));
      QMessageBox::information(this,title,message);
      return;
    }
  }
  nSides = userSides;
  res = resolution(nSides);
  ui->resEdit->clear();
  ui->resEdit->insert(QString::number(res));
  repaint();
  */
}

void healpixDialog::finalize()
{
}

void healpixDialog::help()
{
}

void healpixDialog::cancel()
{
}
