/***************************************************************************
 *   rshtdlg.cpp                                                           *
 *   Copyright (C) 2014 by Daniel Suson                                    *
 *   suson@calumet.purdue.edu                                              *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU General Public License     *
 *   along with this program; if not, write to the                         *
 *   Free Software Foundation, Inc.,                                       *
 *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
 *                                                                         *
 *   In addition, as a special exception, the copyright holders give       *
 *   permission to link the code of this program with any edition of       *
 *   the Qt library by Trolltech AS, Norway (or with modified versions     *
 *   of Qt that use the same license as Qt), and distribute linked         *
 *   combinations including the two.  You must obey the GNU General        *
 *   Public License in all respects for all of the code used other than    *
 *   Qt.  If you modify this file, you may extend this exception to        *
 *   your version of the file, but you are not obligated to do so.  If     *
 *   you do not wish to do so, delete this exception statement from        *
 *   your version.                                                         *
 ***************************************************************************
 * Description:                                                            *
 *                                                                         *
 * This class defines the rsht dialog structure associated with            *
 * the Qt4 user interface.                                                 *
 * ----------------------- Change Log ------------------------------------ *
 * Date    Name         Description                                        *
 *                                                                         *
 ***************************************************************************
 * This software evolved from work that was done by Eric Hivon at the      *
 * California Institute of Technology on the MASTER algorithm (Hivon, E.,  *
 * et al., ApJ, vol 567, p 2).  It adapts or interfaces with these         *
 * packages:                                                               *
 *                                                                         *
 * HealPix         (http://www.eso.org/science/healpix/)                   *
 * FTOOLS & FITSIO (http://heasarc.gsfc.nasa.gov/docs/corp/software.html)  *
 *                                                                         *
 * Any publications or presentations that use results generated by this    *
 * program must reference the fact that it was developed by Daniel Suson   *
 ***************************************************************************/
#include "rshtdlg.h"
#include <limits>

#include <ftxui/dom/elements.hpp>
#include <ftxui/screen/screen.hpp>
#include <ftxui/component/screen_interactive.hpp>
#include <ftxui/component/component.hpp>


rshtDialog::rshtDialog(association *assoc, std::function<void()> s, std::function<void()> c)
            : rshtDialogParent(assoc), screen(ftxui::ScreenInteractive:://FitComponent())
																		TerminalOutput())
{
	successFunc = s;
	cancelFunc = c;
}

rshtDialog::~rshtDialog()
{
}

void rshtDialog::execute()
{
	std::string minDef = "0";
	std::string maxDef = "100";
	std::string iterDef = "1";

	std::string minData = "0";
	std::string maxData = "100";
	std::string iterData = "1";

	minIndex = 0;
	maxIndex = 100;
	noIterations = 1;

	int tempMin = minIndex;
	int tempMax = maxIndex;
	int tempIter = noIterations;

	ftxui::Component emptySpace = ftxui::Renderer([](){return ftxui::text("  ");});

	std::function<ftxui::Component(std::string)> labelMaker = [&](std::string str)
																{
																	ftxui::Component labelComp =
																				ftxui::Renderer([str](bool focused)
																				{
																					ftxui::Element label = ftxui::text(str) | ftxui::focus;
																					if(focused)
																						return label | ftxui::color(ftxui::Color::Black) | ftxui::bgcolor(ftxui::Color::GrayLight);

																					return label;
																				});
																	return labelComp;
																};

	std::function<void()> inputChange = [&]()
										{
											if(minData.length() > 0 && minData != "-")
												tempMin = std::stoi(minData);

											if(maxData.length() > 0 && maxData != "-")
												tempMax = std::stoi(maxData);

											if(iterData.length() > 0 && iterData != "-")
												tempIter = std::stoi(iterData);

											if(tempMin >= 0 && tempMin < tempMax)
												minIndex = tempMin;

											if(tempMax > 0 && tempMax > tempMin)
												maxIndex = tempMax;

											if(tempIter > 0)
												noIterations = tempIter;
										};


	ftxui::InputOption minOptions;
	minOptions.transform = [&](ftxui::InputState minState)
							{
								ftxui::Element minEl = minState.element | ftxui::bgcolor(ftxui::Color::GrayDark);

								if(tempMin < 0 || tempMin >= tempMax)
									minEl = minEl | ftxui::color(ftxui::Color::Red);
								else
									minEl = minEl | ftxui::color(ftxui::Color::Green);

								return minEl;
							};
	minOptions.on_change = inputChange;
	ftxui::Component minInput = ftxui::Input(&minData, minDef, minOptions);
	ftxui::Component minLabel = labelMaker("Min Index:");
	ftxui::Component minCont  = ftxui::Container::Horizontal({minLabel, emptySpace, minInput}) | ftxui::border;

	ftxui::InputOption maxOptions;
	maxOptions.transform = [&](ftxui::InputState maxState)
							{
								ftxui::Element maxEl = maxState.element | ftxui::bgcolor(ftxui::Color::GrayDark);

								if(tempMax <= 0 || tempMax <= tempMin)
									maxEl = maxEl | ftxui::color(ftxui::Color::Red);
								else
									maxEl = maxEl | ftxui::color(ftxui::Color::Green);

								return maxEl;
							};
	maxOptions.on_change = inputChange;
	ftxui::Component maxInput = ftxui::Input(&maxData, maxDef, maxOptions);
	ftxui::Component maxLabel = labelMaker("Max Index:");
	ftxui::Component maxCont  = ftxui::Container::Horizontal({maxLabel, emptySpace, maxInput}) | ftxui::border;

	ftxui::InputOption iterOptions;
	iterOptions.transform = [&](ftxui::InputState iterState)
							{
								ftxui::Element iterEl = iterState.element | ftxui::bgcolor(ftxui::Color::GrayDark);

								if(tempIter <= 0)
									iterEl = iterEl | ftxui::color(ftxui::Color::Red);
								else
									iterEl = iterEl | ftxui::color(ftxui::Color::Green);

								return iterEl;
							};
	iterOptions.on_change = inputChange;
	ftxui::Component iterInput = ftxui::Input(&iterData, iterDef, iterOptions);
	ftxui::Component iterLabel = labelMaker("Iterations:");
	ftxui::Component iterCont  = ftxui::Container::Horizontal({iterLabel, emptySpace, iterInput}) | ftxui::border;

	ftxui::Component cancelButton = ftxui::Button("Cancel", [&](){screen.Exit(); this->cancelFunc();})  | ftxui::flex;
	ftxui::Component submitButton = ftxui::Button("Submit", [&](){screen.Exit(); this->successFunc();}) | ftxui::flex;
	ftxui::Component buttonCont   = ftxui::Container::Horizontal({cancelButton, submitButton}) | ftxui::border;

	ftxui::Component title = ftxui::Renderer([](){return ftxui::text("RSht Configuration") | ftxui::border | ftxui::bold | ftxui::hcenter;});
	ftxui::Component container = ftxui::Container::Vertical({title, minCont, maxCont, iterCont, buttonCont}) | ftxui::border | ftxui::hcenter;

	screen.Loop(container);
}

void rshtDialog::setRange()
{
}

void rshtDialog::setIter()
{
}

bool rshtDialog::confirm()
{
	return true;
}

void rshtDialog::clearInput()
{
}

void rshtDialog::configure()
{
}

void rshtDialog::reset()
{
}

void rshtDialog::validate()
{
}

void rshtDialog::finalize()
{
}

void rshtDialog::help()
{
}

void rshtDialog::cancel()
{
}
