/***************************************************************************
 *   spectrumdlg.cpp                                                       *
 *   Copyright (C) 2014 by Daniel Suson                                    *
 *   suson@calumet.purdue.edu                                              *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU General Public License     *
 *   along with this program; if not, write to the                         *
 *   Free Software Foundation, Inc.,                                       *
 *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
 *                                                                         *
 *   In addition, as a special exception, the copyright holders give       *
 *   permission to link the code of this program with any edition of       *
 *   the Qt library by Trolltech AS, Norway (or with modified versions     *
 *   of Qt that use the same license as Qt), and distribute linked         *
 *   combinations including the two.  You must obey the GNU General        *
 *   Public License in all respects for all of the code used other than    *
 *   Qt.  If you modify this file, you may extend this exception to        *
 *   your version of the file, but you are not obligated to do so.  If     *
 *   you do not wish to do so, delete this exception statement from        *
 *   your version.                                                         *
 ***************************************************************************
 * Description:                                                            *
 *                                                                         *
 * This class defines the spectrum dialog structure associated with        *
 * the Qt4 user interface.                                                 *
 * ----------------------- Change Log ------------------------------------ *
 * Date    Name         Description                                        *
 *                                                                         *
 ***************************************************************************
 * This software evolved from work that was done by Eric Hivon at the      *
 * California Institute of Technology on the MASTER algorithm (Hivon, E.,  *
 * et al., ApJ, vol 567, p 2).  It adapts or interfaces with these         *
 * packages:                                                               *
 *                                                                         *
 * HealPix         (http://www.eso.org/science/healpix/)                   *
 * FTOOLS & FITSIO (http://heasarc.gsfc.nasa.gov/docs/corp/software.html)  *
 *                                                                         *
 * Any publications or presentations that use results generated by this    *
 * program must reference the fact that it was developed by Daniel Suson   *
 ***************************************************************************/
#include "spectrumdlg.h"

#include <limits>
#include <iomanip>

#include <ftxui/component/component.hpp>
#include <ftxui/component/screen_interactive.hpp>
#include <ftxui/dom/elements.hpp>
#include <ftxui/screen/screen.hpp>

spectrumDialog::spectrumDialog(std::function<void()> s, std::function<void()> c)
			: spectrumDialogParent(), screen(ftxui::ScreenInteractive::TerminalOutput())
{
	successFunc = s;
	cancelFunc = c;
}

spectrumDialog::~spectrumDialog()
{
}

void spectrumDialog::execute()
{

	std::function<ftxui::Component(std::string)> labelMaker = [&](std::string str)
																{
																	ftxui::Component labelComp =
																				ftxui::Renderer([str](bool focused)
																				{
																					ftxui::Element label = ftxui::text(str) | ftxui::focus;
																					if(focused)
																						return label | ftxui::color(ftxui::Color::Black) | ftxui::bgcolor(ftxui::Color::GrayLight);

																					return label;
																				});
																	return labelComp;
																};

	int tempEns = 1;
	int tempBin = 3;
	int tempMask = 0;

	std::string ensDef = "1";
	std::string binDef = "3";
	std::string maskDef = "0";

	std::string ensData = "1";
	std::string binData = "3";
	std::string maskData = "0";

	std::function<void()> inputChange = [&]()
										{
											if(ensData.length() > 0 && ensData != "-")
												tempEns = std::stoi(ensData);

											if(binData.length() > 0 && binData != "-")
												tempBin = std::stoi(binData);

											if(maskData.length() > 0 && maskData != "-")
												tempMask = std::stoi(maskData);

											if(tempEns >= 1)
												ensIter = tempEns;

											if(tempBin >=3)
												binSize = tempBin;

											if(tempMask >= 0)
												maskInd = tempMask;
										};

	ftxui::Component emptySpace = ftxui::Renderer([](){return ftxui::text(" ");});

	ftxui::InputOption ensOption;
	ensOption.transform = [&](ftxui::InputState ensState)
							{
								ftxui::Element ensEl = ensState.element | ftxui::bgcolor(ftxui::Color::GrayDark);

								if(tempEns < 1)
									ensEl = ensEl | ftxui::color(ftxui::Color::Red);
								else
									ensEl = ensEl | ftxui::color(ftxui::Color::Green);

								return ensEl;
							};
	ensOption.on_change = inputChange;
	ftxui::Component ensInput = ftxui::Input(&ensData, ensDef, ensOption);
	ftxui::Component ensLabel = labelMaker("Ensemble Iterations:");
	ftxui::Component ensCont  = ftxui::Container::Horizontal({ensLabel, emptySpace, ensInput}) | ftxui::border;

	ftxui::InputOption binOption;
	binOption.transform = [&](ftxui::InputState binState)
							{
								ftxui::Element binEl = binState.element | ftxui::bgcolor(ftxui::Color::GrayDark);

								if(tempBin < 3)
									binEl = binEl | ftxui::color(ftxui::Color::Red);
								else
									binEl = binEl | ftxui::color(ftxui::Color::Green);

								return binEl;
							};
	binOption.on_change = inputChange;
	ftxui::Component binInput = ftxui::Input(&binData, binDef, binOption);
	ftxui::Component binLabel = labelMaker("Number l's per bin:");
	ftxui::Component binCont  = ftxui::Container::Horizontal({binLabel, emptySpace, binInput}) | ftxui::border;

	ftxui::InputOption maskOption;
	maskOption.transform = [&](ftxui::InputState maskState)
							{
								ftxui::Element maskEl = maskState.element | ftxui::bgcolor(ftxui::Color::GrayDark);

								if(tempMask < 0)
									maskEl = maskEl | ftxui::color(ftxui::Color::Red);
								else
									maskEl = maskEl | ftxui::color(ftxui::Color::Green);

								return maskEl;
							};
	maskOption.on_change = inputChange;
	ftxui::Component maskInput = ftxui::Input(&maskData, maskDef, maskOption);
	ftxui::Component maskLabel = labelMaker("Number l's to mask out:");
	ftxui::Component maskCont  = ftxui::Container::Horizontal({maskLabel, emptySpace, maskInput}) | ftxui::border;

	ftxui::Component cancelButton = ftxui::Button("Cancel", [&](){screen.Exit(); this->cancelFunc();})  | ftxui::flex;
	ftxui::Component submitButton = ftxui::Button("Submit", [&](){screen.Exit(); this->successFunc();}) | ftxui::flex;
	ftxui::Component buttonCont   = ftxui::Container::Horizontal({cancelButton, submitButton}) | ftxui::border;

	ftxui::Component title = ftxui::Renderer([](){return ftxui::text("Analyzer Configuration") | ftxui::border | ftxui::bold | ftxui::hcenter;});
	ftxui::Component container = ftxui::Container::Vertical({title, binCont, ensCont, maskCont, buttonCont}) | ftxui::border | ftxui::hcenter;

	screen.Loop(container);
}

void spectrumDialog::setBinSize()
{
}

void spectrumDialog::setEnsAvg()
{
}

void spectrumDialog::setMaskIndex()
{
}

bool spectrumDialog::confirm()
{
	return true;
}

void spectrumDialog::clearInput()
{
}

void spectrumDialog::configure()
{
}

void spectrumDialog::reset()
{
}

void spectrumDialog::validate()
{
}


void spectrumDialog::finalize()
{
}

void spectrumDialog::help()
{
}

void spectrumDialog::cancel()
{
}
